// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconCamera(props: IconProps) {
  return <Icon type="Camera" {...props} />
}

export default IconCamera
