// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconFilm(props: IconProps) {
  return <Icon type="Film" {...props} />
}

export default IconFilm
