// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { CornerRightUp } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconCornerRightUp(props: any) {
    return <IconBase icon={CornerRightUp} {...props} />
  }

  export default IconCornerRightUp
  