// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconCornerRightUp(props: IconProps) {
  return <Icon type="CornerRightUp" {...props} />
}

export default IconCornerRightUp
