// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { UploadCloud } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconUploadCloud(props: any) {
    return <IconBase icon={UploadCloud} {...props} />
  }

  export default IconUploadCloud
  