// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { ArrowRight } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconArrowRight(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={ArrowRight} {...props} />
}

export default IconArrowRight
