---
id: introduction
title: Introduction
hideTitle: true
---

<div className="flex items-start gap-6 not-prose" id="introduction">
  <div className="flex flex-col gap-2">
    <h1 className="text-3xl text-foreground m-0">Self-Hosting Analytics</h1>
  </div>
</div>

<RefSubLayout.EducationRow>
  <RefSubLayout.Details>

The Supabase Analytics server is a Logflare self-hostable instance that manages the ingestion and query pipelines for searching and aggregating structured analytics events.

When running the Analytics server, the logging experience matching that of the Supabase Platform is available in Studio. However, log content and metadata can differ from the Supabase Platform - see **[Differences from the Supabase platform](#differences-from-the-supabase-platform)** below.

Locally running logs and analytics are supported in two separate setups:

- **[Local development & CLI](/docs/guides/local-development)** - a local Supabase stack managed with the Supabase CLI (`supabase start`).
- **[Self-hosted Supabase](/docs/guides/self-hosting)** - the full stack on your own infrastructure with Docker Compose. Logs & Analytics are **optional** and are not started by default.

The sections below cover backend options and Logflare configuration. For self-hosted Supabase, see the [installation and configuration](/docs/guides/self-hosting/docker) guide.

<Admonition type="note" title="Logflare Technical Docs">

All Logflare technical documentation is available at https://docs.logflare.app.

</Admonition>

## Supported backends

The Analytics server supports either **Postgres** or **BigQuery** as the backend. Both [Local development & CLI](/docs/guides/local-development) and [self-hosted Supabase](/docs/guides/self-hosting) use the Postgres backend out of the box.

When using the BigQuery backend, a BigQuery dataset is created in the provided Google Cloud project, and tables are created for each source. Log events are streamed into each table, and all queries generated by Studio or by the Logs Explorer are executed against the BigQuery API. This backend requires internet access to work, and cannot be run fully locally.

When using the Postgres backend, tables are created for each source within the provided schema. Log events received by Logflare are inserted directly into the respective tables. All BigQuery-dialect SQL queries from Studio are handled by a translation layer **within the Analytics server**. This translation layer translates the query to Postgres dialect, and then executes it against the Postgres database.

The Postgres backend is not yet optimized for a high volume of inserts, or for heavy query usage. Today the translation layer only handles a limited subset of the BigQuery dialect. As such, the [Log Explorer](https://supabase.com/docs/guides/platform/logs#logs-explorer) may produce errors for more advanced queries when using the Postgres Backend.

## Getting started

The Postgres backend is recommended when familiarizing and experimenting. For production self-hosting, we recommend the BigQuery backend. See the [notes](#recommendations-for-production) below for more information.

### Local development & CLI

With the Supabase CLI, run `supabase start` to bring up a local stack. Logs use the Postgres backend by default and are stored in the `_analytics` schema. Docker socket access may need manual configuration on some platforms - see the [Access your project's services](/docs/guides/local-development/cli/getting-started#access-your-projects-services) (the Analytics tab).

<Admonition type="caution">

The Supabase CLI is intended for local development only. The local analytics service uses predefined, publicly known access tokens and has no protection against external traffic. Never run the CLI stack on a publicly accessible or untrusted network.

</Admonition>

### Self-hosted Supabase

Self-hosted Supabase does **not** include Logs & Analytics in the default Docker Compose configuration. You must first install and secure the base stack - generate secrets, configure URLs, and set a Studio password - as described in [Self-Hosting with Docker](/docs/guides/self-hosting/docker).

<Admonition type="danger">

**Do not** start the stack with placeholder values from `.env.example`.

</Admonition>

After the base stack is configured, enable Logs & Analytics from your project directory (the directory containing `docker-compose.yml`):

```sh
sh run.sh config add logs && \
sh run.sh start
```

This layers [`docker-compose.logs.yml`](https://github.com/supabase/supabase/blob/master/docker/docker-compose.logs.yml) on top of the base configuration and starts two additional services (`analytics` and `vector`).

See [Enabling analytics](/docs/guides/self-hosting/docker#enabling-analytics) in the self-hosting guide for more context.

### Required Logflare configuration

The following environment variables are always required for the `supabase/logflare` image:

```yaml name=docker-compose.logs.yml
analytics:
  environment:
    # Enable single-tenant mode for Logflare
    LOGFLARE_SINGLE_TENANT: 'true'
    # Seed Supabase-related metadata
    LOGFLARE_SUPABASE_MODE: 'true'
```

For all other configuration environment variables, refer to the [Logflare self-hosting documentation](https://docs.logflare.app/self-hosting/#configuration).

## Using the Postgres backend

### Local development & CLI

The CLI uses the Postgres backend by default. No additional configuration is needed.

### Self-hosted Supabase

The [`docker-compose.logs.yml`](https://github.com/supabase/supabase/blob/master/docker/docker-compose.logs.yml) override uses the Postgres backend by default.

#### Configuration and requirements

The following environment variables control the Postgres backend (set in `docker-compose.logs.yml`):

- `POSTGRES_BACKEND_URL`: Required. Connection string to the Postgres database.
- `POSTGRES_BACKEND_SCHEMA`: Optional. Schema used to store log data (default: `_analytics`).

## Using the BigQuery backend

The BigQuery backend is a more robust and scalable backend option that is battle-tested and production ready. Use this backend if you intend to have heavy logging usage and require advanced querying features such as the Logs Explorer.

### Requirements

Using the BigQuery backend requires:

- A Google Cloud project with billing enabled
- The project ID
- The project number
- A service account JSON key

A valid billing account is required for BigQuery streaming inserts.

### Google Cloud Console setup

1. Open [Google Cloud Console](https://console.cloud.google.com/) and select or create the project you want to use for analytics.
2. Confirm **billing is enabled** on that project ([Billing](https://console.cloud.google.com/billing) - link the project to a billing account if needed).
3. Go to **IAM & Admin > Service Accounts** and click **Create service account** (for example, `supabase-analytics`).
4. On **Permissions**, grant **BigQuery Admin** to keep setup simple. Skip **Principals with access**. Alternatively, grant only the specific permissions listed below instead of the admin role.
5. Open the service account, then **Keys** (or **Actions > Manage keys** from the list view). Click **Add key > Create new key**, choose **JSON**, and download the key file.
6. Go to **APIs & Services > Library**, search for **Cloud Resource Manager API**, open it, and click **Enable**. Confirm the correct project is selected in the project picker at the top. You can also enable it directly: `https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=YOUR_PROJECT_ID` (replace `YOUR_PROJECT_ID`).
7. Go to **Cloud overview > Dashboard** (home dashboard for the project) and copy the **Project ID** and **Project number**. Confirm the project picker at the top shows the same project you configured above.
8. Save the downloaded JSON key as `gcloud.json` in your self-hosted Supabase project directory (the directory that contains `docker-compose.yml`.

<Admonition type="caution">

Do not commit `gcloud.json` to version control. Add it to `.gitignore` if needed.

</Admonition>

<Admonition type="note" title="Minimum BigQuery permissions">

If you prefer not to use the **BigQuery Admin** role, the service account needs at least the following permissions:

- `bigquery.datasets.create`, `bigquery.datasets.get`, `bigquery.datasets.getIamPolicy`, `bigquery.datasets.update`
- `bigquery.jobs.create`
- `bigquery.routines.create`, `bigquery.routines.update`
- `bigquery.tables.create`, `bigquery.tables.delete`, `bigquery.tables.get`, `bigquery.tables.getData`, `bigquery.tables.update`, `bigquery.tables.updateData`

</Admonition>

### Self-hosted Supabase configuration

Complete [Self-Hosting with Docker](/docs/guides/self-hosting/docker) first. Enable the logs override, then switch the `analytics` service in [`docker-compose.logs.yml`](https://github.com/supabase/supabase/blob/master/docker/docker-compose.logs.yml) from Postgres to BigQuery.

**1. Set Google Cloud variables in `.env`**

Add your project values under the Analytics section (do not leave the `.env.example` placeholders):

```sh
############
# Logs and Analytics
############

# Google Cloud Project details
GOOGLE_PROJECT_ID=your-project-id
GOOGLE_PROJECT_NUMBER=123456789012
```

**2. Mount the service account key and switch the analytics backend**

In `docker-compose.logs.yml`, under the `analytics` service:

- Remove or comment out `POSTGRES_BACKEND_URL` and `POSTGRES_BACKEND_SCHEMA`.
- Uncomment `GOOGLE_PROJECT_ID` and `GOOGLE_PROJECT_NUMBER`.
- Uncomment the `volumes` block and bind-mount `gcloud.json` from your project directory.

Example:

```yml name=docker-compose.logs.yml
analytics:
  environment:
    GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
    GOOGLE_PROJECT_NUMBER: ${GOOGLE_PROJECT_NUMBER}
  volumes:
    - ./gcloud.json:/opt/app/rel/logflare/bin/gcloud.json:ro,z
```

**3. Start the stack**

From your project directory:

```sh
sh run.sh config add logs && \
sh run.sh start
```

## Log collection and routing with Vector

In the self-hosted Docker Compose setup, [Vector](https://github.com/vectordotdev/vector) is used for the logging pipeline when the `docker-compose.logs.yml` override is enabled. Log events are forwarded to the Analytics API for ingestion.

Please refer to the [Vector configuration file](https://github.com/supabase/supabase/blob/master/docker/volumes/logs/vector.yml) when customizing your own setup.

You must ensure that each payload matches the event shape produced by the Vector transforms. Logs Explorer in Studio expects the fields below when querying Analytics sources:

| Field           | Description                                                                                                                                                                                 |
| --------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `event_message` | The log message displayed in Studio.                                                                                                                                                        |
| `timestamp`     | The event timestamp. If omitted, Logflare assigns an ingestion timestamp.                                                                                                                   |
| `metadata`      | A JSON object with service-specific fields used by the Logs UI. For example, API logs include request and response metadata, while database logs include parsed Postgres severity metadata. |

When adding a custom Vector source, map your service logs to this shape before sending them to `http://analytics:4000/api/logs?source_name=<source-name>`. Reuse the existing source names in `vector.yml` if you want the logs to appear in the built-in Studio Logs panels.

## Differences from the Supabase platform

API logs rely on the locally running API gateway (Kong) instead of the Supabase Cloud API Gateway. Logs from Kong are not enriched with platform-only data.

Within self-hosted Supabase (with the logs override enabled), container logs are routed to Logflare via Vector. As Kong routes API requests to PostgREST, self-hosted and [local development & CLI](/docs/guides/local-development) deployments produce Kong request logs rather than the platform API gateway logs.

This results in differences in log event metadata between your own infrastructure and the Supabase Platform.

## Recommendations for production

When running a self-hosted instance of Logflare in production, we recommend the following.

### Set unique access tokens

<Admonition type="danger">

`LOGFLARE_PUBLIC_ACCESS_TOKEN` and `LOGFLARE_PRIVATE_ACCESS_TOKEN` **must** be set to unique, randomly generated values. Never run with the placeholder or default values.

</Admonition>

In a self-hosted Supabase configuration, these tokens are generated automatically when you run `sh utils/generate-keys.sh` during initial setup.

### Restrict network access to Logflare

Self-hosted Logflare has UI authentication disabled.

<Admonition type="caution">

The `/dashboard` path is publicly accessible by default and **must** be restricted at the network level. If you need dashboard access for managing sources, place it behind a VPN or other secure access layer.

</Admonition>

Direct access to the Logflare's container port 4000 is intentionally not exposed in the default self-hosted Supabase configuration - Logflare is only reachable through the API gateway (Kong). Do not re-expose this port directly unless required.

### Use a different Postgres Database to store Logflare data

Logflare requires a Postgres database to function. However, if there is an issue with you self-hosted Postgres service, you would not be able to debug it as it would also bring down Logflare.

The self-hosted Docker example is a minimal reference for running the entire stack; it is not recommended to use the same Postgres instance for both production workloads and observability data.

### Use BigQuery as the Logflare backend

The current Postgres Ingestion backend isn't optimized for production usage. We recommend using BigQuery for more heavy use cases.

**We recommend using the BigQuery backend for production environments as it offers better scaling and querying/debugging experiences.**

### Rotate encryption keys regularly

The Logflare server uses the a Base64 encryption key optionally set via the `LOGFLARE_DB_ENCRYPTION_KEY` environment variable to perform encryption at rest for sensitive database columns.

To perform encryption key rotation, move the retired key to the `LOGFLARE_DB_ENCRYPTION_KEY_RETIRED` environment variable, and replace the `LOGFLARE_DB_ENCRYPTION_KEY` environement variable with the new key. Perform a server restart and check `info` logs for the migration to be detected and performed.

Once migration is complete, you can safely remove the retired key.

  </RefSubLayout.Details>

  <RefSubLayout.Examples>

    ### Client libraries

    - [JavaScript - Pino Transport](https://github.com/Logflare/pino-logflare)
    - [Elixir](https://github.com/Logflare/logflare_api_client)
    - [Elixir - Logger Backend](https://github.com/Logflare/logflare_logger_backend)
    - [Erlang](https://github.com/Logflare/logflare_erl)
    - [Erlang - Lager Backend](https://github.com/Logflare/logflare_lager_backend)
    - [Cloudflare Worker](https://gist.github.com/chasers/c7a220e91820a1084b27fcfdb18ad6bd)

    ### Integrations

    - [Fly - Logs](https://github.com/Logflare/fly-log-shipper)
    - [Vercel Integration - Logs](https://vercel.com/integrations/logflare)
    - [Cloudflare App - Logs](https://www.cloudflare.com/apps/logflare/install)

    ### Additional links

    - [Source code](https://github.com/logflare/logflare)
    - [OpenAPI docs](https://logflare.app/api/openapi)
    - [Supabase Acquires Logflare](https://supabase.com/blog/supabase-acquires-logflare)
    - [Logflare self-hosting docs](https://docs.logflare.app/self-hosting)

  </RefSubLayout.Examples>

</RefSubLayout.EducationRow>
