// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Coffee } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconCoffee(props: any) {
    return <IconBase icon={Coffee} {...props} />
  }

  export default IconCoffee
  