// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconSmile(props: IconProps) {
  return <Icon type="Smile" {...props} />
}

export default IconSmile
