// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconShield(props: IconProps) {
  return <Icon type="Shield" {...props} />
}

export default IconShield
