// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconGlobe(props: IconProps) {
  return <Icon type="Globe" {...props} />
}

export default IconGlobe
