// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Globe } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconGlobe(props: any) {
    return <IconBase icon={Globe} {...props} />
  }

  export default IconGlobe
  