// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconBarChart(props: IconProps) {
  return <Icon type="BarChart" {...props} />
}

export default IconBarChart
