// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { BarChart2 } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconBarChart2(props: any) {
    return <IconBase icon={BarChart2} {...props} />
  }

  export default IconBarChart2
  