import dayjs from 'dayjs'

import { LogsTableName, type SqlFilterEntry } from './Logs.constants'
import type { Filters, LogData, LogsEndpointParams, QueryType } from './Logs.types'
import { buildWhereClauses } from './Logs.utils'
import { parseOtelTimestamp, type OtelLogRow } from '@/data/logs/otel-inspection.utils'
import {
  joinSqlFragments,
  analyticsLiteral as lit,
  safeSql,
  type SafeLogSqlFragment,
} from '@/data/logs/safe-analytics-sql'

/**
 * OTEL / ClickHouse query builders for the legacy per-service logs pages.
 *
 * The OTEL endpoint (`logs.all.otel`) stores every log source in a single
 * `logs` table keyed by a `source` column, with the per-log fields the old
 * BigQuery queries unnested from `metadata` exposed flat in the `log_attributes`
 * Map. These builders mirror the BigQuery generators in `Logs.utils.ts` but emit
 * ClickHouse SQL and alias columns to the exact leaf names the existing row
 * renderers read, so the UI needs no changes.
 *
 * Everything that varies per table — the `source` value, the projected columns,
 * the chart severity buckets, the filter templates, and any always-on predicate
 * — lives in a single `OTEL_SOURCES` descriptor so each table is described once
 * and coverage can be eyeballed against `LogsTableName`.
 */

const attr = (key: string): SafeLogSqlFragment => safeSql`log_attributes[${lit(key)}]`
const statusAsInt = (key: string): SafeLogSqlFragment => safeSql`toInt32OrZero(${attr(key)})`

// Severity predicates, reused across the chart and (for auth) the filter
// templates so a row buckets identically wherever it is classified. These are
// the OTEL counterparts of the BigQuery getError/getWarningCondition switches
// and the AUTH_LOG_* constants in Logs.constants.ts.
const HTTP_ERROR: SafeLogSqlFragment = safeSql`${statusAsInt('response.status_code')} >= 500`
const HTTP_WARNING: SafeLogSqlFragment = safeSql`${statusAsInt('response.status_code')} BETWEEN 400 AND 499`
const PG_ERROR: SafeLogSqlFragment = safeSql`${attr('parsed.error_severity')} IN ('ERROR', 'FATAL', 'PANIC')`
const PG_WARNING: SafeLogSqlFragment = safeSql`${attr('parsed.error_severity')} = 'WARNING'`
const FN_ERROR: SafeLogSqlFragment = safeSql`${attr('level')} IN ('error', 'fatal')`
const FN_WARNING: SafeLogSqlFragment = safeSql`${attr('level')} = 'warning'`
const MULTIGRES_ERROR: SafeLogSqlFragment = safeSql`JSONExtractString(event_message, 'level') IN ('ERROR', 'FATAL', 'PANIC')`
const MULTIGRES_WARNING: SafeLogSqlFragment = safeSql`JSONExtractString(event_message, 'level') IN ('WARN', 'WARNING')`
const AUTH_ERROR: SafeLogSqlFragment = safeSql`${attr('level')} IN ('error', 'fatal') OR ${statusAsInt('status')} >= 500`
const AUTH_WARNING: SafeLogSqlFragment = safeSql`${attr('level')} = 'warning' OR ${statusAsInt('status')} BETWEEN 400 AND 499`
const AUTH_INFO: SafeLogSqlFragment = safeSql`NOT (${AUTH_ERROR}) AND NOT (${AUTH_WARNING})`
// "no severity concept" — every row counts as ok in the chart.
const NO_MATCH: SafeLogSqlFragment = safeSql`0`

// pg_cron logs are postgres_logs rows generated by the pg_cron extension.
const PG_CRON_PREDICATE: SafeLogSqlFragment = safeSql`(${attr('parsed.application_name')} = 'pg_cron' OR event_message ILIKE '%cron job%')`

// Common filter applied to every table (free-text search over event_message).
const COMMON_FILTERS: Record<string, SqlFilterEntry> = {
  search_query: (value: string) => safeSql`event_message ILIKE ${lit('%' + value + '%')}`,
}
const databaseFilter = (value: string): SafeLogSqlFragment =>
  safeSql`${attr('identifier')} = ${lit(value)}`

// Per-table filter templates: ClickHouse equivalents of SQL_FILTER_TEMPLATES
// (Logs.constants.ts). Tables not listed here use COMMON_FILTERS only.
const POSTGRES_FILTERS: Record<string, SqlFilterEntry> = {
  ...COMMON_FILTERS,
  database: databaseFilter,
  'severity.error': PG_ERROR,
  'severity.noError': safeSql`${attr('parsed.error_severity')} NOT IN ('ERROR', 'FATAL', 'PANIC')`,
  'severity.log': safeSql`${attr('parsed.error_severity')} = 'LOG'`,
}
const STATUS_CODE_FILTERS: Record<string, SqlFilterEntry> = {
  'status_code.error': safeSql`${statusAsInt('response.status_code')} BETWEEN 500 AND 599`,
  'status_code.success': safeSql`${statusAsInt('response.status_code')} BETWEEN 200 AND 299`,
  'status_code.warning': safeSql`${statusAsInt('response.status_code')} BETWEEN 400 AND 499`,
}
const EDGE_FILTERS: Record<string, SqlFilterEntry> = {
  ...COMMON_FILTERS,
  database: databaseFilter,
  ...STATUS_CODE_FILTERS,
  'product.database': safeSql`${attr('request.path')} LIKE '/rest/%' OR ${attr('request.path')} LIKE '/graphql/%'`,
  'product.storage': safeSql`${attr('request.path')} LIKE '/storage/%'`,
  'product.auth': safeSql`${attr('request.path')} LIKE '/auth/%'`,
  'product.realtime': safeSql`${attr('request.path')} LIKE '/realtime/%'`,
  'method.get': safeSql`${attr('request.method')} = 'GET'`,
  'method.post': safeSql`${attr('request.method')} = 'POST'`,
  'method.put': safeSql`${attr('request.method')} = 'PUT'`,
  'method.patch': safeSql`${attr('request.method')} = 'PATCH'`,
  'method.delete': safeSql`${attr('request.method')} = 'DELETE'`,
  'method.options': safeSql`${attr('request.method')} = 'OPTIONS'`,
}
const FUNCTION_LOGS_FILTERS: Record<string, SqlFilterEntry> = {
  ...COMMON_FILTERS,
  'severity.error': safeSql`${attr('level')} = 'error'`,
  'severity.notError': safeSql`${attr('level')} != 'error'`,
  'severity.log': safeSql`${attr('level')} = 'log'`,
  'severity.info': safeSql`${attr('level')} = 'info'`,
  'severity.debug': safeSql`${attr('level')} = 'debug'`,
  'severity.warn': safeSql`${attr('level')} = 'warn'`,
}
const AUTH_FILTERS: Record<string, SqlFilterEntry> = {
  ...COMMON_FILTERS,
  'severity.error': AUTH_ERROR,
  'severity.warning': AUTH_WARNING,
  'severity.info': AUTH_INFO,
  'status_code.server_error': safeSql`${statusAsInt('status')} BETWEEN 500 AND 599`,
  'status_code.client_error': safeSql`${statusAsInt('status')} BETWEEN 400 AND 499`,
  'status_code.redirection': safeSql`${statusAsInt('status')} BETWEEN 300 AND 399`,
  'status_code.success': safeSql`${statusAsInt('status')} BETWEEN 200 AND 299`,
  'endpoints.admin': safeSql`match(${attr('path')}, '/admin')`,
  'endpoints.signup': safeSql`match(${attr('path')}, '/signup|/invite|/verify')`,
  'endpoints.authentication': safeSql`match(${attr('path')}, '/token|/authorize|/callback|/otp|/magiclink')`,
  'endpoints.recover': safeSql`match(${attr('path')}, '/recover')`,
  'endpoints.user': safeSql`match(${attr('path')}, '/user')`,
  'endpoints.logout': safeSql`match(${attr('path')}, '/logout')`,
}
const SUPAVISOR_FILTERS: Record<string, SqlFilterEntry> = {
  ...COMMON_FILTERS,
  database: (value: string) => safeSql`${attr('project')} LIKE ${lit(value + '%')}`,
}
const ETL_FILTERS: Record<string, SqlFilterEntry> = {
  ...COMMON_FILTERS,
  pipeline_id: (value: string | number) => safeSql`${attr('pipeline_id')} = ${lit(value)}`,
}

/** Aliased projection column: `log_attributes['<key>'] AS <alias>`. */
const col = (key: string, alias: SafeLogSqlFragment): SafeLogSqlFragment =>
  safeSql`${attr(key)} AS ${alias}`

/**
 * Everything that varies per table when querying the OTEL `logs` table.
 * `columns`/`filterTemplates`/`error`/`warning`/`basePredicate` default to the
 * "nothing extra" case so a plain process-log table is just `{ source }`.
 */
interface OtelSourceDescriptor {
  source: string
  /** Extra projection columns beyond id/timestamp/event_message, aliased to the renderer leaf names. */
  columns?: SafeLogSqlFragment[]
  /** Filter templates for this table; defaults to COMMON_FILTERS. */
  filterTemplates?: Record<string, SqlFilterEntry>
  /** Chart severity predicates; absent => the table has no severity concept. */
  error?: SafeLogSqlFragment
  warning?: SafeLogSqlFragment
  /** Predicate always ANDed with the source filter (e.g. the pg_cron subset). */
  basePredicate?: SafeLogSqlFragment
}

const OTEL_SOURCES: Record<LogsTableName, OtelSourceDescriptor> = {
  [LogsTableName.EDGE]: {
    source: 'edge_logs',
    columns: [
      col('identifier', safeSql`identifier`),
      col('request.method', safeSql`method`),
      col('request.path', safeSql`path`),
      col('request.search', safeSql`search`),
      col('response.status_code', safeSql`status_code`),
    ],
    filterTemplates: EDGE_FILTERS,
    error: HTTP_ERROR,
    warning: HTTP_WARNING,
  },
  [LogsTableName.POSTGRES]: {
    source: 'postgres_logs',
    columns: [
      col('identifier', safeSql`identifier`),
      col('parsed.error_severity', safeSql`error_severity`),
      col('parsed.detail', safeSql`detail`),
      col('parsed.hint', safeSql`hint`),
    ],
    filterTemplates: POSTGRES_FILTERS,
    error: PG_ERROR,
    warning: PG_WARNING,
  },
  [LogsTableName.PG_CRON]: {
    source: 'postgres_logs',
    columns: [
      col('parsed.error_severity', safeSql`error_severity`),
      col('parsed.query', safeSql`query`),
    ],
    error: PG_ERROR,
    warning: PG_WARNING,
    basePredicate: PG_CRON_PREDICATE,
  },
  [LogsTableName.FUNCTIONS]: {
    source: 'function_logs',
    columns: [
      col('event_type', safeSql`event_type`),
      col('function_id', safeSql`function_id`),
      col('execution_id', safeSql`execution_id`),
      col('level', safeSql`level`),
    ],
    filterTemplates: FUNCTION_LOGS_FILTERS,
    error: FN_ERROR,
    warning: FN_WARNING,
  },
  [LogsTableName.FN_EDGE]: {
    source: 'function_edge_logs',
    columns: [
      col('response.status_code', safeSql`status_code`),
      col('request.method', safeSql`method`),
      col('request.pathname', safeSql`pathname`),
      col('function_id', safeSql`function_id`),
      col('execution_id', safeSql`execution_id`),
      col('execution_time_ms', safeSql`execution_time_ms`),
      col('deployment_id', safeSql`deployment_id`),
      col('version', safeSql`version`),
    ],
    filterTemplates: { ...COMMON_FILTERS, ...STATUS_CODE_FILTERS },
    error: HTTP_ERROR,
    warning: HTTP_WARNING,
  },
  [LogsTableName.AUTH]: {
    source: 'auth_logs',
    columns: [
      col('level', safeSql`level`),
      col('status', safeSql`status`),
      col('path', safeSql`path`),
      col('msg', safeSql`msg`),
      col('error', safeSql`error`),
    ],
    filterTemplates: AUTH_FILTERS,
    error: AUTH_ERROR,
    warning: AUTH_WARNING,
  },
  [LogsTableName.MULTIGRES]: {
    source: 'multigres_logs',
    error: MULTIGRES_ERROR,
    warning: MULTIGRES_WARNING,
  },
  [LogsTableName.POSTGREST]: {
    source: 'postgrest_logs',
    filterTemplates: { ...COMMON_FILTERS, database: databaseFilter },
  },
  [LogsTableName.SUPAVISOR]: { source: 'supavisor_logs', filterTemplates: SUPAVISOR_FILTERS },
  [LogsTableName.ETL]: { source: 'etl_replication_logs', filterTemplates: ETL_FILTERS },
  [LogsTableName.AUTH_AUDIT]: { source: 'auth_audit_logs' },
  [LogsTableName.REALTIME]: { source: 'realtime_logs' },
  [LogsTableName.STORAGE]: { source: 'storage_logs' },
  [LogsTableName.PGBOUNCER]: { source: 'pgbouncer_logs' },
  [LogsTableName.PG_UPGRADE]: { source: 'pg_upgrade_logs' },
}

/**
 * Generic equality resolver for filter keys without a template entry — emits an
 * OTEL `log_attributes[key] = value` predicate (the ClickHouse counterpart of
 * the BigQuery `quotedIdent` fallback). Drops the clause on non-scalar input.
 */
const resolveUnknownOtelClause = (dotKey: string, value: unknown): SafeLogSqlFragment | null => {
  if (typeof value !== 'string' && typeof value !== 'number' && typeof value !== 'boolean') {
    return null
  }
  try {
    return safeSql`${attr(dotKey)} = ${lit(value)}`
  } catch {
    // analyticsLiteral rejects non-finite numbers — drop the clause.
    return null
  }
}

// Builds the full WHERE clause: source predicate (+ any base predicate) AND the
// user's filters, reusing the shared nested AND/OR grouping logic.
const genOtelWhere = (table: LogsTableName, filters: Filters): SafeLogSqlFragment => {
  const desc = OTEL_SOURCES[table]
  const predicates: SafeLogSqlFragment[] = [safeSql`source = ${lit(desc.source)}`]
  if (desc.basePredicate) predicates.push(desc.basePredicate)
  predicates.push(
    ...buildWhereClauses(
      table,
      filters,
      desc.filterTemplates ?? COMMON_FILTERS,
      resolveUnknownOtelClause
    )
  )
  return safeSql`WHERE ${joinSqlFragments(predicates, ' AND ')}`
}

const genOtelSelectColumns = (table: LogsTableName): SafeLogSqlFragment => {
  const columns: SafeLogSqlFragment[] = [
    safeSql`id`,
    safeSql`timestamp`,
    safeSql`event_message`,
    ...(OTEL_SOURCES[table].columns ?? []),
  ]
  return joinSqlFragments(columns, ', ')
}

export const genDefaultQueryOtel = (
  table: LogsTableName,
  filters: Filters,
  limit: number = 100
): SafeLogSqlFragment => {
  return safeSql`-- Logs Preview Query (otel) [${lit(table)}]
SELECT ${genOtelSelectColumns(table)}
FROM logs
${genOtelWhere(table, filters)}
ORDER BY timestamp DESC
LIMIT ${lit(limit)}`
}

export const genCountQueryOtel = (table: LogsTableName, filters: Filters): SafeLogSqlFragment => {
  return safeSql`-- Logs Count Query (otel) [${lit(table)}]
SELECT count() AS count FROM logs ${genOtelWhere(table, filters)}`
}

// Chart bucketing matches the BigQuery calcChartStart thresholds: minute for
// ranges up to 12h, otherwise hour (the day branch is unreachable, as in BQ).
const otelChartTruncFn = (params: LogsEndpointParams): SafeLogSqlFragment => {
  const ite = params.iso_timestamp_end ? dayjs(params.iso_timestamp_end) : dayjs()
  const its = params.iso_timestamp_start ? dayjs(params.iso_timestamp_start) : dayjs()
  const minuteDiff = ite.diff(its, 'minute')
  const hourDiff = ite.diff(its, 'hour')
  if (minuteDiff > 60 * 12) return safeSql`toStartOfHour`
  if (hourDiff > 24 * 3) return safeSql`toStartOfDay`
  return safeSql`toStartOfMinute`
}

export const genChartQueryOtel = (
  table: LogsTableName,
  params: LogsEndpointParams,
  filters: Filters
): SafeLogSqlFragment => {
  const truncFn = otelChartTruncFn(params)
  const desc = OTEL_SOURCES[table]
  const err = desc.error ?? NO_MATCH
  const warn = desc.warning ?? NO_MATCH
  // The time range is bounded by the endpoint's iso_timestamp_start/end params,
  // so (unlike the BigQuery chart) no explicit timestamp predicate is needed here.
  return safeSql`-- Logs Chart Query (otel) [${lit(table)}]
SELECT
  ${truncFn}(timestamp) AS timestamp,
  countIf(NOT ((${err}) OR (${warn}))) AS ok_count,
  countIf(${err}) AS error_count,
  countIf(${warn}) AS warning_count
FROM logs
${genOtelWhere(table, filters)}
GROUP BY timestamp
ORDER BY timestamp ASC`
}

// Single log fetch by id. id is uuid-shaped (originates from a URL param), so
// reject anything else before interpolating it into the query.
export const genSingleLogQueryOtel = (id: string): SafeLogSqlFragment => {
  if (!/^[0-9a-fA-F-]{1,64}$/.test(id)) {
    throw new Error('Invalid logId')
  }
  return safeSql`-- Single Log Query (otel)
SELECT id, timestamp, event_message, source, severity_text, log_attributes
FROM logs
WHERE id = ${lit(id)}
LIMIT 1`
}

/**
 * Normalizes an OTEL timestamp to the microsecond number the legacy renderers
 * and pagination cursor expect. Shares the parsing heuristic with the unified
 * logs path via `parseOtelTimestamp`.
 */
export const otelTimestampToMicros = (timestamp: unknown): number =>
  parseOtelTimestamp(timestamp).getTime() * 1000

/** Maps an OTEL preview row to the legacy LogData shape (micro-number timestamp). */
export const mapOtelPreviewRow = (row: Record<string, any>): LogData => {
  return { ...row, timestamp: otelTimestampToMicros(row.timestamp) } as LogData
}

/**
 * Reconstructs the nested BigQuery `metadata` shape the api/database single-log
 * detail panels read, from the flat OTEL `log_attributes`. Tables not listed
 * here use a flat row (the default panel reads fields directly).
 *
 * TODO: the OTEL edge logs also carry the JWT/apikey/`sb` subtree as flattened
 * keys (e.g. `request.sb.jwt.apikey.payload.role`), so the api panel's API key /
 * role rows can be reconstructed here in a follow-up.
 */
const SINGLE_LOG_METADATA: Partial<Record<QueryType, (attrs: Record<string, any>) => unknown>> = {
  api: (attrs) => ({
    request: [
      {
        method: attrs['request.method'] ?? null,
        path: attrs['request.path'] ?? null,
        search: attrs['request.search'] ?? null,
        headers: [{ user_agent: attrs['request.headers.user_agent'] ?? null }],
      },
    ],
    response: [
      {
        status_code: attrs['response.status_code'] ?? null,
        // OTEL exposes the gateway error code as `sb_error_code`; BigQuery used
        // `x_sb_error_code`. Coalesce so the panel resolves it either way.
        headers: [
          {
            x_sb_error_code:
              attrs['response.headers.sb_error_code'] ??
              attrs['response.headers.x_sb_error_code'] ??
              null,
          },
        ],
      },
    ],
  }),
  database: (attrs) => ({
    parsed: [
      {
        hint: attrs['parsed.hint'] ?? null,
        detail: attrs['parsed.detail'] ?? null,
        query: attrs['parsed.query'] ?? null,
      },
    ],
  }),
}

/** Maps a single OTEL log row to the legacy LogData shape the detail panel reads. */
export const mapOtelSingleLogToLegacy = (row: OtelLogRow, queryType?: QueryType): LogData => {
  const attrs: Record<string, any> = row.log_attributes ?? {}
  const base = {
    id: row.id,
    timestamp: otelTimestampToMicros(row.timestamp),
    event_message: row.event_message,
  }

  const buildMetadata = queryType ? SINGLE_LOG_METADATA[queryType] : undefined
  if (buildMetadata) {
    return { ...base, metadata: [buildMetadata(attrs)] } as unknown as LogData
  }
  return { ...base, ...attrs } as LogData
}
