import dayjs from 'dayjs'

import { LogsTableName, type SqlFilterEntry } from './Logs.constants'
import type { Filters, LogData, LogsEndpointParams, QueryType } from './Logs.types'
import { buildWhereClauses } from './Logs.utils'
import type { OtelLogRow } from '@/data/logs/otel-inspection.utils'
import {
  joinSqlFragments,
  analyticsLiteral as lit,
  safeSql,
  type SafeLogSqlFragment,
} from '@/data/logs/safe-analytics-sql'

/**
 * OTEL / ClickHouse query builders for the legacy per-service logs pages.
 *
 * The OTEL endpoint (`logs.all.otel`) stores every log source in a single
 * `logs` table keyed by a `source` column, with the per-log fields the old
 * BigQuery queries unnested from `metadata` exposed flat in the
 * `log_attributes` Map. These builders mirror the BigQuery generators in
 * `Logs.utils.ts` but emit ClickHouse SQL and alias columns to the exact leaf
 * names the existing row renderers read, so the UI needs no changes.
 */

// Maps a logs table to its OTEL `source` value. Identity for almost every
// table; pg_cron is a subset of postgres_logs identified by a predicate.
export const LOG_TABLE_TO_OTEL_SOURCE: Record<LogsTableName, string> = {
  [LogsTableName.EDGE]: 'edge_logs',
  [LogsTableName.POSTGRES]: 'postgres_logs',
  [LogsTableName.FUNCTIONS]: 'function_logs',
  [LogsTableName.FN_EDGE]: 'function_edge_logs',
  [LogsTableName.AUTH]: 'auth_logs',
  [LogsTableName.AUTH_AUDIT]: 'auth_audit_logs',
  [LogsTableName.REALTIME]: 'realtime_logs',
  [LogsTableName.STORAGE]: 'storage_logs',
  [LogsTableName.POSTGREST]: 'postgrest_logs',
  [LogsTableName.SUPAVISOR]: 'supavisor_logs',
  [LogsTableName.PGBOUNCER]: 'pgbouncer_logs',
  [LogsTableName.PG_UPGRADE]: 'pg_upgrade_logs',
  [LogsTableName.PG_CRON]: 'postgres_logs',
  [LogsTableName.ETL]: 'etl_replication_logs',
  [LogsTableName.MULTIGRES]: 'multigres_logs',
}

const attr = (key: string): SafeLogSqlFragment => safeSql`log_attributes[${lit(key)}]`
const statusAsInt = (key: string): SafeLogSqlFragment => safeSql`toInt32OrZero(${attr(key)})`

// pg_cron logs are postgres_logs rows generated by the pg_cron extension.
const PG_CRON_OTEL_CONDITION: SafeLogSqlFragment = safeSql`(${attr('parsed.application_name')} = 'pg_cron' OR event_message ILIKE '%cron job%')`

const _SQL_FILTER_COMMON_OTEL: Record<string, SqlFilterEntry> = {
  search_query: (value: string) => safeSql`event_message ILIKE ${lit('%' + value + '%')}`,
}

/**
 * ClickHouse equivalents of `SQL_FILTER_TEMPLATES` (Logs.constants.ts), keyed by
 * the same table name strings. Predicates reference raw OTEL columns and
 * `log_attributes[...]` lookups instead of BigQuery unnested fields.
 */
export const SQL_FILTER_TEMPLATES_OTEL: Record<string, Record<string, SqlFilterEntry>> = {
  postgres_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
    database: (value: string) => safeSql`${attr('identifier')} = ${lit(value)}`,
    'severity.error': safeSql`${attr('parsed.error_severity')} IN ('ERROR', 'FATAL', 'PANIC')`,
    'severity.noError': safeSql`${attr('parsed.error_severity')} NOT IN ('ERROR', 'FATAL', 'PANIC')`,
    'severity.log': safeSql`${attr('parsed.error_severity')} = 'LOG'`,
  },
  edge_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
    database: (value: string) => safeSql`${attr('identifier')} = ${lit(value)}`,
    'status_code.error': safeSql`${statusAsInt('response.status_code')} BETWEEN 500 AND 599`,
    'status_code.success': safeSql`${statusAsInt('response.status_code')} BETWEEN 200 AND 299`,
    'status_code.warning': safeSql`${statusAsInt('response.status_code')} BETWEEN 400 AND 499`,

    'product.database': safeSql`${attr('request.path')} LIKE '/rest/%' OR ${attr('request.path')} LIKE '/graphql/%'`,
    'product.storage': safeSql`${attr('request.path')} LIKE '/storage/%'`,
    'product.auth': safeSql`${attr('request.path')} LIKE '/auth/%'`,
    'product.realtime': safeSql`${attr('request.path')} LIKE '/realtime/%'`,

    'method.get': safeSql`${attr('request.method')} = 'GET'`,
    'method.post': safeSql`${attr('request.method')} = 'POST'`,
    'method.put': safeSql`${attr('request.method')} = 'PUT'`,
    'method.patch': safeSql`${attr('request.method')} = 'PATCH'`,
    'method.delete': safeSql`${attr('request.method')} = 'DELETE'`,
    'method.options': safeSql`${attr('request.method')} = 'OPTIONS'`,
  },
  function_edge_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
    'status_code.error': safeSql`${statusAsInt('response.status_code')} BETWEEN 500 AND 599`,
    'status_code.success': safeSql`${statusAsInt('response.status_code')} BETWEEN 200 AND 299`,
    'status_code.warning': safeSql`${statusAsInt('response.status_code')} BETWEEN 400 AND 499`,
  },
  function_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
    'severity.error': safeSql`${attr('level')} = 'error'`,
    'severity.notError': safeSql`${attr('level')} != 'error'`,
    'severity.log': safeSql`${attr('level')} = 'log'`,
    'severity.info': safeSql`${attr('level')} = 'info'`,
    'severity.debug': safeSql`${attr('level')} = 'debug'`,
    'severity.warn': safeSql`${attr('level')} = 'warn'`,
  },
  auth_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
    'severity.error': safeSql`${attr('level')} = 'error' OR ${attr('level')} = 'fatal'`,
    'severity.warning': safeSql`${attr('level')} = 'warning'`,
    'severity.info': safeSql`${attr('level')} = 'info'`,
    'status_code.server_error': safeSql`${statusAsInt('status')} BETWEEN 500 AND 599`,
    'status_code.client_error': safeSql`${statusAsInt('status')} BETWEEN 400 AND 499`,
    'status_code.redirection': safeSql`${statusAsInt('status')} BETWEEN 300 AND 399`,
    'status_code.success': safeSql`${statusAsInt('status')} BETWEEN 200 AND 299`,
    'endpoints.admin': safeSql`match(${attr('path')}, '/admin')`,
    'endpoints.signup': safeSql`match(${attr('path')}, '/signup|/invite|/verify')`,
    'endpoints.authentication': safeSql`match(${attr('path')}, '/token|/authorize|/callback|/otp|/magiclink')`,
    'endpoints.recover': safeSql`match(${attr('path')}, '/recover')`,
    'endpoints.user': safeSql`match(${attr('path')}, '/user')`,
    'endpoints.logout': safeSql`match(${attr('path')}, '/logout')`,
  },
  realtime_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
  },
  storage_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
  },
  postgrest_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
    database: (value: string) => safeSql`${attr('identifier')} = ${lit(value)}`,
  },
  pgbouncer_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
  },
  supavisor_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
    database: (value: string) => safeSql`${attr('project')} LIKE ${lit(value + '%')}`,
  },
  pg_upgrade_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
  },
  pg_cron_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
  },
  etl_replication_logs: {
    ..._SQL_FILTER_COMMON_OTEL,
    pipeline_id: (value: string | number) => safeSql`${attr('pipeline_id')} = ${lit(value)}`,
  },
}

/**
 * Generic equality resolver for filter keys without a template entry — emits an
 * OTEL `log_attributes[key] = value` predicate (the ClickHouse counterpart of
 * the BigQuery `quotedIdent` fallback). Drops the clause on non-scalar input.
 */
const resolveUnknownOtelClause = (dotKey: string, value: unknown): SafeLogSqlFragment | null => {
  if (typeof value !== 'string' && typeof value !== 'number' && typeof value !== 'boolean') {
    return null
  }
  try {
    return safeSql`${attr(dotKey)} = ${lit(value)}`
  } catch {
    return null
  }
}

// Builds the full WHERE clause: source predicate (+ cron predicate for pg_cron)
// AND the user's filters, reusing the shared nested AND/OR grouping logic.
const genOtelWhere = (table: LogsTableName, filters: Filters): SafeLogSqlFragment => {
  const predicates: SafeLogSqlFragment[] = [
    safeSql`source = ${lit(LOG_TABLE_TO_OTEL_SOURCE[table])}`,
  ]
  if (table === LogsTableName.PG_CRON) {
    predicates.push(PG_CRON_OTEL_CONDITION)
  }
  const userClauses = buildWhereClauses(
    table,
    filters,
    SQL_FILTER_TEMPLATES_OTEL[table] ?? {},
    resolveUnknownOtelClause
  )
  predicates.push(...userClauses)
  return safeSql`WHERE ${joinSqlFragments(predicates, ' AND ')}`
}

// Per-table projection columns (besides id/timestamp/event_message), aliased to
// the leaf names the legacy row renderers read.
const genOtelExtraColumns = (table: LogsTableName): SafeLogSqlFragment[] => {
  switch (table) {
    case LogsTableName.EDGE:
      return [
        safeSql`${attr('identifier')} AS identifier`,
        safeSql`${attr('request.method')} AS method`,
        safeSql`${attr('request.path')} AS path`,
        safeSql`${attr('request.search')} AS search`,
        safeSql`${attr('response.status_code')} AS status_code`,
      ]
    case LogsTableName.POSTGRES:
      return [
        safeSql`${attr('identifier')} AS identifier`,
        safeSql`${attr('parsed.error_severity')} AS error_severity`,
        safeSql`${attr('parsed.detail')} AS detail`,
        safeSql`${attr('parsed.hint')} AS hint`,
      ]
    case LogsTableName.PG_CRON:
      return [
        safeSql`${attr('parsed.error_severity')} AS error_severity`,
        safeSql`${attr('parsed.query')} AS query`,
      ]
    case LogsTableName.FUNCTIONS:
      return [
        safeSql`${attr('event_type')} AS event_type`,
        safeSql`${attr('function_id')} AS function_id`,
        safeSql`${attr('execution_id')} AS execution_id`,
        safeSql`${attr('level')} AS level`,
      ]
    case LogsTableName.FN_EDGE:
      return [
        safeSql`${attr('response.status_code')} AS status_code`,
        safeSql`${attr('request.method')} AS method`,
        safeSql`${attr('request.pathname')} AS pathname`,
        safeSql`${attr('function_id')} AS function_id`,
        safeSql`${attr('execution_id')} AS execution_id`,
        safeSql`${attr('execution_time_ms')} AS execution_time_ms`,
        safeSql`${attr('deployment_id')} AS deployment_id`,
        safeSql`${attr('version')} AS version`,
      ]
    case LogsTableName.AUTH:
      return [
        safeSql`${attr('level')} AS level`,
        safeSql`${attr('status')} AS status`,
        safeSql`${attr('path')} AS path`,
        safeSql`${attr('msg')} AS msg`,
        safeSql`${attr('error')} AS error`,
      ]
    default:
      return []
  }
}

const genOtelSelectColumns = (table: LogsTableName): SafeLogSqlFragment => {
  const columns: SafeLogSqlFragment[] = [
    safeSql`id`,
    safeSql`timestamp`,
    safeSql`event_message`,
    ...genOtelExtraColumns(table),
  ]
  return joinSqlFragments(columns, ', ')
}

export const genDefaultQueryOtel = (
  table: LogsTableName,
  filters: Filters,
  limit: number = 100
): SafeLogSqlFragment => {
  const where = genOtelWhere(table, filters)
  return safeSql`SELECT ${genOtelSelectColumns(table)}
FROM logs
${where}
ORDER BY timestamp DESC
LIMIT ${lit(limit)}`
}

export const genCountQueryOtel = (table: LogsTableName, filters: Filters): SafeLogSqlFragment => {
  const where = genOtelWhere(table, filters)
  return safeSql`SELECT count() AS count FROM logs ${where}`
}

// Severity classification per source, mirroring the BigQuery
// getErrorCondition / getWarningCondition logic but over OTEL columns.
const otelErrorCondition = (table: LogsTableName): SafeLogSqlFragment => {
  switch (table) {
    case LogsTableName.EDGE:
    case LogsTableName.FN_EDGE:
      return safeSql`${statusAsInt('response.status_code')} >= 500`
    case LogsTableName.POSTGRES:
    case LogsTableName.PG_CRON:
      return safeSql`${attr('parsed.error_severity')} IN ('ERROR', 'FATAL', 'PANIC')`
    case LogsTableName.AUTH:
      return safeSql`${attr('level')} = 'error' OR ${statusAsInt('status')} >= 400`
    case LogsTableName.FUNCTIONS:
      return safeSql`${attr('level')} IN ('error', 'fatal')`
    case LogsTableName.MULTIGRES:
      return safeSql`JSONExtractString(event_message, 'level') IN ('ERROR', 'FATAL', 'PANIC')`
    default:
      return safeSql`0`
  }
}

const otelWarningCondition = (table: LogsTableName): SafeLogSqlFragment => {
  switch (table) {
    case LogsTableName.EDGE:
    case LogsTableName.FN_EDGE:
      return safeSql`${statusAsInt('response.status_code')} BETWEEN 400 AND 499`
    case LogsTableName.POSTGRES:
    case LogsTableName.PG_CRON:
      return safeSql`${attr('parsed.error_severity')} = 'WARNING'`
    case LogsTableName.AUTH:
      return safeSql`${attr('level')} = 'warning'`
    case LogsTableName.FUNCTIONS:
      return safeSql`${attr('level')} = 'warning'`
    case LogsTableName.MULTIGRES:
      return safeSql`JSONExtractString(event_message, 'level') IN ('WARN', 'WARNING')`
    default:
      return safeSql`0`
  }
}

// Chart bucketing matches the BigQuery calcChartStart thresholds: minute for
// ranges up to 12h, otherwise hour (the day branch is unreachable, as in BQ).
const otelChartTruncFn = (params: LogsEndpointParams): SafeLogSqlFragment => {
  const ite = params.iso_timestamp_end ? dayjs(params.iso_timestamp_end) : dayjs()
  const its = params.iso_timestamp_start ? dayjs(params.iso_timestamp_start) : dayjs()
  const minuteDiff = ite.diff(its, 'minute')
  const hourDiff = ite.diff(its, 'hour')
  if (minuteDiff > 60 * 12) return safeSql`toStartOfHour`
  if (hourDiff > 24 * 3) return safeSql`toStartOfDay`
  return safeSql`toStartOfMinute`
}

export const genChartQueryOtel = (
  table: LogsTableName,
  params: LogsEndpointParams,
  filters: Filters
): SafeLogSqlFragment => {
  const truncFn = otelChartTruncFn(params)
  const where = genOtelWhere(table, filters)
  const err = otelErrorCondition(table)
  const warn = otelWarningCondition(table)
  return safeSql`SELECT
  ${truncFn}(timestamp) AS timestamp,
  countIf(NOT ((${err}) OR (${warn}))) AS ok_count,
  countIf(${err}) AS error_count,
  countIf(${warn}) AS warning_count
FROM logs
${where}
GROUP BY timestamp
ORDER BY timestamp ASC`
}

// Single log fetch by id. id is uuid-shaped (originates from a URL param), so
// reject anything else before interpolating it into the query.
export const genSingleLogQueryOtel = (id: string): SafeLogSqlFragment => {
  if (!/^[0-9a-fA-F-]{1,64}$/.test(id)) {
    throw new Error('Invalid logId')
  }
  return safeSql`SELECT id, timestamp, event_message, source, severity_text, log_attributes
FROM logs
WHERE id = ${lit(id)}
LIMIT 1`
}

/**
 * Normalizes an OTEL timestamp (ISO string or numeric microseconds-since-epoch)
 * to the microsecond number the legacy renderers and pagination cursor expect.
 */
export const otelTimestampToMicros = (timestamp: unknown): number => {
  const ts = String(timestamp ?? '')
  const looksLikeIso = /[T-]/.test(ts)
  let date: Date
  if (looksLikeIso) {
    // ClickHouse may serialize as `YYYY-MM-DD HH:mm:ss[.ffffff]`; convert the
    // space to `T` and assume UTC when no timezone is present.
    const withT = ts.includes(' ') ? ts.replace(' ', 'T') : ts
    const hasTz = /Z$|[+-]\d{2}:?\d{2}$/.test(withT)
    date = new Date(hasTz ? withT : `${withT}Z`)
  } else {
    date = new Date(Number(ts) / 1000)
  }
  return date.getTime() * 1000
}

/** Maps an OTEL preview row to the legacy LogData shape (micro-number timestamp). */
export const mapOtelPreviewRow = (row: Record<string, any>): LogData => {
  return { ...row, timestamp: otelTimestampToMicros(row.timestamp) } as LogData
}

/**
 * Maps a single OTEL log row to the legacy LogData shape. The `api` and
 * `database` detail panels read a nested `metadata` structure, so reconstruct
 * the minimal shape they consume from `log_attributes`; all other panels read a
 * flat row, so spread the attributes directly.
 */
export const mapOtelSingleLogToLegacy = (row: OtelLogRow, queryType?: QueryType): LogData => {
  const attrs: Record<string, any> = row.log_attributes ?? {}
  const base = {
    id: row.id,
    timestamp: otelTimestampToMicros(row.timestamp),
    event_message: row.event_message,
  }

  if (queryType === 'api') {
    return {
      ...base,
      metadata: [
        {
          request: [
            {
              method: attrs['request.method'] ?? null,
              path: attrs['request.path'] ?? null,
              search: attrs['request.search'] ?? null,
              headers: [{ user_agent: attrs['request.headers.user_agent'] ?? null }],
            },
          ],
          response: [
            {
              status_code: attrs['response.status_code'] ?? null,
              headers: [{ x_sb_error_code: attrs['response.headers.x_sb_error_code'] ?? null }],
            },
          ],
        },
      ],
    } as unknown as LogData
  }

  if (queryType === 'database') {
    return {
      ...base,
      metadata: [
        {
          parsed: [
            {
              hint: attrs['parsed.hint'] ?? null,
              detail: attrs['parsed.detail'] ?? null,
              query: attrs['parsed.query'] ?? null,
            },
          ],
        },
      ],
    } as unknown as LogData
  }

  return { ...base, ...attrs } as LogData
}
