// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    {
      type: 'category',
      label: 'Supabase Dart',
      link: { type: 'doc', id: 'intro' },
      items: ['installing', 'initializing'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Auth',
      items: [
        'auth-signup',
        'auth-signin',
        'auth-signinwithprovider',
        'auth-signout',
        'auth-session',
        'auth-user',
        'auth-update',
        'auth-onauthstatechange',
        'reset-password-email',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Functions',
      items: ['invoke'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Database',
      items: ['select', 'insert', 'update', 'upsert', 'delete', 'rpc'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Realtime',
      items: ['subscribe', 'removesubscription', 'getsubscriptions', 'stream'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Storage',
      items: [
        'storage-createbucket',
        'storage-getbucket',
        'storage-listbuckets',
        'storage-updatebucket',
        'storage-deletebucket',
        'storage-emptybucket',
        'storage-from-upload',
        'storage-from-download',
        'storage-from-list',
        'storage-from-update',
        'storage-from-move',
        'storage-from-remove',
        'storage-from-createsignedurl',
        'storage-from-getpublicurl',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Modifiers',
      items: ['using-modifiers', 'limit', 'order', 'range', 'single'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Filters',
      items: [
        'using-filters',
        'or',
        'not',
        'match',
        'eq',
        'neq',
        'gt',
        'gte',
        'lt',
        'lte',
        'like',
        'ilike',
        'is_',
        'in_',
        'contains',
        'containedby',
        'rangelt',
        'rangegt',
        'rangegte',
        'rangelte',
        'rangeadjacent',
        'overlaps',
        'textsearch',
        'filter',
      ],
      collapsed: true,
    },
    'release-notes',
  ],
}

module.exports = sidebars
