// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Chrome } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconChrome(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Chrome} {...props} />
}

export default IconChrome
