// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Send } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconSend(props: any) {
    return <IconBase icon={Send} {...props} />
  }

  export default IconSend
  