// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconSend(props: IconProps) {
  return <Icon type="Send" {...props} />
}

export default IconSend
