// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconCornerDownRight(props: IconProps) {
  return <Icon type="CornerDownRight" {...props} />
}

export default IconCornerDownRight
