// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { CornerDownRight } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconCornerDownRight(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={CornerDownRight} {...props} />
}

export default IconCornerDownRight
