// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { ArrowDownCircle } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconArrowDownCircle(props: any) {
    return <IconBase icon={ArrowDownCircle} {...props} />
  }

  export default IconArrowDownCircle
  