// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { ArrowDownCircle } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconArrowDownCircle(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={ArrowDownCircle} {...props} />
}

export default IconArrowDownCircle
