# Add 'documentation' to any change in apps/docs
# https://github.com/marketplace/actions/labeler
documentation:
  - changed-files:
      - any-glob-to-any-file: 'apps/docs/**/*'

# Add 'api-deploy-required' to any change in packages/api-types/types
api-deploy-required:
  - changed-files:
      - any-glob-to-any-file: 'packages/api-types/types/**'
