const template = `
---
id: usage
title: Usage
---

<!-- AUTOGENERATED: DO NOT EDIT DIRECTLY IF THIS IS VERSION "next" -->

<%- info.description %>


<!-- AUTOGENERATED: DO NOT EDIT DIRECTLY IF THIS IS VERSION "next" -->


<% functions.forEach(function(fn){ %>

## <%- fn.summary %>

<%- fn.usage %>

### Attributes

<% fn.attributes.forEach(function(attribute){ %>
- <%- attribute.id %>
<% }); %>


### Notes

<%- fn.description %>

### Examples

<% fn.examples.forEach(function(example){ %>

#### <%- example.title %>

<%- example.code %>

<% }); %>

<% }); %>


`.trim()

export default template
