// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconHash(props: IconProps) {
  return <Icon type="Hash" {...props} />
}

export default IconHash
