import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { ThemeProvider } from 'common/Providers'
import { themes } from 'ui'
import { Provider as JotaiProvider } from 'jotai'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // const themeKeys = themes.map((theme) => theme.value)

  return (
    <html className="dark" lang="en" data-theme="dark" style={{ colorScheme: 'dark' }}>
      <JotaiProvider>
        {/* <ThemeProvider
        themes={['dark', 'light']}
        defaultTheme="system"
        enableSystem
        // forcedTheme={forceDarkMode ? 'dark' : undefined}
      > */}
        <body className={inter.className}>{children}</body>
        {/* </ThemeProvider> */}
      </JotaiProvider>
    </html>
  )
}
