// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconAtSign(props: IconProps) {
  return <Icon type="AtSign" {...props} />
}

export default IconAtSign
