packages:
  - 'apps/*'
  - 'packages/*'
  - 'tests/*'

catalog:
  '@types/node': ^20.0.0
  '@supabase/auth-js': 2.69.0-rc.3
  '@supabase/supabase-js': ^2.47.14
  '@supabase/realtime-js': ^2.11.3
  next: 14.2.26
  'react': '^18.3.0'
  'react-dom': '^18.3.0'
  '@types/react': '^18.3.0'
  '@types/react-dom': '^18.3.0'
  'valtio': '^1.12.0'
