packages:
  - apps/*
  - packages/*
  - blocks/*
  - e2e/*

catalog:
  '@sentry/nextjs': ^10.26.0
  '@supabase/auth-js': 2.103.0
  '@supabase/postgrest-js': 2.103.0
  '@supabase/realtime-js': 2.103.0
  '@supabase/supabase-js': 2.103.0
  '@types/node': ^22.0.0
  '@types/react': ^18.3.0
  '@types/react-dom': ^18.3.0
  lodash: ^4.18.1
  lodash-es: ^4.18.1
  next: ~16.1.7
  react: ^18.3.0
  react-dom: ^18.3.0
  recharts: ^2.15.4
  tailwindcss: 3.4.1
  tsx: 4.20.3
  typescript: ~6.0.0
  valtio: ^1.12.0
  vite: ^7.3.2
  vitest: ^3.2.0
  zod: 3.25.76

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - contentlayer2
  - core-js
  - es5-ext
  - esbuild
  - libpg-query
  - msw
  - protobufjs
  - sharp

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@ai-sdk/*'
  - '@supabase/*'
  - '@supabase-labs/*'
  # The following deps were added due to vulnerabilities. You can remove them after the minimum time has passed.
  - defu
  - vite
  - '@hono/node-server'
  - hono
  - lodash
  - lodash-es

onlyBuiltDependencies:
  - node-pty
  - supabase

overrides:
  '@ardatan/relay-compiler>immutable': ^3.8.3
  '@aws-sdk/core>fast-xml-parser': ^4.5.5
  '@mapbox/node-pre-gyp>tar': ^7.5.11
  '@redocly/respect-core>form-data': ^4.0.4
  '@redocly/respect-core>js-yaml': ^4.1.1
  '@rollup/plugin-terser>serialize-javascript': ^7.0.5
  '@tanstack/start-server-core': ^1.159.0
  cacache>tar: ^7.5.11
  dompurify: ^3.3.2
  esbuild: ^0.25.2
  lodash: 'catalog:'
  lodash-es: 'catalog:'
  node-gyp>tar: ^7.5.11
  nodemailer: ^7.0.11
  payload>undici: ^7.18.2
  'pgsql-parser>libpg-query': ^15.2.0
  refractor>prismjs: ^1.30.0
  supabase>tar: ^7.5.11
  'terser-webpack-plugin>serialize-javascript': ^7.0.5
  tmp: ^0.2.4
  webpack: ^5.104.1

patchedDependencies:
  react-data-grid: patches/react-data-grid.patch
