package api

// Provider constants
const (
	AnonymousProvider         = "anonymous"
	AppleProvider             = "apple"
	AzureProvider             = "azure"
	BitbucketProvider         = "bitbucket"
	DiscordProvider           = "discord"
	EmailProvider             = "email"
	FacebookProvider          = "facebook"
	FigmaProvider             = "figma"
	FlyProvider               = "fly"
	GitHubProvider            = "github"
	GitLabProvider            = "gitlab"
	GoogleProvider            = "google"
	KakaoProvider             = "kakao"
	KeycloakProvider          = "keycloak"
	LinkedInProvider          = "linkedin"
	LinkedInOIDCProvider      = "linkedin_oidc"
	NotionProvider            = "notion"
	PhoneProvider             = "phone"
	SAMLProvider              = "saml"
	SlackProvider             = "slack"
	SlackOIDCProvider         = "slack_oidc"
	SnapchatProvider          = "snapchat"
	SpotifyProvider           = "spotify"
	TwitchProvider            = "twitch"
	TwitterProvider           = "twitter"
	VercelMarketplaceProvider = "vercel_marketplace"
	Web3Provider              = "web3"
	WorkOSProvider            = "workos"
	XProvider                 = "x"
	ZoomProvider              = "zoom"
)
