// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { XOctagon } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconXOctagon(props: any) {
    return <IconBase icon={XOctagon} {...props} />
  }

  export default IconXOctagon
  