// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { UserPlus } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconUserPlus(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={UserPlus} {...props} />
}

export default IconUserPlus
