// public/markdown/manifest.json is generated by internals/generate-guides-markdown.ts
// and gitignored, so it may not exist on disk when tsc runs.
declare module '~/public/markdown/manifest.json' {
  const slugs: string[]
  export default slugs
}

// public/markdown/reference-manifest.json is generated by internals/generate-reference-sections.ts
declare module '~/public/markdown/reference-manifest.json' {
  const manifest: Record<string, string>
  // eslint-disable-next-line no-restricted-exports -- a JSON module only has a default export
  export default manifest
}
