import React from 'react'

export const Index: Record<string, any> = {
  default: {
    'accordion-demo': {
      name: 'accordion-demo',
      type: 'components:example',
      registryDependencies: ['accordion'],
      component: React.lazy(() => import('@/registry/default/example/accordion-demo')),
      source: '',
      files: ['registry/default/example/accordion-demo.tsx'],
      category: 'undefined',
      subcategory: 'undefined',
      backendProviders: [],
      chunks: [],
    },
    'dropdown-menu-demo': {
      name: 'dropdown-menu-demo',
      type: 'components:example',
      registryDependencies: ['dropdown-menu'],
      component: React.lazy(() => import('@/registry/default/example/dropdown-menu-demo')),
      source: '',
      files: ['registry/default/example/dropdown-menu-demo.tsx'],
      category: 'undefined',
      subcategory: 'undefined',
      backendProviders: [],
      chunks: [],
    },
    'dropdown-menu-checkboxes': {
      name: 'dropdown-menu-checkboxes',
      type: 'components:example',
      registryDependencies: ['dropdown-menu', 'checkbox'],
      component: React.lazy(() => import('@/registry/default/example/dropdown-menu-checkboxes')),
      source: '',
      files: ['registry/default/example/dropdown-menu-checkboxes.tsx'],
      category: 'undefined',
      subcategory: 'undefined',
      backendProviders: [],
      chunks: [],
    },
    'dropdown-menu-radio-group': {
      name: 'dropdown-menu-radio-group',
      type: 'components:example',
      registryDependencies: ['dropdown-menu', 'radio-group'],
      component: React.lazy(() => import('@/registry/default/example/dropdown-menu-radio-group')),
      source: '',
      files: ['registry/default/example/dropdown-menu-radio-group.tsx'],
      category: 'undefined',
      subcategory: 'undefined',
      backendProviders: [],
      chunks: [],
    },
  },
}
