import { Registry } from './schema'

// Base shadcn/ui primitives. Unlike `examples`/`fragments`/`charts`, these don't
// live under `registry/default/*` — their source is the real, shared components
// consumed via `import { X } from 'ui'`, at `packages/ui/src/components/shadcn/ui`.
// `getRegistryFiles` in `lib/rehype-component.ts` resolves `components:ui` files
// against that package path instead of the usual `registry/${style}/` prefix.
export const ui: Registry = [
  { name: 'accordion', type: 'components:ui', files: ['accordion.tsx'] },
  { name: 'alert', type: 'components:ui', files: ['alert.tsx'] },
  { name: 'alert-dialog', type: 'components:ui', files: ['alert-dialog.tsx'] },
  { name: 'aspect-ratio', type: 'components:ui', files: ['aspect-ratio.tsx'] },
  { name: 'avatar', type: 'components:ui', files: ['avatar.tsx'] },
  { name: 'badge', type: 'components:ui', files: ['badge.tsx'] },
  { name: 'breadcrumb', type: 'components:ui', files: ['breadcrumb.tsx'] },
  { name: 'button', type: 'components:ui', files: ['button.tsx'] },
  { name: 'button-group', type: 'components:ui', files: ['button-group.tsx'] },
  { name: 'calendar', type: 'components:ui', files: ['calendar.tsx'] },
  { name: 'card', type: 'components:ui', files: ['card.tsx'] },
  { name: 'chart', type: 'components:ui', files: ['chart.tsx'] },
  { name: 'checkbox', type: 'components:ui', files: ['checkbox.tsx'] },
  { name: 'collapsible', type: 'components:ui', files: ['collapsible.tsx'] },
  { name: 'command', type: 'components:ui', files: ['command.tsx'] },
  { name: 'context-menu', type: 'components:ui', files: ['context-menu.tsx'] },
  { name: 'dialog', type: 'components:ui', files: ['dialog.tsx'] },
  { name: 'drawer', type: 'components:ui', files: ['drawer.tsx'] },
  { name: 'dropdown-menu', type: 'components:ui', files: ['dropdown-menu.tsx'] },
  { name: 'field', type: 'components:ui', files: ['field.tsx'] },
  { name: 'form', type: 'components:ui', files: ['form.tsx'] },
  { name: 'hover-card', type: 'components:ui', files: ['hover-card.tsx'] },
  { name: 'input', type: 'components:ui', files: ['input.tsx'] },
  { name: 'input-group', type: 'components:ui', files: ['input-group.tsx'] },
  { name: 'input-otp', type: 'components:ui', files: ['input-otp.tsx'] },
  { name: 'label', type: 'components:ui', files: ['label.tsx'] },
  { name: 'menubar', type: 'components:ui', files: ['menubar.tsx'] },
  { name: 'navigation-menu', type: 'components:ui', files: ['navigation-menu.tsx'] },
  { name: 'popover', type: 'components:ui', files: ['popover.tsx'] },
  { name: 'progress', type: 'components:ui', files: ['progress.tsx'] },
  { name: 'radio-group', type: 'components:ui', files: ['radio-group.tsx'] },
  { name: 'resizable', type: 'components:ui', files: ['resizable.tsx'] },
  { name: 'scroll-area', type: 'components:ui', files: ['scroll-area.tsx'] },
  { name: 'select', type: 'components:ui', files: ['select.tsx'] },
  { name: 'separator', type: 'components:ui', files: ['separator.tsx'] },
  { name: 'sheet', type: 'components:ui', files: ['sheet.tsx'] },
  { name: 'sidebar', type: 'components:ui', files: ['sidebar.tsx'] },
  { name: 'skeleton', type: 'components:ui', files: ['skeleton.tsx'] },
  { name: 'slider', type: 'components:ui', files: ['slider.tsx'] },
  { name: 'sonner', type: 'components:ui', files: ['sonner.tsx'] },
  { name: 'sonner-progress', type: 'components:ui', files: ['sonner-progress.tsx'] },
  { name: 'switch', type: 'components:ui', files: ['switch.tsx'] },
  { name: 'table', type: 'components:ui', files: ['table.tsx'] },
  { name: 'tabs', type: 'components:ui', files: ['tabs.tsx'] },
  { name: 'text-area', type: 'components:ui', files: ['text-area.tsx'] },
  { name: 'textarea', type: 'components:ui', files: ['textarea.tsx'] },
  { name: 'toggle', type: 'components:ui', files: ['toggle.tsx'] },
  { name: 'toggle-group', type: 'components:ui', files: ['toggle-group.tsx'] },
  { name: 'tooltip', type: 'components:ui', files: ['tooltip.tsx'] },
]
