import { buildWhereClause, SurveyChart } from '../SurveyChart'

function generateAICodebasePercentSQL(activeFilters: Record<string, string>) {
  const whereClause = buildWhereClause(activeFilters, ['ai_generated_codebase_percent IS NOT NULL'])

  return `SELECT
  ai_generated_codebase_percent AS band,
  COUNT(*) AS total
FROM responses_2026
${whereClause}
GROUP BY ai_generated_codebase_percent
ORDER BY CASE
    WHEN ai_generated_codebase_percent = '0%' THEN 1
    WHEN ai_generated_codebase_percent = '1-25%' THEN 2
    WHEN ai_generated_codebase_percent = '26-50%' THEN 3
    WHEN ai_generated_codebase_percent = '51-75%' THEN 4
    WHEN ai_generated_codebase_percent = '76-100%' THEN 5
    ELSE 6
  END;`
}

export function AICodebasePercentChart() {
  return (
    <SurveyChart
      title="What percentage of your codebase was generated by AI?"
      targetColumn="ai_generated_codebase_percent"
      filterColumns={['person_age', 'team_size', 'money_raised']}
      functionName="get_ai_generated_codebase_percent_stats"
      newInYear={2026}
      generateSQLQuery={generateAICodebasePercentSQL}
    />
  )
}
