// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconMap(props: IconProps) {
  return <Icon type="Map" {...props} />
}

export default IconMap
