// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconArrowUpRight(props: IconProps) {
  return <Icon type="ArrowUpRight" {...props} />
}

export default IconArrowUpRight
