import type { NextPage } from 'next'
import { Auth } from '@supabase/auth-ui-react'
import { ThemeSupa } from '@supabase/auth-ui-shared'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import Account from '../components/Account'
import Footer from '../components/Footer'
import Head from 'next/head'

const Home: NextPage = () => {
  const session = useSession()
  const supabase = useSupabaseClient()

  return (
    <>
      <Head>
        <title>User Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container" style={{ padding: '50px 0 100px 0' }}>
        {!session ? (
          <div className="row">
            <div className="col-6">
              <h1 className="header">Supabase Auth + Storage</h1>
              <p className="">
                Experience our Auth and Storage through a simple profile management example. Create
                a user profile and upload an avatar image. Fast, simple, secure.
              </p>
            </div>
            <div className="col-6 auth-widget">
              <Auth
                supabaseClient={supabase}
                view="magic_link"
                redirectTo="http://localhost:3000/api/auth/callback"
                appearance={{ theme: ThemeSupa }}
                theme="dark"
                showLinks={false}
                providers={[]}
              />
            </div>
          </div>
        ) : (
          <>
            <h3>Account</h3>
            <Account session={session} />
          </>
        )}

        <Footer />
      </div>
    </>
  )
}

export default Home
