// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { PauseCircle } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconPauseCircle(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={PauseCircle} {...props} />
}

export default IconPauseCircle
