// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Anchor } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconAnchor(props: any) {
    return <IconBase icon={Anchor} {...props} />
  }

  export default IconAnchor
  