// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { RotateCcw } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconRotateCcw(props: any) {
    return <IconBase icon={RotateCcw} {...props} />
  }

  export default IconRotateCcw
  