// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconAlignLeft(props: IconProps) {
  return <Icon type="AlignLeft" {...props} />
}

export default IconAlignLeft
