// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Twitch } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconTwitch(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Twitch} {...props} />
}

export default IconTwitch
