// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconDivideCircle(props: IconProps) {
  return <Icon type="DivideCircle" {...props} />
}

export default IconDivideCircle
