import React from 'react'
import Ticket from '../Ticket/Ticket'

interface User {
  username: string | null
  name: string | null
  ticketNumber: number | null
  golden: boolean
  referrals: number
}

interface Props {
  users: User[]
}

export default function TicketBrickWall({ users }: Props) {
  console.log(users)
  return (
    <div className="">
      <div className="max-w-[38rem] mx-auto">
        <h2 className="radial-gradient-text-scale-500 text-center">
          Explore the unique tickets generated by our community
        </h2>
        <div>
          {users.map((user) => (
            <></>
            // <Ticket
            //   username={user.username}
            //   name={user.name}
            //   ticketNumber={user.ticketNumber}
            //   golden={user.golden}
            //   referrals={user.referrals ?? 0}
            // />
          ))}
        </div>
      </div>
    </div>
  )
}
