import React from 'react'

interface User {
  username: string | null
  name: string | null
  ticketNumber: number | null
  golden: boolean
  referrals: number
}

interface Props {
  users: User[]
}

export default function TicketBrickWall({ users }: Props) {
  console.log(users)
  return (
    <div className="">
      <div className="max-w-[38rem] mx-auto">
        <h2 className="radial-gradient-text-scale-500 text-center">
          Explore the unique tickets generated by our community
        </h2>
      </div>
    </div>
  )
}
