import React, { useState } from 'react'
import { UserData } from '../Ticket/hooks/use-conf-data'

import { createClient } from '@supabase/supabase-js'

import TicketHeader from '../Ticket/TicketHeader'
import TicketNumber from '../Ticket/TicketNumber'

type user = UserData
interface Props {
  users: user[]
}

export default function TicketBrickWall({ users }: Props) {
  const [supabase] = useState(() =>
    createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!)
  )

  return (
    <div className="mx-auto overflow-hidden">
      <div className="max-w-[38rem] mx-auto ">
        <h2 className="radial-gradient-text-scale-500 text-center">
          Explore the unique tickets generated by our community
        </h2>
      </div>
      <div className="flex gap-4 flex-wrap justify-center -ml-48">
        {users.map((user, i) => (
          <div
            className={`relative w-[450px] h-[230px] border border-red-100 rounded-2xl ${
              i === 3 ? 'ml-48' : ''
            }`}
          >
            <TicketHeader size="small" />
            <div className="rounded-full grid gap-4 mx-auto justify-center mt-8">
              <img
                src={`https://github.com/${user.username}.png`}
                alt={user.username}
                className="w-20 h-20 rounded-full"
              />
              <div className="text-center">
                <h3 className="gradient-text-scale-500 text-xl">
                  {user.name ? user.name : user.username}
                </h3>
                {user.name && <p className="gradient-text-scale-500 text-sm">@{user.username}</p>}
              </div>
            </div>
            <TicketNumber number={user.ticketNumber} size="small" />
          </div>
        ))}
      </div>
    </div>
  )
}
