// TODO: Change lib tests to server tests.
// https://github.com/supabase/postgres-meta/issues/397#issuecomment-1285078489
import './lib/columns'
import './lib/config'
import './lib/extensions'
import './lib/foreign-tables'
import './lib/functions'
import './lib/policies'
import './lib/publications'
import './lib/roles'
import './lib/schemas'
import './lib/secrets'
import './lib/tables'
import './lib/triggers'
import './lib/types'
import './lib/version'
import './lib/views'
import './server/column-privileges'
import './server/format-pool'
import './server/indexes'
import './server/materialized-views'
import './server/query'
import './server/ssl'
import './server/table-privileges'
import './server/typegen'
import './server/result-size-limit'
import './server/query-timeout'
// New tests for increased coverage - commented out to avoid import issues
// import './server/app'
// import './server/utils'
// import './server/functions'
// import './server/config'
// import './server/extensions'
// import './server/publications'
// import './server/schemas'
// import './server/roles'
// import './server/triggers'
// import './server/types'
// import './server/views'
