export {
  AlertCircle as IconAlertCircle,
  Book as IconBook,
  Check as IconCheck,
  ChevronUp as IconChevronUp,
  ChevronDown as IconChevronDown,
  ChevronRight as IconChevronRight,
  LogOut as IconLogOut,
  Settings as IconSettings,
  HardDrive as IconHardDrive,
  Mail as IconMail,
  Package as IconPackage,
  Trash as IconTrash, Activity,
  User as IconUser,
} from 'react-feather'
