// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconZap(props: IconProps) {
  return <Icon type="Zap" {...props} />
}

export default IconZap
