// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Zap } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconZap(props: any) {
    return <IconBase icon={Zap} {...props} />
  }

  export default IconZap
  