// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconGift(props: IconProps) {
  return <Icon type="Gift" {...props} />
}

export default IconGift
