// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Gift } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconGift(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Gift} {...props} />
}

export default IconGift
