name: Check pull requests

on:
  push:
    branches-ignore: # Run the checks on all branches but the protected ones
      - master
      - release/*

  pull_request:
    branches:
      - master
      - release/*
    types:
      - opened
      - edited
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  check-conventional-commits:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    if: github.actor != 'dependabot[bot]' # skip for dependabot PRs
    env:
      EVENT: ${{ toJSON(github.event) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .github

      - if: ${{ github.event_name == 'pull_request' }}
        run: |
          set -ex

          TMP_FILE=$(mktemp)
          echo "${EVENT}" > "$TMP_FILE"
          node .github/workflows/conventional-commits-lint.js pr "${TMP_FILE}"

      - if: ${{ github.event_name == 'push' }}
        run: |
          set -ex

          TMP_FILE=$(mktemp)
          echo "${EVENT}" > "$TMP_FILE"
          node .github/workflows/conventional-commits-lint.js push "${TMP_FILE}"
