// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { XCircle } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconXCircle(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={XCircle} {...props} />
}

export default IconXCircle
