// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { XCircle } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconXCircle(props: any) {
    return <IconBase icon={XCircle} {...props} />
  }

  export default IconXCircle
  