export interface Permission {
  id: string
  label: string
  description: string
  group: 'organization' | 'project'
}

export const PERMISSIONS: Permission[] = [
  // Organization permissions
  {
    id: 'organizations_read',
    label: 'organizations_read',
    description: 'View organization details',
    group: 'organization',
  },
  {
    id: 'organizations_create',
    label: 'organizations_create',
    description: 'Create organizations',
    group: 'organization',
  },
  {
    id: 'organization_admin_read',
    label: 'organization_admin_read',
    description: 'View organization admin settings',
    group: 'organization',
  },
  {
    id: 'organization_admin_write',
    label: 'organization_admin_write',
    description: 'Manage organization admin settings',
    group: 'organization',
  },
  {
    id: 'members_read',
    label: 'members_read',
    description: 'View organization members',
    group: 'organization',
  },
  {
    id: 'members_write',
    label: 'members_write',
    description: 'Manage organization members',
    group: 'organization',
  },
  {
    id: 'organization_projects_read',
    label: 'organization_projects_read',
    description: 'View organization projects',
    group: 'organization',
  },
  {
    id: 'organization_projects_create',
    label: 'organization_projects_create',
    description: 'Create projects in organization',
    group: 'organization',
  },
  {
    id: 'snippets_read',
    label: 'snippets_read',
    description: 'View SQL snippets',
    group: 'organization',
  },
  {
    id: 'analytics_usage_read',
    label: 'analytics_usage_read',
    description: 'View usage analytics',
    group: 'organization',
  },
  // Project permissions
  {
    id: 'projects_read',
    label: 'projects_read',
    description: 'View project details',
    group: 'project',
  },
  {
    id: 'project_admin_read',
    label: 'project_admin_read',
    description: 'View project admin settings',
    group: 'project',
  },
  {
    id: 'project_admin_write',
    label: 'project_admin_write',
    description: 'Manage project admin settings',
    group: 'project',
  },
  {
    id: 'action_runs_read',
    label: 'action_runs_read',
    description: 'View action runs',
    group: 'project',
  },
  {
    id: 'action_runs_write',
    label: 'action_runs_write',
    description: 'Manage action runs',
    group: 'project',
  },
  {
    id: 'advisors_read',
    label: 'advisors_read',
    description: 'View advisor recommendations',
    group: 'project',
  },
  {
    id: 'analytics_logs_read',
    label: 'analytics_logs_read',
    description: 'View analytics logs',
    group: 'project',
  },
  {
    id: 'api_gateway_keys_read',
    label: 'api_gateway_keys_read',
    description: 'View API gateway keys',
    group: 'project',
  },
  {
    id: 'api_gateway_keys_write',
    label: 'api_gateway_keys_write',
    description: 'Manage API gateway keys',
    group: 'project',
  },
  {
    id: 'auth_config_read',
    label: 'auth_config_read',
    description: 'View auth configuration',
    group: 'project',
  },
  {
    id: 'auth_config_write',
    label: 'auth_config_write',
    description: 'Manage auth settings',
    group: 'project',
  },
  {
    id: 'auth_signing_keys_read',
    label: 'auth_signing_keys_read',
    description: 'View auth signing keys',
    group: 'project',
  },
  {
    id: 'auth_signing_keys_write',
    label: 'auth_signing_keys_write',
    description: 'Manage auth signing keys',
    group: 'project',
  },
  { id: 'backups_read', label: 'backups_read', description: 'View backups', group: 'project' },
  { id: 'backups_write', label: 'backups_write', description: 'Manage backups', group: 'project' },
  {
    id: 'branching_development_read',
    label: 'branching_development_read',
    description: 'View development branches',
    group: 'project',
  },
  {
    id: 'branching_development_create',
    label: 'branching_development_create',
    description: 'Create development branches',
    group: 'project',
  },
  {
    id: 'branching_development_write',
    label: 'branching_development_write',
    description: 'Manage development branches',
    group: 'project',
  },
  {
    id: 'branching_development_delete',
    label: 'branching_development_delete',
    description: 'Delete development branches',
    group: 'project',
  },
  {
    id: 'branching_production_read',
    label: 'branching_production_read',
    description: 'View production branches',
    group: 'project',
  },
  {
    id: 'branching_production_create',
    label: 'branching_production_create',
    description: 'Create production branches',
    group: 'project',
  },
  {
    id: 'branching_production_write',
    label: 'branching_production_write',
    description: 'Manage production branches',
    group: 'project',
  },
  {
    id: 'branching_production_delete',
    label: 'branching_production_delete',
    description: 'Delete production branches',
    group: 'project',
  },
  {
    id: 'custom_domain_read',
    label: 'custom_domain_read',
    description: 'View custom domain settings',
    group: 'project',
  },
  {
    id: 'custom_domain_write',
    label: 'custom_domain_write',
    description: 'Manage custom domain',
    group: 'project',
  },
  {
    id: 'data_api_config_read',
    label: 'data_api_config_read',
    description: 'View Data API configuration',
    group: 'project',
  },
  {
    id: 'data_api_config_write',
    label: 'data_api_config_write',
    description: 'Manage Data API settings',
    group: 'project',
  },
  {
    id: 'database_read',
    label: 'database_read',
    description: 'Read database data',
    group: 'project',
  },
  {
    id: 'database_write',
    label: 'database_write',
    description: 'Write database data',
    group: 'project',
  },
  {
    id: 'database_config_read',
    label: 'database_config_read',
    description: 'View database configuration',
    group: 'project',
  },
  {
    id: 'database_config_write',
    label: 'database_config_write',
    description: 'Manage database settings',
    group: 'project',
  },
  {
    id: 'database_migrations_read',
    label: 'database_migrations_read',
    description: 'View database migrations',
    group: 'project',
  },
  {
    id: 'database_migrations_write',
    label: 'database_migrations_write',
    description: 'Run database migrations',
    group: 'project',
  },
  {
    id: 'database_pooling_config_read',
    label: 'database_pooling_config_read',
    description: 'View connection pooling settings',
    group: 'project',
  },
  {
    id: 'database_pooling_config_write',
    label: 'database_pooling_config_write',
    description: 'Manage connection pooling',
    group: 'project',
  },
  {
    id: 'database_ssl_config_read',
    label: 'database_ssl_config_read',
    description: 'View SSL configuration',
    group: 'project',
  },
  {
    id: 'database_ssl_config_write',
    label: 'database_ssl_config_write',
    description: 'Manage SSL settings',
    group: 'project',
  },
  {
    id: 'database_webhooks_config_read',
    label: 'database_webhooks_config_read',
    description: 'View database webhooks',
    group: 'project',
  },
  {
    id: 'database_webhooks_config_write',
    label: 'database_webhooks_config_write',
    description: 'Manage database webhooks',
    group: 'project',
  },
  {
    id: 'edge_functions_read',
    label: 'edge_functions_read',
    description: 'View Edge Functions',
    group: 'project',
  },
  {
    id: 'edge_functions_write',
    label: 'edge_functions_write',
    description: 'Deploy and manage Edge Functions',
    group: 'project',
  },
  {
    id: 'edge_functions_secrets_read',
    label: 'edge_functions_secrets_read',
    description: 'View Edge Function secrets',
    group: 'project',
  },
  {
    id: 'edge_functions_secrets_write',
    label: 'edge_functions_secrets_write',
    description: 'Manage Edge Function secrets',
    group: 'project',
  },
  {
    id: 'infra_add_ons_read',
    label: 'infra_add_ons_read',
    description: 'View infrastructure add-ons',
    group: 'project',
  },
  {
    id: 'infra_add_ons_write',
    label: 'infra_add_ons_write',
    description: 'Manage infrastructure add-ons',
    group: 'project',
  },
  {
    id: 'infra_disk_config_read',
    label: 'infra_disk_config_read',
    description: 'View disk configuration',
    group: 'project',
  },
  {
    id: 'infra_disk_config_write',
    label: 'infra_disk_config_write',
    description: 'Manage disk settings',
    group: 'project',
  },
  {
    id: 'infra_read_replicas_read',
    label: 'infra_read_replicas_read',
    description: 'View read replicas',
    group: 'project',
  },
  {
    id: 'infra_read_replicas_write',
    label: 'infra_read_replicas_write',
    description: 'Manage read replicas',
    group: 'project',
  },
  {
    id: 'project_snippets_read',
    label: 'project_snippets_read',
    description: 'View project SQL snippets',
    group: 'project',
  },
  {
    id: 'project_snippets_write',
    label: 'project_snippets_write',
    description: 'Manage project SQL snippets',
    group: 'project',
  },
  {
    id: 'storage_read',
    label: 'storage_read',
    description: 'Read storage objects',
    group: 'project',
  },
  {
    id: 'storage_write',
    label: 'storage_write',
    description: 'Write storage objects',
    group: 'project',
  },
  {
    id: 'storage_config_read',
    label: 'storage_config_read',
    description: 'View storage configuration',
    group: 'project',
  },
  {
    id: 'storage_config_write',
    label: 'storage_config_write',
    description: 'Manage storage settings',
    group: 'project',
  },
  {
    id: 'vanity_subdomain_read',
    label: 'vanity_subdomain_read',
    description: 'View vanity subdomain settings',
    group: 'project',
  },
  {
    id: 'vanity_subdomain_write',
    label: 'vanity_subdomain_write',
    description: 'Manage vanity subdomain',
    group: 'project',
  },
]
