// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconPhoneForwarded(props: IconProps) {
  return <Icon type="PhoneForwarded" {...props} />
}

export default IconPhoneForwarded
