// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconMessageSquare(props: IconProps) {
  return <Icon type="MessageSquare" {...props} />
}

export default IconMessageSquare
