export const ProviderCollapsibleClasses = [
  'bg-scale-100 dark:bg-scale-300 ',
  'hover:bg-scale-200 dark:hover:bg-scale-500',
  'data-open:bg-scale-200 dark:data-open:bg-scale-500 ',
  'border-scale-300 ',
  'dark:border-scale-500 hover:border-scale-500 ',
  'dark:hover:border-scale-700 data-open:border-scale-700',
  'data-open:pb-px col-span-12 mx-auto',
  '-space-y-px overflow-hidden',
  'border shadow',
  'transition',
  'first:rounded-tl',
  'first:rounded-tr',
  'last:rounded-bl',
  'last:rounded-br',
  'hover:z-50',
]
