-- Create a table of users
create table "public"."quotes" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"first_name" text null,
	"last_name" text null,
	"inserted_at" timestamp without time zone not null default(now() at time zone 'utc'),
	"updated_at" timestamp without time zone not null default (now() at time zone 'utc')
);