create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  event_name text not null,
  properties jsonb not null default '{}',
  created_at timestamptz default now()
);

create index if not exists analytics_events_event_name_idx
on public.analytics_events (event_name);
