// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Bold } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconBold(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Bold} {...props} />
}

export default IconBold
