// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconMinus(props: IconProps) {
  return <Icon type="Minus" {...props} />
}

export default IconMinus
