// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Tv } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconTv(props: any) {
    return <IconBase icon={Tv} {...props} />
  }

  export default IconTv
  