// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Voicemail } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconVoicemail(props: any) {
    return <IconBase icon={Voicemail} {...props} />
  }

  export default IconVoicemail
  