module.exports = {
  "UI-H1-Bold": "var(--ui-typography-h1-bold, [object Object]);",
  "UI-H1-Regular": "var(--ui-typography-h1-regular, [object Object]);",
  "UI-H2-Bold": "var(--ui-typography-h2-bold, [object Object]);",
  "UI-H2-Regular": "var(--ui-typography-h2-regular, [object Object]);",
  "UI-H3-Bold": "var(--ui-typography-h3-bold, [object Object]);",
  "UI-H3-Regular": "var(--ui-typography-h3-regular, [object Object]);",
  "UI-H4-Bold": "var(--ui-typography-h4-bold, [object Object]);",
  "UI-H4-Regular": "var(--ui-typography-h4-regular, [object Object]);",
  "UI-H4-mono": "var(--ui-typography-h4-mono, [object Object]);",
  "UI-H5-Bold": "var(--ui-typography-h5-bold, [object Object]);",
  "UI-H5-Regular": "var(--ui-typography-h5-regular, [object Object]);",
  "UI-body-base-normal": "var(--ui-typography-body-base-normal, [object Object]);",
  "UI-body-lg-normal": "var(--ui-typography-body-lg-normal, [object Object]);",
  "UI-body-lg-mono": "var(--ui-typography-body-lg-mono, [object Object]);",
  "UI-body-xs-normal": "var(--ui-typography-body-xs-normal, [object Object]);",
  "UI-body-xs-code-header": "var(--ui-typography-body-xs-code-header, [object Object]);",
  "UI-body-sm-normal": "var(--ui-typography-body-sm-normal, [object Object]);",
  "UI-body-sm-code-header": "var(--ui-typography-body-sm-code-header, [object Object]);",
  "UI-body-sm-code-normal": "var(--ui-typography-body-sm-code-normal, [object Object]);",
  "UI-body-sm-bullet-points": "var(--ui-typography-body-sm-bullet-points, [object Object]);",
  "UI-button-xs": "var(--ui-typography-button-xs, [object Object]);",
  "UI-button-sm": "var(--ui-typography-button-sm, [object Object]);",
  "UI-form-label": "var(--ui-typography-form-label, [object Object]);",
  "UI-form-label-secondary": "var(--ui-typography-form-label-secondary, [object Object]);",
  "UI-table-header": "var(--ui-typography-table-header, [object Object]);"
}