export const SHORTCUT_REFERENCE_GROUPS = {
  GLOBAL_ACTIONS: 'global.actions',
  NAVIGATION_GLOBAL: 'navigation.global',
  NAVIGATION_DATABASE: 'navigation.database',
  NAVIGATION_AUTH: 'navigation.auth',
  NAVIGATION_STORAGE: 'navigation.storage',
  NAVIGATION_FUNCTIONS: 'navigation.functions',
  NAVIGATION_FUNCTION_DETAIL: 'navigation.function-detail',
  NAVIGATION_REALTIME: 'navigation.realtime',
  NAVIGATION_OBSERVABILITY: 'navigation.observability',
  NAVIGATION_ADVISORS: 'navigation.advisors',
  NAVIGATION_INTEGRATIONS_DETAIL: 'navigation.integrations-detail',
} as const

export const SHORTCUT_REFERENCE_GROUP_LABELS: Record<string, string> = {
  [SHORTCUT_REFERENCE_GROUPS.GLOBAL_ACTIONS]: 'Global Actions',
  [SHORTCUT_REFERENCE_GROUPS.NAVIGATION_GLOBAL]: 'Global Navigation',
  [SHORTCUT_REFERENCE_GROUPS.NAVIGATION_DATABASE]: 'Database Navigation',
  [SHORTCUT_REFERENCE_GROUPS.NAVIGATION_AUTH]: 'Auth Navigation',
  [SHORTCUT_REFERENCE_GROUPS.NAVIGATION_STORAGE]: 'Storage Navigation',
  [SHORTCUT_REFERENCE_GROUPS.NAVIGATION_FUNCTIONS]: 'Edge Functions Navigation',
  [SHORTCUT_REFERENCE_GROUPS.NAVIGATION_FUNCTION_DETAIL]: 'Edge Function Tabs',
  [SHORTCUT_REFERENCE_GROUPS.NAVIGATION_REALTIME]: 'Realtime Navigation',
  [SHORTCUT_REFERENCE_GROUPS.NAVIGATION_OBSERVABILITY]: 'Observability Navigation',
  [SHORTCUT_REFERENCE_GROUPS.NAVIGATION_ADVISORS]: 'Advisors Navigation',
  [SHORTCUT_REFERENCE_GROUPS.NAVIGATION_INTEGRATIONS_DETAIL]: 'Integration Tabs',
}

export const SHORTCUT_REFERENCE_GROUP_ORDER = [
  'command-menu',
  'shortcuts',
  SHORTCUT_REFERENCE_GROUPS.GLOBAL_ACTIONS,
  SHORTCUT_REFERENCE_GROUPS.NAVIGATION_GLOBAL,
  SHORTCUT_REFERENCE_GROUPS.NAVIGATION_DATABASE,
  SHORTCUT_REFERENCE_GROUPS.NAVIGATION_AUTH,
  'auth-users',
  SHORTCUT_REFERENCE_GROUPS.NAVIGATION_STORAGE,
  'storage-buckets',
  'storage-explorer',
  SHORTCUT_REFERENCE_GROUPS.NAVIGATION_FUNCTIONS,
  'functions-list',
  SHORTCUT_REFERENCE_GROUPS.NAVIGATION_FUNCTION_DETAIL,
  'functions-detail',
  'functions-overview',
  SHORTCUT_REFERENCE_GROUPS.NAVIGATION_REALTIME,
  'realtime-inspector',
  SHORTCUT_REFERENCE_GROUPS.NAVIGATION_OBSERVABILITY,
  'observability-page',
  SHORTCUT_REFERENCE_GROUPS.NAVIGATION_ADVISORS,
  'advisors-page',
  SHORTCUT_REFERENCE_GROUPS.NAVIGATION_INTEGRATIONS_DETAIL,
  'logs-preview',
  'nav',
  'ai-assistant',
  'inline-editor',
  'sql-editor',
  'results',
  'data-table',
  'table-editor',
  'schema-visualizer',
  'list-page',
  'platform-webhooks',
  'action-bar',
  'operation-queue',
  'unified-logs',
]
