// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconMaximize2(props: IconProps) {
  return <Icon type="Maximize2" {...props} />
}

export default IconMaximize2
