// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { PhoneOutgoing } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconPhoneOutgoing(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={PhoneOutgoing} {...props} />
}

export default IconPhoneOutgoing
