// Design guidance and optional CSS vocabulary for generated pages.
// Keep the task and its information hierarchy ahead of any suggested composition.
export const GENERATED_PAGE_DESIGN_PROMPT = `
### Studio UI defaults and customization
- Default to Studio's visual language when the user has not specified a design. The UI kit and composition ideas below are optional starting points, never requirements on the user's design. Choose the page's hierarchy and layout for the task before choosing classes.
- A specific change overrides that aspect of the defaults. A request for a completely different aesthetic or interface authorizes a complete departure, including layout, typography, colors, density, and component styling. Do not make the user request each override separately or steer them back to Studio styling.
- For a custom design, override any kit class with ordinary inline CSS, use your own classes, or omit the kit entirely. The kit lives in a low-priority CSS cascade layer, so your normal CSS overrides it, including hover/focus rules, without !important. Existing base typography and body spacing can also be overridden by your later CSS. Preserve an existing page's requested design when revising it.
- Custom appearance does not change the sandbox, available APIs, query approval requirements, or accessibility requirements. Do not load external stylesheets, scripts, fonts, or images.

### Available UI kit
These are browser CSS classes, not React components. They are already injected. Reuse them where they fit; add CSS freely to improve the composition, hierarchy, or interaction while keeping the default Studio palette and typography. Do not sacrifice the design to fit the kit. Use native HTML elements and add JavaScript for behavior; classes do not implement sorting, filtering, pagination, retries, or data loading.
- Layout: \`studio-page\` supplies a centered content column and section spacing; add \`studio-page--full\` for wide data views or \`studio-page--narrow\` for focused controls. \`studio-section\` groups a heading with content. \`studio-section-header\` aligns a heading left and related actions right. \`studio-grid\` lays out related panels and stacks them when narrow.
- Toolbars: \`studio-toolbar\` with \`studio-actions\` groups on the left and right. Put search/filters left and actions right. Controls wrap at narrow widths. Explorer supplies a tab title and reload/stop controls. Do not recreate application navigation or runtime controls. A dashboard or investigation can still have a useful page heading and a short description; a self-explanatory table or console can start at the toolbar.
- Buttons: \`studio-button\` is a neutral 34px button aligned with the default fields. Add \`studio-button--primary\` for a clear main action, \`studio-button--text\` for a quiet action, or \`studio-button--compact\` for a 26px action in a deliberately dense editor toolbar. Do not make every page compact by default. Always use type="button" unless intentionally submitting a form. Native disabled and focus-visible states are styled. While an action runs, disable it and show a specific loading label.
- Fields: wrap a labeled native input/select/textarea in \`studio-field\`; use \`studio-input\` or \`studio-select\`. Fields default to 34px, including toolbars; coarse pointers get larger targets. Use \`studio-description\` for help text, connect it with aria-describedby, and set aria-invalid for invalid input. Keep short selectors content-sized. Search Escape should clear a nonempty search first, then blur when already empty.
- Tables: \`studio-table-container\` contains horizontal overflow around a semantic \`studio-table\`. Use thead/tbody, th scope="col", and \`studio-number\` on numeric headers and cells. Headers stay on one line. Use \`studio-nowrap\` for short identifiers, service names, and status columns; format timestamps as readable dates/times in a time element. Use \`studio-text\` only on prose/message cells that should wrap. Never apply overflow-wrap:anywhere or word-break:break-all to the entire table. Show concise message summaries with expandable raw details instead of making full URLs and unformatted JSON dominate the table. Keep technical identifiers monospace with \`font-mono\`. Wire any sort/filter/page controls to the bounded result set; never imply a local filter searched the entire database.
- Surfaces: \`studio-card\` is an optional subtle bordered group; put padded content in \`studio-card-content\` and footer actions in \`studio-card-footer\`. Use headings, spacing, and dividers when a card is unnecessary. Do not nest cards or wrap each metric/filter in one. \`studio-badge\` is a neutral status/category label, not a button or decoration.
- Metrics: use a \`studio-metrics\` definition list, with each dt/dd pair wrapped in a div. Values have tabular numerals and stay smaller inside cards; add \`studio-metrics--summary\` only for the few leading figures that deserve emphasis. Do not render every value at the same large size or repeat the same metrics in a summary strip and service cards. Include units and the relevant time range. Use \`studio-muted\` for secondary text. Charts use the injected color tokens, quiet axes and grids, readable labels, and consistent units; the kit does not include a chart library.
- States: \`studio-state\` groups a loading, empty, or error message with an optional action. Use role="status" for loading, and \`studio-state studio-state--error\` with role="alert" for failures. Keep these inside the affected section; preserve table headers and filters for zero results. Use hidden to switch states, show the actual error message, and wire a retry button. Never present example values as live query results.
- Typography/copy: semantic h1–h6 and the classes \`heading-title\`, \`heading-section\`, \`heading-subSection\`, \`heading-default\`, \`heading-compact\`, \`text-default\`, \`text-subTitle\`, and \`text-compact\` are available. Keep capitalization exact. Keep the hierarchy visible: h1/heading-title for an optional page title, h2/heading-section for major sections, and heading-default for compact panel titles and labels. Do not style every heading as a small label. Prefer normal or medium weight and sentence case. Font antialiasing is already applied to match Studio. Avoid oversized hero headings, uppercase eyebrow labels, slogans, decorative icon tiles, and redundant descriptions by default.

### Composition ideas
These describe useful relationships between content, not templates to reproduce. Include only what answers the user's task. Do not add a table, metric strip, summary, evidence section, or technical-details panel simply because it appears below.
- **Browse records:** place filters and relevant actions beside each other above the primary table/list. Keep the result count and any local pagination nearby. Use the available width when columns need it; preserve readable row spacing and useful search-field width. Keep filters and headers in place for zero results.
- **Monitor activity:** group each service or topic's label, metrics, time range, and chart together. A small number of coherent panels can work better than a detached metric strip above unrelated charts. Give the dominant chart or finding enough space; add recent events only when they help the user investigate it.
- **Investigate a record or issue:** lead with the selected record or concrete question, then order relevant facts and evidence by importance. Use inline facts for metadata, a list or table for repeated evidence, and disclosure for long technical details. Avoid generic "Summary" and "Evidence" headings when the actual content can provide more useful names.
- Across layouts, align sections to shared edges, keep related content close, and leave more space between major groups. Use normal Studio heading sizes and restrained surfaces. A small page should feel complete and intentional, without empty panels or filler. All query-dependent content needs loading, empty, and error states. Custom user designs may use entirely different compositions.

### Project health pages
For a request such as "track project health for my project", start with a readable dashboard at the default page width, not a stretched full-width report. Use a modest page heading with the time range or freshness nearby and a neutral Refresh button. Show one concise health status with the specific reason it needs attention; remove transient "loaded successfully" messages after loading. Group related service metrics in compact panels with a clear service heading, modest label/value pairs, and a divider or spacing between the header and measurements. Use color sparingly to identify actual warning/error states with text. Include a trend only when the declared data supports it, and keep recent issues scannable with readable times, friendly service labels, and short message summaries. Keep the original details available in a disclosure. Do not label all log entries as errors or sum unrelated service counters into a single unexplained "error signals" metric. Adapt this composition to the project's available data and the user's requested design.

### Final design check
For the default Studio design, check the overall hierarchy and proportions as well as the components. Remove filler, unjustified cards, redundant chrome, and decorative badges, but retain useful page context and section headings. Adjust the kit with CSS whenever that improves the page. For a user-requested custom design, check against that request instead and preserve intentional departures. In both cases, check narrow layouts, text zoom, keyboard operation, contrast, and loading/empty/error states.
`
