import { expect } from '@playwright/test'

import { createTable, dropTable, query } from '../utils/db/index.js'
import {
  addFilter,
  getFilterBarInput,
  navigateToTable,
  selectColumnFilter,
  selectOperator,
  setupFilterBarPage,
} from '../utils/filter-bar-helpers.js'
import { test } from '../utils/test.js'
import { toUrl } from '../utils/to-url.js'

const tableNamePrefix = 'pw_filter_bar'

test.describe('Filter Bar', () => {
  test.beforeEach(async ({ page, ref }) => {
    await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
  })

  test.describe('Basic Filter Operations', () => {
    test('selecting a column creates a filter condition', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_col_sel`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await selectColumnFilter(page, columnName)

        await expect(page.getByTestId(`filter-condition-${columnName}`)).toBeVisible()
        await expect(page.getByTestId(`filter-operator-${columnName}`)).toBeFocused()
      } finally {
        await dropTable(tableName)
      }
    })

    test('selecting operator from dropdown focuses value input', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_op_sel`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await selectColumnFilter(page, columnName)
        await page.keyboard.press('Enter')

        await expect(page.getByTestId(`filter-value-${columnName}`)).toBeFocused()
      } finally {
        await dropTable(tableName)
      }
    })

    test('entering value filters the grid', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_val_filt`
      const columnName = 'name'

      await createTable(tableName, columnName, [
        { name: 'Alice' },
        { name: 'Bob' },
        { name: 'Charlie' },
      ])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')

        await expect(page.getByRole('gridcell', { name: 'Alice' })).toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Bob' })).not.toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Charlie' })).not.toBeVisible()
      } finally {
        await dropTable(tableName)
      }
    })

    test('removing filter via X button restores all data', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_remove_x`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }, { name: 'Bob' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')
        await expect(page.getByRole('gridcell', { name: 'Bob' })).not.toBeVisible()

        await page.getByTestId(`filter-remove-${columnName}`).click()

        await expect(page.getByTestId(`filter-condition-${columnName}`)).not.toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Alice' })).toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Bob' })).toBeVisible()
      } finally {
        await dropTable(tableName)
      }
    })

    test('multiple filters can be added', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_multi`

      await query(
        `CREATE TABLE IF NOT EXISTS ${tableName} (
          id bigint generated by default as identity primary key,
          first_name text,
          last_name text
        )`
      )
      await query(
        `INSERT INTO ${tableName} (first_name, last_name) VALUES ('Alice', 'Smith'), ('Bob', 'Smith'), ('Alice', 'Jones')`
      )

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, 'first_name', '=', 'Alice')
        await addFilter(page, ref, 'last_name', '=', 'Smith')

        await expect(page.getByTestId('filter-condition-first_name')).toBeVisible()
        await expect(page.getByTestId('filter-condition-last_name')).toBeVisible()
      } finally {
        await dropTable(tableName)
      }
    })
  })

  test.describe('Keyboard Navigation - Freeform Input', () => {
    test('Enter selects column from dropdown', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_enter_col`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        const freeformInput = getFilterBarInput(page)
        await freeformInput.click()
        await freeformInput.fill(columnName)
        await expect(page.getByTestId(`filter-menu-item-${columnName}`)).toBeVisible()

        await page.keyboard.press('Enter')

        await expect(page.getByTestId(`filter-condition-${columnName}`)).toBeVisible()
      } finally {
        await dropTable(tableName)
      }
    })

    test('Tab selects column from dropdown', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_tab_col`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        const freeformInput = getFilterBarInput(page)
        await freeformInput.click()
        await freeformInput.fill(columnName)
        await expect(page.getByTestId(`filter-menu-item-${columnName}`)).toBeVisible()

        await page.keyboard.press('Tab')

        await expect(page.getByTestId(`filter-condition-${columnName}`)).toBeVisible()
      } finally {
        await dropTable(tableName)
      }
    })

    test('ArrowDown/ArrowUp navigates dropdown items', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_arrow_nav`

      await query(
        `CREATE TABLE IF NOT EXISTS ${tableName} (
          id bigint generated by default as identity primary key,
          alpha text,
          beta text,
          gamma text
        )`
      )
      await query(`INSERT INTO ${tableName} (alpha, beta, gamma) VALUES ('a', 'b', 'g')`)

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        const freeformInput = getFilterBarInput(page)
        await freeformInput.click()

        // Items: id (0), alpha (1), beta (2), gamma (3)
        await page.keyboard.press('ArrowDown')
        await page.keyboard.press('ArrowDown')
        await page.keyboard.press('Enter')

        await expect(page.getByTestId('filter-condition-beta')).toBeVisible()
      } finally {
        await dropTable(tableName)
      }
    })

    test('Backspace on empty input highlights last filter', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_bksp_hl`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')

        const freeformInput = getFilterBarInput(page)
        await freeformInput.click()
        await page.keyboard.press('Backspace')

        await expect(page.getByTestId(`filter-condition-${columnName}`)).toHaveAttribute(
          'data-highlighted',
          'true'
        )
      } finally {
        await dropTable(tableName)
      }
    })

    test('Backspace again deletes highlighted filter', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_bksp_del`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')

        const freeformInput = getFilterBarInput(page)
        await freeformInput.click()
        await page.keyboard.press('Backspace')
        await expect(page.getByTestId(`filter-condition-${columnName}`)).toHaveAttribute(
          'data-highlighted',
          'true'
        )

        await page.keyboard.press('Backspace')

        await expect(page.getByTestId(`filter-condition-${columnName}`)).not.toBeVisible()
      } finally {
        await dropTable(tableName)
      }
    })

    test('ArrowLeft highlights previous condition', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_arrowl_hl`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')

        const freeformInput = getFilterBarInput(page)
        await freeformInput.click()
        await page.keyboard.press('ArrowLeft')

        await expect(page.getByTestId(`filter-condition-${columnName}`)).toHaveAttribute(
          'data-highlighted',
          'true'
        )
      } finally {
        await dropTable(tableName)
      }
    })

    test('ArrowRight clears highlight at end', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_arrowr_cl`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')

        const freeformInput = getFilterBarInput(page)
        await freeformInput.click()
        await page.keyboard.press('ArrowLeft')
        await expect(page.getByTestId(`filter-condition-${columnName}`)).toHaveAttribute(
          'data-highlighted',
          'true'
        )

        await page.keyboard.press('ArrowRight')
        await expect(page.getByTestId(`filter-condition-${columnName}`)).not.toHaveAttribute(
          'data-highlighted',
          'true'
        )
      } finally {
        await dropTable(tableName)
      }
    })

    test('Escape clears highlight', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_esc_cl`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')

        const freeformInput = getFilterBarInput(page)
        await freeformInput.click()
        await page.keyboard.press('ArrowLeft')
        await expect(page.getByTestId(`filter-condition-${columnName}`)).toHaveAttribute(
          'data-highlighted',
          'true'
        )

        await page.keyboard.press('Escape')
        await expect(page.getByTestId(`filter-condition-${columnName}`)).not.toHaveAttribute(
          'data-highlighted',
          'true'
        )
      } finally {
        await dropTable(tableName)
      }
    })

    test('Enter on highlighted condition focuses value input', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_enter_hl`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')

        const freeformInput = getFilterBarInput(page)
        await freeformInput.click()
        await page.keyboard.press('Backspace')
        await expect(page.getByTestId(`filter-condition-${columnName}`)).toHaveAttribute(
          'data-highlighted',
          'true'
        )

        await page.keyboard.press('Enter')
        await expect(page.getByTestId(`filter-value-${columnName}`)).toBeFocused()
      } finally {
        await dropTable(tableName)
      }
    })
  })

  test.describe('Keyboard Navigation - Operator Input', () => {
    test('Enter selects operator and focuses value', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_op_enter`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await selectColumnFilter(page, columnName)
        await page.keyboard.press('Enter')

        await expect(page.getByTestId(`filter-value-${columnName}`)).toBeFocused()
      } finally {
        await dropTable(tableName)
      }
    })

    test('Backspace on empty operator removes condition', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_op_bksp`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await selectColumnFilter(page, columnName)

        const operatorInput = page.getByTestId(`filter-operator-${columnName}`)
        await operatorInput.fill('')
        await page.keyboard.press('Backspace')

        await expect(page.getByTestId(`filter-condition-${columnName}`)).not.toBeVisible()
      } finally {
        await dropTable(tableName)
      }
    })
  })

  test.describe('Keyboard Navigation - Value Input', () => {
    test('Enter on value moves focus to group freeform', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_val_enter`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')

        await expect(getFilterBarInput(page)).toBeFocused()
      } finally {
        await dropTable(tableName)
      }
    })

    test('Backspace on empty value moves to operator', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_val_bksp`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await selectColumnFilter(page, columnName)
        await selectOperator(page, columnName, '=')

        await page.keyboard.press('Backspace')

        await expect(page.getByTestId(`filter-operator-${columnName}`)).toBeFocused()
      } finally {
        await dropTable(tableName)
      }
    })

    test('ArrowLeft at position 0 moves to previous condition value', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_val_arrowl`

      await query(
        `CREATE TABLE IF NOT EXISTS ${tableName} (
          id bigint generated by default as identity primary key,
          first_name text,
          last_name text
        )`
      )
      await query(
        `INSERT INTO ${tableName} (first_name, last_name) VALUES ('Alice', 'Smith'), ('Bob', 'Jones')`
      )

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, 'first_name', '=', 'Alice')
        await addFilter(page, ref, 'last_name', '=', 'Smith')

        const lastNameValue = page.getByTestId('filter-value-last_name')
        await lastNameValue.click()
        await page.keyboard.press('Home')

        await page.keyboard.press('ArrowLeft')

        await expect(page.getByTestId('filter-value-first_name')).toBeFocused()
      } finally {
        await dropTable(tableName)
      }
    })

    test('ArrowRight at end moves to next condition or freeform', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_val_arrowr`
      const columnName = 'name'

      await createTable(tableName, columnName, [{ name: 'Alice' }])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')

        // Use keyboard to focus value: highlight condition then Enter to avoid re-opening dropdown
        const freeformInput = getFilterBarInput(page)
        await freeformInput.click()
        await page.keyboard.press('Backspace')
        await page.keyboard.press('Enter')

        await expect(page.getByTestId(`filter-value-${columnName}`)).toBeFocused()
        await page.keyboard.press('End')
        await page.keyboard.press('ArrowRight')

        await expect(freeformInput).toBeFocused()
      } finally {
        await dropTable(tableName)
      }
    })
  })

  test.describe('Filter Results Verification', () => {
    test('filter data verification with row count', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_data_ver`
      const columnName = 'name'

      await createTable(tableName, columnName, [
        { name: 'Alice' },
        { name: 'Bob' },
        { name: 'Charlie' },
      ])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await expect(page.getByRole('gridcell', { name: 'Alice' })).toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Bob' })).toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Charlie' })).toBeVisible()

        await addFilter(page, ref, columnName, '=', 'Alice')

        await expect(page.getByRole('gridcell', { name: 'Alice' })).toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Bob' })).not.toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Charlie' })).not.toBeVisible()
      } finally {
        await dropTable(tableName)
      }
    })

    test('removing filter restores all data', async ({ page, ref }) => {
      const tableName = `${tableNamePrefix}_restore`
      const columnName = 'name'

      await createTable(tableName, columnName, [
        { name: 'Alice' },
        { name: 'Bob' },
        { name: 'Charlie' },
      ])

      try {
        await setupFilterBarPage(page, ref, toUrl(`/project/${ref}/editor?schema=public`))
        await navigateToTable(page, ref, tableName)

        await addFilter(page, ref, columnName, '=', 'Alice')

        await expect(page.getByRole('gridcell', { name: 'Bob' })).not.toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Charlie' })).not.toBeVisible()

        await page.getByTestId(`filter-remove-${columnName}`).click()

        await expect(page.getByRole('gridcell', { name: 'Alice' })).toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Bob' })).toBeVisible()
        await expect(page.getByRole('gridcell', { name: 'Charlie' })).toBeVisible()
      } finally {
        await dropTable(tableName)
      }
    })
  })
})
