// List of available Tax IDs as reflected in Stripe's web portal
// This was manually ported over so there may be a chance of mistakes
// Last updated as of 29th March 2022.
// The code may not necessarily match with the name (ref SE_VAT)
// https://stripe.com/docs/api/customer_tax_ids/create
export interface TaxId {
  name: string
  type: string
  country: string
  placeholder: string
  vatPrefix?: string
}

export const TAX_IDS: TaxId[] = [
  {
    name: 'AE TRN',
    type: 'ae_trn',
    country: 'United Arab Emirates',
    placeholder: '123456789012345',
  },
  {
    name: 'AT VAT',
    type: 'eu_vat',
    country: 'Austria',
    placeholder: 'ATU12345678',
    vatPrefix: 'ATU',
  },
  {
    name: 'AD NRT',
    type: 'ad_nrt',
    country: 'Andorra',
    placeholder: 'A-123456-Z',
  },
  {
    name: 'AR CUIT',
    type: 'ar_cuit',
    country: 'Argentina',
    placeholder: '12-3456789-01',
  },
  {
    name: 'AU ABN',
    type: 'au_abn',
    country: 'Australia',
    placeholder: '12345678912',
  },
  {
    name: 'AU ARN',
    type: 'au_arn',
    country: 'Australia',
    placeholder: '123456789123',
  },
  {
    name: 'BE VAT',
    type: 'eu_vat',
    country: 'Belgium',
    placeholder: 'BE0123456789',
    vatPrefix: 'BE',
  },
  {
    name: 'BO TIN',
    type: 'bo_tin',
    country: 'Bolivia',
    placeholder: '123456789',
  },
  {
    name: 'BG VAT',
    type: 'eu_vat',
    country: 'Bulgaria',
    placeholder: 'BG0123456789',
    vatPrefix: 'BG',
  },
  {
    name: 'BR CNPJ',
    type: 'br_cnpj',
    country: 'Brazil',
    placeholder: '01.234.456/5432-10',
  },
  {
    name: 'BR CPF',
    type: 'br_cpf',
    country: 'Brazil',
    placeholder: '123.456.789-87',
  },
  {
    name: 'CA BN',
    type: 'ca_bn',
    country: 'Canada',
    placeholder: '123456789',
  },
  {
    name: 'CA GST/HST',
    type: 'ca_gst_hst',
    country: 'Canada',
    placeholder: '123456789RT0002',
  },
  {
    name: 'CA PST-BC',
    type: 'ca_pst_bc',
    country: 'Canada',
    placeholder: 'PST-1234-5678',
  },
  {
    name: 'CA PST-MB',
    type: 'ca_pst_mb',
    country: 'Canada',
    placeholder: '123456-7',
  },
  {
    name: 'CA PST-SK',
    type: 'ca_pst_mb',
    country: 'Canada',
    placeholder: '1234567',
  },
  {
    name: 'CA QST',
    type: 'ca_qst',
    country: 'Canada',
    placeholder: '1234567890TQ1234',
  },
  {
    name: 'CH VAT',
    type: 'ch_vat',
    country: 'Switzerland',
    placeholder: 'CHE-123.456.789 MWST',
    vatPrefix: 'CHE',
  },
  {
    name: 'CL TIN',
    type: 'cl_tin',
    country: 'Chile',
    placeholder: '12.345.678-K',
  },
  {
    name: 'CN TIN',
    type: 'cn_tin',
    country: 'China',
    placeholder: '123456789012345678',
  },
  {
    name: 'CO NIT',
    type: 'co_nit',
    country: 'Colombia',
    placeholder: '123.456.789-0',
  },
  {
    name: 'CR TIN',
    type: 'cr_tin',
    country: 'Costa Rica',
    placeholder: '1-234-567890',
  },
  {
    name: 'CY VAT',
    type: 'eu_vat',
    country: 'Cyprus',
    placeholder: 'CY12345678Z',
    vatPrefix: 'CY',
  },
  {
    name: 'CZ VAT',
    type: 'eu_vat',
    country: 'Czech Republic',
    placeholder: 'CZ1234567890',
    vatPrefix: 'CZ',
  },
  {
    name: 'DE VAT',
    type: 'eu_vat',
    country: 'Germany',
    placeholder: 'DE123456789',
    vatPrefix: 'DE',
  },
  {
    name: 'DK VAT',
    type: 'eu_vat',
    country: 'Denmark',
    placeholder: 'DK12345678',
    vatPrefix: 'DK',
  },
  {
    name: 'DO RCN',
    type: 'do_rcn',
    country: 'Dominican Republic',
    placeholder: '123-4567890-1',
  },
  {
    name: 'EE VAT',
    type: 'eu_vat',
    country: 'Estonia',
    placeholder: 'EE123456789',
    vatPrefix: 'EE',
  },
  {
    name: 'ES CIF',
    type: 'es_cif',
    country: 'Spain',
    placeholder: 'A12345678',
  },
  {
    name: 'ES VAT',
    type: 'eu_vat',
    country: 'Spain',
    placeholder: 'ESX1234567Z',
    vatPrefix: 'ES',
  },
  {
    name: 'FI VAT',
    type: 'eu_vat',
    country: 'Finland',
    placeholder: 'FI12345678',
    vatPrefix: 'FI',
  },
  {
    name: 'FR VAT',
    type: 'eu_vat',
    country: 'France',
    placeholder: 'FRAB123456789',
    vatPrefix: 'FR',
  },
  {
    name: 'GB VAT',
    type: 'eu_vat',
    country: 'United Kingdom',
    placeholder: 'GB123456789',
    vatPrefix: 'GB',
  },
  {
    name: 'GE VAT',
    type: 'ge_vat',
    country: 'Georgia',
    placeholder: '123456789',
  },
  {
    name: 'EL VAT',
    type: 'eu_vat',
    country: 'Greece',
    placeholder: 'EL123456789',
    vatPrefix: 'EL',
  },
  {
    name: 'HK BR',
    type: 'hk_br',
    country: 'Hong Kong SAR China',
    placeholder: '12345678',
  },
  {
    name: 'HR VAT',
    type: 'eu_vat',
    country: 'Croatia',
    placeholder: 'HR12345678912',
    vatPrefix: 'HR',
  },
  {
    name: 'HU VAT',
    type: 'eu_vat',
    country: 'Hungary',
    placeholder: 'HU12345678912',
    vatPrefix: 'HU',
  },
  {
    name: 'ID NPWP',
    type: 'id_npwp',
    country: 'Indonesia',
    placeholder: '12.345.678.9-012.345',
  },
  {
    name: 'IE VAT',
    type: 'eu_vat',
    country: 'Ireland',
    placeholder: 'IE1234567AB',
    vatPrefix: 'IE',
  },
  {
    name: 'IL VAT',
    type: 'il_vat',
    country: 'Israel',
    placeholder: '000012345',
  },
  {
    name: 'IN GST',
    type: 'in_gst',
    country: 'India',
    placeholder: '12ABCDE3456FGZH',
  },
  {
    name: 'IS VAT',
    type: 'is_vat',
    country: 'Iceland',
    placeholder: '123456',
  },
  {
    name: 'IT VAT',
    type: 'eu_vat',
    country: 'Italy',
    placeholder: 'IT12345678912',
    vatPrefix: 'IT',
  },
  {
    name: 'JP CN',
    type: 'jp_cn',
    country: 'Japan',
    placeholder: '1234567891234',
  },
  {
    name: 'KE PIN',
    type: 'ke_pin',
    country: 'Kenya',
    placeholder: 'P000111111A',
  },
  {
    name: 'JP RN',
    type: 'jp_rn',
    country: 'Japan',
    placeholder: '12345',
  },
  {
    name: 'KR BRN',
    type: 'kr_brn',
    country: 'Korea',
    placeholder: '123-45-67890',
  },
  {
    name: 'LI UID',
    type: 'li_uid',
    country: 'Liechtenstein',
    placeholder: 'CHE123456789',
  },
  {
    name: 'LT VAT',
    type: 'eu_vat',
    country: 'Lithuania',
    placeholder: 'LT123456789123',
    vatPrefix: 'LT',
  },
  {
    name: 'LU VAT',
    type: 'eu_vat',
    country: 'Luxembourg',
    placeholder: 'LU12345678',
    vatPrefix: 'LU',
  },
  {
    name: 'LV VAT',
    type: 'eu_vat',
    country: 'Latvia',
    placeholder: 'LV12345678912',
    vatPrefix: 'LV',
  },
  {
    name: 'MT VAT',
    type: 'eu_vat',
    country: 'Malta',
    placeholder: 'MT12345678',
    vatPrefix: 'MT',
  },
  {
    name: 'MX RFC',
    type: 'mx_rfc',
    country: 'Mexico',
    placeholder: 'ABC010203AB9',
  },
  {
    name: 'MY FRP',
    type: 'my_frp',
    country: 'Malaysia',
    placeholder: '12345678',
  },
  {
    name: 'MY ITN',
    type: 'my_itn',
    country: 'Malaysia',
    placeholder: 'C 1234567890',
  },
  {
    name: 'MY SST',
    type: 'my_sst',
    country: 'Malaysia',
    placeholder: 'A12-3456-78912345',
  },
  {
    name: 'NL VAT',
    type: 'eu_vat',
    country: 'Netherlands',
    placeholder: 'NL123456789B12',
    vatPrefix: 'NL',
  },
  {
    name: 'NO VAT',
    type: 'no_vat',
    country: 'Norway',
    placeholder: '123456789MVA',
  },
  {
    name: 'PE RUC',
    type: 'pe_ruc',
    country: 'Peru',
    placeholder: '12345678901',
  },
  {
    name: 'PH TIN',
    type: 'ph_tin',
    country: 'Philippines',
    placeholder: '123456789012',
  },
  {
    name: 'NZ GST',
    type: 'nz_gst',
    country: 'New Zealand',
    placeholder: '123456789',
  },
  {
    name: 'PL VAT',
    type: 'eu_vat',
    country: 'Poland',
    placeholder: 'PL1234567890',
    vatPrefix: 'PL',
  },
  {
    name: 'PT VAT',
    type: 'eu_vat',
    country: 'Portugal',
    placeholder: 'PT123456789',
    vatPrefix: 'PT',
  },
  {
    name: 'RO VAT',
    type: 'eu_vat',
    country: 'Romania',
    placeholder: 'RO1234567891',
    vatPrefix: 'RO',
  },
  {
    name: 'RU INN',
    type: 'ru_inn',
    country: 'Russia',
    placeholder: '1234567891',
  },
  {
    name: 'RU KPP',
    type: 'ru_kpp',
    country: 'Russia',
    placeholder: '123456789',
  },
  {
    name: 'SA VAT',
    type: 'sa_vat',
    country: 'Saudi Arabia',
    placeholder: '123456789012345',
  },
  {
    name: 'RS PIB',
    type: 'rs_pib',
    country: 'Serbia',
    placeholder: '123456789',
  },
  {
    name: 'SE VAT',
    type: 'eu_vat',
    country: 'Sweden',
    placeholder: 'SE123456789123',
    vatPrefix: 'SE',
  },
  {
    name: 'SG GST',
    type: 'sg_gst',
    country: 'Singapore',
    placeholder: 'M12345678X',
  },
  {
    name: 'SG UEN',
    type: 'sg_uen',
    country: 'Singapore',
    placeholder: '123456789F',
  },
  {
    name: 'SI VAT',
    type: 'eu_vat',
    country: 'Slovenia',
    placeholder: 'SI12345678',
    vatPrefix: 'SI',
  },
  {
    name: 'SK VAT',
    type: 'eu_vat',
    country: 'Slovakia',
    placeholder: 'SK1234567891',
    vatPrefix: 'SK',
  },
  {
    name: 'TH VAT',
    type: 'th_vat',
    country: 'Thailand',
    placeholder: '1234567891234',
  },
  {
    name: 'TR TIN',
    type: 'tr_tin',
    country: 'Turkey',
    placeholder: '0123456789',
  },
  {
    name: 'TW VAT',
    type: 'tw_vat',
    country: 'Taiwan',
    placeholder: '12345678',
  },
  {
    name: 'UA VAT',
    type: 'ua_vat',
    country: 'Ukraine',
    placeholder: '123456789',
  },
  {
    name: 'US EIN',
    type: 'us_ein',
    country: 'United States',
    placeholder: '12-3456789',
  },
  {
    name: 'XI VAT',
    type: 'eu_vat',
    country: 'United Kingdom (Northern Ireland)',
    placeholder: 'XI123456789',
    vatPrefix: 'XI',
  },
  {
    name: 'ZA VAT',
    type: 'za_vat',
    country: 'South Africa',
    placeholder: '4123456789',
  },
  {
    name: 'UY RUC',
    type: 'uy_ruc',
    country: 'Uruguay',
    placeholder: '123456789012',
  },
  {
    name: 'VE RIF',
    type: 've_rif',
    country: 'Venezuela',
    placeholder: 'A-12345678-9',
  },
  {
    name: 'VN TIN',
    type: 'vn_tin',
    country: 'Vietnam',
    placeholder: '1234567890',
  },
]
