// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconZoomIn(props: IconProps) {
  return <Icon type="ZoomIn" {...props} />
}

export default IconZoomIn
