import type { Template } from './template-catalog'

export const testTemplates: Template[] = [
  {
    id: 'database',
    name: 'Database',
    description: 'PostgreSQL database with schemas and seed support',
    category: 'Core',
    version: '1.0.0',
    defaultEnabled: true,
    tags: ['database', 'postgres'],
    files: [
      {
        path: 'supabase/config.toml',
        content: '[db]\nenabled = true\n',
      },
    ],
  },
  {
    id: 'auth',
    name: 'Auth',
    description: 'User authentication and policies',
    category: 'Core',
    version: '1.0.0',
    dependencies: { required: ['database'] },
    files: [
      {
        path: 'supabase/config.toml',
        content: '[auth]\nenabled = true\n',
      },
    ],
  },
  {
    id: 'storage',
    name: 'Storage',
    description: 'Supabase Storage service',
    category: 'Core',
    version: '1.0.0',
    dependencies: { required: ['database'] },
    files: [
      {
        path: 'supabase/config.toml',
        content: '[storage]\nenabled = true\n',
      },
    ],
  },
  {
    id: 'functions',
    name: 'Edge Functions',
    description: 'Supabase Edge Functions runtime',
    category: 'Core',
    version: '1.0.0',
    dependencies: { required: ['database'] },
    files: [
      {
        path: 'supabase/config.toml',
        content: '[edge_runtime]\nenabled = true\n',
      },
    ],
  },
  {
    id: 'api',
    name: 'Data API',
    description: 'REST and GraphQL APIs for exposed schemas',
    category: 'Core',
    version: '1.0.0',
    dependencies: { required: ['database'] },
    files: [
      {
        path: 'supabase/config.toml',
        content: '[api]\nenabled = true\nschemas = ["public"]\n',
      },
    ],
  },
  {
    id: 'todos',
    name: 'Todos',
    description: 'Example todo table with RLS policies',
    category: 'Database',
    version: '1.0.0',
    defaultEnabled: true,
    dependencies: { required: ['database', 'auth'] },
    files: [
      {
        path: 'supabase/schemas/todos.sql',
        content: `create table public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null
);
`,
      },
    ],
  },
  {
    id: 'multi-tenant-rbac',
    name: 'Multi-tenant RBAC',
    description: 'Organization-scoped authorization for SaaS applications',
    category: 'Security',
    version: '1.0.0',
    dependencies: { required: ['database', 'auth'] },
    files: [
      {
        path: 'supabase/schemas/authorization.sql',
        content: `create table public.organizations (
  id uuid primary key,
  name text not null
);
`,
      },
    ],
  },
  {
    id: 'storage-avatars',
    name: 'Storage Avatars',
    description: 'Private avatar bucket and storage policies',
    category: 'Storage',
    version: '1.0.0',
    dependencies: { required: ['database', 'auth', 'storage'] },
    files: [
      {
        path: 'supabase/schemas/storage.sql',
        content: `insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', false);
`,
      },
    ],
  },
  {
    id: 'functions-stripe-webhook',
    name: 'Stripe Webhook',
    description: 'Stripe webhook Edge Function',
    category: 'Integrations',
    version: '1.0.0',
    dependencies: { required: ['database', 'functions'] },
    files: [
      {
        path: 'supabase/functions/stripe-webhook/index.ts',
        content: 'Deno.serve(() => new Response("ok"))\n',
      },
      {
        path: 'supabase/schemas/billing.sql',
        content: 'create table public.customers (id text primary key);\n',
      },
    ],
  },
]
