#!/usr/bin/env python3
"""
Generate docker-compose auth service definitions from the database registry.
Usage: python3 docker/scripts/generate-compose-auth.py > docker/docker-compose.auth.yml

Each database entry in the registry gets its own GoTrue container named
  supabase-auth-{ref}
listening on port 9999 internally, reachable via Docker DNS as
  supabase-auth-{ref}:9999

Environment variable resolution:
  - host/database fields that use ${VAR:-default} syntax are passed through
    to docker-compose as literal ${VAR:-default} so they resolve at runtime.
  - password_env / jwt_secret_env are referenced via ${VAR} interpolation.
"""
import json
import os
import sys

REGISTRY_PATH = os.environ.get(
    "DATABASE_REGISTRY_PATH",
    "docker/volumes/registry/databases.json",
)

# GoTrue image version — keep in sync with the base auth service in docker-compose.yml
GOTRUE_IMAGE = "supabase/gotrue:v2.189.0"


def load_registry(path: str) -> dict:
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"ERROR: registry not found at {path}", file=sys.stderr)
        sys.exit(1)


def service_block(db: dict) -> str:
    ref = db["ref"]
    # These may contain ${VAR:-default} shell syntax — emit as-is for docker-compose interpolation
    host = db.get("host", "${POSTGRES_HOST:-db}")
    port = db.get("port", 5432)
    database = db.get("database", "${POSTGRES_DB:-postgres}")
    password_env = db.get("password_env", "POSTGRES_PASSWORD")
    jwt_secret_env = db.get("jwt_secret_env", "JWT_SECRET")

    # Build the DATABASE_URL. If host/database contain ${...} expressions they
    # pass through correctly in a double-quoted yaml scalar.
    db_url = (
        f"postgres://supabase_auth_admin:${{{password_env}}}"
        f"@{host}:{port}/{database}?search_path=auth"
    )

    return f"""\
  auth-{ref}:
    container_name: supabase-auth-{ref}
    image: {GOTRUE_IMAGE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/health"]
      timeout: 5s
      interval: 5s
      retries: 3
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${{API_EXTERNAL_URL}}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: "{db_url}"
      GOTRUE_SITE_URL: ${{SITE_URL}}
      GOTRUE_URI_ALLOW_LIST: ${{ADDITIONAL_REDIRECT_URLS}}
      GOTRUE_DISABLE_SIGNUP: "${{DISABLE_SIGNUP}}"
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${{JWT_EXPIRY:-3600}}
      GOTRUE_JWT_SECRET: ${{{jwt_secret_env}}}
      GOTRUE_JWT_ISSUER: ${{API_EXTERNAL_URL}}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${{ENABLE_EMAIL_SIGNUP}}
      GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED: ${{ENABLE_ANONYMOUS_USERS}}
      GOTRUE_MAILER_AUTOCONFIRM: ${{ENABLE_EMAIL_AUTOCONFIRM}}
      GOTRUE_SMTP_ADMIN_EMAIL: ${{SMTP_ADMIN_EMAIL}}
      GOTRUE_SMTP_HOST: ${{SMTP_HOST}}
      GOTRUE_SMTP_PORT: ${{SMTP_PORT:-587}}
      GOTRUE_SMTP_USER: ${{SMTP_USER}}
      GOTRUE_SMTP_PASS: ${{SMTP_PASS}}
      GOTRUE_SMTP_SENDER_NAME: ${{SMTP_SENDER_NAME}}
      GOTRUE_MAILER_URLPATHS_INVITE: ${{MAILER_URLPATHS_INVITE:-/auth/v1/verify}}
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: ${{MAILER_URLPATHS_CONFIRMATION:-/auth/v1/verify}}
      GOTRUE_MAILER_URLPATHS_RECOVERY: ${{MAILER_URLPATHS_RECOVERY:-/auth/v1/verify}}
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: ${{MAILER_URLPATHS_EMAIL_CHANGE:-/auth/v1/verify}}
      GOTRUE_RATE_LIMIT_HEADER: X-Forwarded-For
      GOTRUE_RATE_LIMIT_EMAIL_SENT: ${{RATE_LIMIT_EMAIL_SENT:-100}}
      GOTRUE_EXTERNAL_PHONE_ENABLED: ${{ENABLE_PHONE_SIGNUP}}
      GOTRUE_SMS_AUTOCONFIRM: ${{ENABLE_PHONE_AUTOCONFIRM}}
    networks:
      - supabase_network_default
"""


def main() -> None:
    registry = load_registry(REGISTRY_PATH)
    databases = registry.get("databases", [])

    if not databases:
        print("WARNING: no databases found in registry", file=sys.stderr)
        sys.exit(0)

    lines = [
        "# Auto-generated by docker/scripts/generate-compose-auth.py",
        "# Do not edit manually.",
        "# Regenerate with:",
        "#   cd <repo-root>",
        "#   python3 docker/scripts/generate-compose-auth.py > docker/docker-compose.auth.yml",
        "# Then bring up with:",
        "#   docker compose -f docker/docker-compose.yml -f docker/docker-compose.auth.yml up -d",
        "",
        "services:",
    ]

    for db in databases:
        lines.append(service_block(db))

    lines += [
        "networks:",
        "  supabase_network_default:",
        "    external: true",
        "",
    ]

    print("\n".join(lines))


if __name__ == "__main__":
    main()