#!/usr/bin/env python3
"""
Generate Envoy CDS (cluster discovery service) config for per-database GoTrue instances.

Usage:
  python3 docker/scripts/generate-envoy-clusters.py \
      > docker/volumes/api/envoy/cds.multi.yaml

The output file merges the existing clusters from cds.yaml with a new
  auth-{ref}  cluster for every database in the registry.
Envoy resolves  supabase-auth-{ref}  via Docker DNS on port 9999.

Requirements:
  pip install pyyaml      (or: python3 -m pip install pyyaml)
"""
import json
import os
import sys

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required — install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REGISTRY_PATH = os.environ.get(
    "DATABASE_REGISTRY_PATH",
    "docker/volumes/registry/databases.json",
)
BASE_CDS = os.environ.get(
    "BASE_CDS_PATH",
    "docker/volumes/api/envoy/cds.yaml",
)


def load_json(path: str) -> dict:
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"ERROR: file not found: {path}", file=sys.stderr)
        sys.exit(1)


def load_yaml(path: str) -> dict:
    try:
        with open(path) as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        print(f"ERROR: file not found: {path}", file=sys.stderr)
        sys.exit(1)


def auth_cluster(ref: str) -> dict:
    """Build a STRICT_DNS cluster definition for supabase-auth-{ref}."""
    return {
        "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
        "name": f"auth-{ref}",
        "connect_timeout": "15s",
        "type": "STRICT_DNS",
        "dns_refresh_rate": "5s",
        "dns_failure_refresh_rate": {
            "base_interval": "1s",
            "max_interval": "5s",
        },
        "dns_lookup_family": "V4_ONLY",
        "lb_policy": "ROUND_ROBIN",
        "load_assignment": {
            "cluster_name": f"auth-{ref}",
            "endpoints": [
                {
                    "lb_endpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socket_address": {
                                        "address": f"supabase-auth-{ref}",
                                        "port_value": 9999,
                                    }
                                }
                            }
                        }
                    ]
                }
            ],
        },
        "health_checks": [
            {
                "timeout": "2s",
                "interval": "5s",
                "unhealthy_threshold": 3,
                "healthy_threshold": 2,
                "http_health_check": {"path": "/health"},
            }
        ],
        "circuit_breakers": {
            "thresholds": [
                {
                    "priority": "DEFAULT",
                    "max_connections": 10000,
                    "max_pending_requests": 10000,
                    "max_requests": 10000,
                }
            ]
        },
    }


def main() -> None:
    registry = load_json(REGISTRY_PATH)
    base = load_yaml(BASE_CDS)

    databases = registry.get("databases", [])
    if not databases:
        print("WARNING: no databases in registry; outputting base cds.yaml unchanged", file=sys.stderr)
        print(yaml.dump(base, default_flow_style=False, sort_keys=False))
        return

    existing_cluster_names = {c.get("name") for c in base.get("resources", [])}

    added = []
    for db in databases:
        ref = db["ref"]
        cluster_name = f"auth-{ref}"
        if cluster_name in existing_cluster_names:
            print(
                f"INFO: cluster '{cluster_name}' already exists in base cds.yaml — skipping",
                file=sys.stderr,
            )
            continue
        base.setdefault("resources", []).append(auth_cluster(ref))
        added.append(cluster_name)

    if added:
        print(f"INFO: added clusters: {added}", file=sys.stderr)

    header = (
        "# Auto-generated by docker/scripts/generate-envoy-clusters.py\n"
        "# Do not edit manually.\n"
        "# Regenerate with:\n"
        "#   python3 docker/scripts/generate-envoy-clusters.py \\\n"
        "#       > docker/volumes/api/envoy/cds.multi.yaml\n"
        "# Then restart kong/envoy to pick up the new clusters.\n"
        "\n"
    )
    print(header + yaml.dump(base, default_flow_style=False, sort_keys=False))


if __name__ == "__main__":
    main()