// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Cpu } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconCpu(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Cpu} {...props} />
}

export default IconCpu
