// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconChevronsDown(props: IconProps) {
  return <Icon type="ChevronsDown" {...props} />
}

export default IconChevronsDown
