import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './Providers'
import SideNav from './[org]/side-nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          themes={['dark', 'light', 'deep-dark']}
          defaultTheme="deep-dark"
          enableSystem
        >
          <main className="h-screen w-screen flex">
            <SideNav />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
