// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconMoreHorizontal(props: IconProps) {
  return <Icon type="MoreHorizontal" {...props} />
}

export default IconMoreHorizontal
