// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { CameraOff } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconCameraOff(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={CameraOff} {...props} />
}

export default IconCameraOff
