import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.

# Channels are not secured by default in development and
# are secured by default in production.
presence = System.get_env("PRESENCE", "false") == "false"

config :realtime,
  presence: presence,
  load_tenant_db_dump: false,
  node_balance_uptime_threshold_in_ms: 100,
  access_token_throttle_ms: to_timeout(second: 10)

port_free? = fn port ->
  case :gen_tcp.listen(port, [:inet, ip: {0, 0, 0, 0}, reuseaddr: true, active: false]) do
    {:ok, socket} -> :gen_tcp.close(socket) == :ok
    {:error, _reason} -> false
  end
end

port =
  case System.get_env("PORT") do
    nil ->
      Enum.find(4000..4999, port_free?) || raise "no free port found on range 4000..4999"

    pinned ->
      pinned = String.to_integer(pinned)

      if !port_free?.(pinned) do
        raise """
        PORT=#{pinned} is set but it's already in use.
        """
      end

      pinned
  end

config :realtime, RealtimeWeb.Endpoint,
  http: [port: port, compress: true],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# watchers: [
#   node: [
#     "node_modules/webpack/bin/webpack.js",
#     "--mode",
#     "development",
#     "--watch-stdin",
#     cd: Path.expand("../assets", __DIR__)
#   ]
# ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :realtime, RealtimeWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/realtime_web/(live|views)/.*(ex)$",
      ~r"lib/realtime_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter,
  format: "$time [$level] $message $metadata\n",
  metadata: [
    :error_code,
    :file,
    :pid,
    :project,
    :external_id,
    :application_name,
    :region,
    :request_id,
    :sub,
    :iss,
    :exp
  ]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable caching to ensure the rendered spec is refreshed
config :open_api_spex, :cache_adapter, OpenApiSpex.Plug.NoneCache

# Disabled but can print to stdout with:
# config :opentelemetry, traces_exporter: {:otel_exporter_stdout, []}
config :opentelemetry, traces_exporter: :none

config :mix_test_watch, clear: true
