import './globals.css'
import Login from './login'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* @ts-expect-error next version of TS will fix this */}
        <Login />
        {children}
      </body>
    </html>
  )
}
