# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "protomaps"

# Disable data API since we are not using the PostgREST client in this example.
[api]
enabled = false

[storage]
enabled = true
# The maximum file size allowed for all buckets in the project.
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true

[storage.buckets.maps-private]
public = false
# file_size_limit = "50MiB"
# allowed_mime_types = ["application/vnd.pmtiles"]
# Uncomment to specify a local directory to upload objects to the bucket.
# objects_path = "./buckets/maps-private"

[edge_runtime]
enabled = true
# Configure one of the supported request policies: `oneshot`, `per_worker`.
# Use `oneshot` for hot reload, or `per_worker` for load testing.
policy = "oneshot"
# Port to attach the Chrome inspector for debugging Edge Functions locally.
inspector_port = 8083

[functions.maps-private]
enabled = true
verify_jwt = false
# import_map = "./functions/maps-private/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
# entrypoint = "./functions/maps-private/index.ts"
