// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { FolderMinus } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconFolderMinus(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={FolderMinus} {...props} />
}

export default IconFolderMinus
