// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconFolderMinus(props: IconProps) {
  return <Icon type="FolderMinus" {...props} />
}

export default IconFolderMinus
