// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconDivideSquare(props: IconProps) {
  return <Icon type="DivideSquare" {...props} />
}

export default IconDivideSquare
