// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconLayout(props: IconProps) {
  return <Icon type="Layout" {...props} />
}

export default IconLayout
