// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconTarget(props: IconProps) {
  return <Icon type="Target" {...props} />
}

export default IconTarget
