- name: tmux - Install tmux
  ansible.builtin.apt:
    name: 'tmux'
    state: 'present'
  become: true

- name: tmux - Configure tmux alias
  ansible.builtin.copy:
    content: |
      case "$-" in
        *i*) alias tmux='tmux new-session -A -s supa' ;;
      esac
    dest: '/etc/profile.d/11-tmux_alias.sh'
    group: 'root'
    mode: '0644'
    owner: 'root'
  become: true

- name: tmux - Configure tmux
  ansible.builtin.template:
    dest: '/etc/tmux.conf'
    group: 'root'
    mode: '0644'
    owner: 'root'
    src: 'files/tmux.conf.j2'
  become: true

- name: tmux - Auto-logout from stale tmux
  ansible.builtin.copy:
    content: |
      case "$-" in
        *i*)
          case "$TERM" in
            tmux*) export TMOUT=86400 ;;
          esac
          ;;
      esac
    dest: '/etc/profile.d/12-tmux_logout.sh'
    group: 'root'
    mode: '0644'
    owner: 'root'
  become: true
