// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconBriefcase(props: IconProps) {
  return <Icon type="Briefcase" {...props} />
}

export default IconBriefcase
