// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Briefcase } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconBriefcase(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Briefcase} {...props} />
}

export default IconBriefcase
