-- Multi-tenant schema with organization-scoped RLS.
-- Add tenant_id to your tables and reuse the membership checks below.

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_at timestamptz default now()
);

create table public.organization_members (
  id bigint generated by default as identity primary key,
  organization_id uuid references public.organizations on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  created_at timestamptz default now(),
  unique (organization_id, user_id)
);

create or replace function public.current_organization_ids()
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select organization_id
  from public.organization_members
  where user_id = auth.uid();
$$;

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;

create policy "Members can read their organizations"
on public.organizations
for select
to authenticated
using (id in (select public.current_organization_ids()));

create policy "Members can read organization memberships"
on public.organization_members
for select
to authenticated
using (organization_id in (select public.current_organization_ids()));

create policy "Users can read their own memberships"
on public.organization_members
for select
to authenticated
using (user_id = auth.uid());

-- Example tenant-scoped table
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations on delete cascade not null,
  name text not null,
  created_at timestamptz default now()
);

alter table public.projects enable row level security;

create policy "Members can read projects in their organizations"
on public.projects
for select
to authenticated
using (organization_id in (select public.current_organization_ids()));

create policy "Members can insert projects in their organizations"
on public.projects
for insert
to authenticated
with check (organization_id in (select public.current_organization_ids()));

create policy "Members can update projects in their organizations"
on public.projects
for update
to authenticated
using (organization_id in (select public.current_organization_ids()));

create policy "Members can delete projects in their organizations"
on public.projects
for delete
to authenticated
using (organization_id in (select public.current_organization_ids()));
