// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Hexagon } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconHexagon(props: any) {
    return <IconBase icon={Hexagon} {...props} />
  }

  export default IconHexagon
  