services:

  minio:
    image: cgr.dev/chainguard/minio
    #ports:
    #  - '9000:9000'
    #  - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 2s
      timeout: 10s
      retries: 5
    volumes:
      - minio-data:/data

  minio-createbucket:
    image: cgr.dev/chainguard/minio-client:latest-dev
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -ec "
      mc alias set supa-minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb --ignore-existing supa-minio/${GLOBAL_S3_BUCKET}
      "

  storage:
    depends_on:
      minio-createbucket:
        condition: service_completed_successfully
      minio:
        condition: service_healthy
    environment:
      STORAGE_BACKEND: s3
      GLOBAL_S3_ENDPOINT: http://minio:9000
      GLOBAL_S3_PROTOCOL: http
      GLOBAL_S3_FORCE_PATH_STYLE: true
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}

volumes:
  minio-data:
