services:

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./volumes/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      kong:
        condition: service_healthy
    environment:
      DOMAIN: ${DOMAIN}

volumes:
  caddy_data:
  caddy_config:
