services:
  storage:
    environment:
      STORAGE_BACKEND: ${STORAGE_BACKEND:-file}
      GLOBAL_S3_ENDPOINT: ${GLOBAL_S3_ENDPOINT:-}
      GLOBAL_S3_PROTOCOL: ${GLOBAL_S3_PROTOCOL:-https}
      GLOBAL_S3_FORCE_PATH_STYLE: ${GLOBAL_S3_FORCE_PATH_STYLE:-true}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
