## For use with the VS Code Extension "REST Client"
## https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### [PostgREST] 401 Unauthorized: No API key found in request
GET http://localhost:8000/rest/v1/ HTTP/1.1
Content-Type: application/json

### [PostgREST] 200 OK: anon key for PostgREST
GET http://localhost:8000/rest/v1/ HTTP/1.1
Content-Type: application/json
apikey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyNzIwODU0MCwiZXhwIjoxOTc0MzYzNzQwfQ.zcaQfHd3VA7XgJmdGfmV86OLVJT9s2MTmSy-e69BpUY

### [postgres-meta] 403 Forbidden: anon key not allowed
GET http://localhost:8000/pg/health HTTP/1.1
content-type: application/json
apikey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyNzIwODU0MCwiZXhwIjoxOTc0MzYzNzQwfQ.zcaQfHd3VA7XgJmdGfmV86OLVJT9s2MTmSy-e69BpUY


### [postgres-meta] 200 OK: service_key is allowed
GET http://localhost:8000/pg/health HTTP/1.1
content-type: application/json
apikey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjI3MjA4NTQwLCJleHAiOjE5NzQzNjM3NDB9.pkT3PNpO4DtO45Ac5HK_TKCx8sGLgNtV__pr_ZrRSAU
