// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconList(props: IconProps) {
  return <Icon type="List" {...props} />
}

export default IconList
