// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconShare(props: IconProps) {
  return <Icon type="Share" {...props} />
}

export default IconShare
