// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import React from 'react'
  // @ts-ignore
  import { Umbrella } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconUmbrella(props: any) {
    return <IconBase icon={Umbrella} {...props} />
  }

  export default IconUmbrella
  