// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconLogIn(props: IconProps) {
  return <Icon type="LogIn" {...props} />
}

export default IconLogIn
