// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/info'
  import IconBase from './../../IconBase'

  function IconInfo(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconInfo
  