// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Folder } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconFolder(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Folder} {...props} />
}

export default IconFolder
