// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Figma } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconFigma(props: any) {
    return <IconBase icon={Figma} {...props} />
  }

  export default IconFigma
  