// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconFile(props: IconProps) {
  return <Icon type="File" {...props} />
}

export default IconFile
