--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2
-- Dumped by pg_dump version 11.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: cities; Type: TABLE; Schema: public; Owner: supabase
--

CREATE TABLE public.cities (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    country_id integer NOT NULL
);


ALTER TABLE public.cities OWNER TO supabase;

--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: countries; Type: TABLE; Schema: public; Owner: supabase
--

CREATE TABLE public.countries (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    iso2 character varying(5) NOT NULL,
    continent character varying(255) NOT NULL
);


ALTER TABLE public.countries OWNER TO supabase;

--
-- Name: countries_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase
--

ALTER TABLE public.countries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cities; Type: TABLE DATA; Schema: public; Owner: supabase
--

COPY public.cities (id, name, country_id) FROM stdin;
1	Rio de Janeiro	1
2	Beijing	2
3	Paris	3
4	Auckland	4
5	Lagos	5
6	San Francisco	6
\.


--
-- Data for Name: countries; Type: TABLE DATA; Schema: public; Owner: supabase
--

COPY public.countries (id, name, iso2, continent) FROM stdin;
1	Brazil	BR	South America
2	China	CN	Asia
3	France	FR	Europe
4	New Zealand	NZ	Oceania
5	Nigeria	NG	Africa
6	United States	US	North America
\.


--
-- Name: cities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase
--

SELECT pg_catalog.setval('public.cities_id_seq', 6, true);


--
-- Name: countries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase
--

SELECT pg_catalog.setval('public.countries_id_seq', 6, true);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: countries countries_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (id);


--
-- Name: cities cities_countries_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_countries_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

