_format_version: "1.1"
services:
-   name: auth-v1-open
    url: http://auth:9999/verify
    routes:
    -   name: auth-v1-open
        strip_path: true
        paths:
        - /auth/v1/verify
    plugins:
    -   name: cors
-   name: auth-v1-open-callback
    url: http://auth:9999/callback
    routes:
    -   name: auth-v1-open-callback
        strip_path: true
        paths:
        - /auth/v1/callback
    plugins:
    -   name: cors
-   name: auth-v1-open-authorize
    url: http://auth:9999/authorize
    routes:
    -   name: auth-v1-open-authorize
        strip_path: true
        paths:
        - /auth/v1/authorize
    plugins:
    -   name: cors
-   name: auth-v1
    _comment: 'GoTrue: /auth/v1/* -> http://auth:9999/*'
    url: http://auth:9999/
    routes:
    -   name: auth-v1-all
        strip_path: true
        paths:
        - /auth/v1/
    plugins:
    -   name: cors
    -   name: key-auth
        config:
            hide_credentials: true
-   name: rest-v1
    _comment: 'PostgREST: /rest/v1/* -> http://rest:3000/*'
    url: http://rest:3000/
    routes:
    -   name: rest-v1-all
        strip_path: true
        paths:
        - /rest/v1/
    plugins:
    -   name: cors
    -   name: key-auth
        config:
            hide_credentials: true
-   name: realtime-v1
    _comment: 'Realtime: /realtime/v1/* -> ws://realtime:4000/socket/*'
    url: http://realtime:4000/socket/
    routes:
    -   name: realtime-v1-all
        strip_path: true
        paths:
        - /realtime/v1/
    plugins:
    -   name: cors
    -   name: key-auth
        config:
            hide_credentials: true
-   name: storage-v1
    _comment: 'Storage: /storage/v1/* -> http://storage-api:5000/*'
    url: http://storage:5000/
    routes:
    -   name: storage-v1-all
        strip_path: true
        paths:
        - /storage/v1/
    plugins:
    -   name: cors
consumers:
-   username: 'anon-key'
    keyauth_credentials:
    -   key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYyNzIwODU0MCwiZXhwIjoxOTc0MzYzNzQwLCJhdWQiOiIiLCJzdWIiOiIiLCJyb2xlIjoiYW5vbiJ9.sUHErUOiKZ3nHQIxy-7jND6B80Uzf9G4NtMLmL6HXPQ
-   username: 'service-key'
    keyauth_credentials:
    -   key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYyNzIwNzUzMiwiZXhwIjoxNjkwMjc5NTMyLCJhdWQiOiIiLCJzdWIiOiIiLCJyb2xlIjoic2VydmljZV9yb2xlIn0.hfdXFZV5PdvUdo2xK0vStb1i97GJukSkRqfwd4YIh2M