_format_version: "1.1"
services:
-   name: auth-v1
    _comment: 'GoTrue: /auth/v1/* -> http://auth:9999/*'
    url: http://auth:9999/
    routes:
    -   name: auth-v1-all
        strip_path: true
        paths:
        - /auth/v1/
    plugins:
    -   name: cors
    -   name: key-auth
        config:
            hide_credentials: true
-   name: rest-v1
    _comment: 'PostgREST: /rest/v1/* -> http://rest:3000/*'
    url: http://rest:3000/
    routes:
    -   name: rest-v1-all
        strip_path: true
        paths:
        - /rest/v1/
    plugins:
    -   name: cors
    -   name: key-auth
        config:
            hide_credentials: true
-   name: realtime-v1
    _comment: 'Realtime: /realtime/v1/* -> ws://realtime:4000/socket/*'
    url: http://realtime:4000/socket/
    routes:
    -   name: realtime-v1-all
        strip_path: true
        paths:
        - /realtime/v1/
    plugins:
    -   name: cors
    -   name: key-auth
        config:
            hide_credentials: true
-   name: storage-v1
    _comment: 'Storage: /storage/v1/* -> http://storage-api:5000/*'
    url: http://storage:5000/
    routes:
    -   name: storage-v1-all
        strip_path: true
        paths:
        - /storage/v1/
    plugins:
    -   name: cors
consumers:
-   username: 'anon-key'
    keyauth_credentials:
    -   key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoxNjIwNzQyMTM1LCJhdWQiOiIiLCJzdWIiOiIiLCJSb2xlIjoiYW5vbiIsImp0aSI6ImQ1N2ZkMjFlLTNkYjQtNDk3YS1hNGViLTI4ZDY3Yzg2NjEwMiJ9.Uc0w024BLhWjMAAdzMJfkMxaFa82N-6pBxAtEGzrXCQ
-   username: 'service-key'
    keyauth_credentials:
    -   key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoxNjIwNzQyMTU1LCJhdWQiOiIiLCJzdWIiOiIiLCJSb2xlIjoic2VydmljZV9yb2xlIiwianRpIjoiOTk4MzJiYmItNDdhNS00NzJhLTgxMDQtYzY4ZGVjZDQyZDVlIn0.zQXx74dQyhpkcqZOMxsx961DPsDz4-nWxTLrCAd-ioI
