// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Power } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconPower(props: any) {
    return <IconBase icon={Power} {...props} />
  }

  export default IconPower
  