// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Power } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconPower(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Power} {...props} />
}

export default IconPower
