-- We apply our test seedings to template1 so every new created db will have the same structure
\c template1

CREATE TABLE public.category (
	id serial NOT NULL PRIMARY KEY,
	name text NOT NULL
);

-- Fake policies
grant select, update(name)
on category
to postgres;

create policy categories_update_policy
on category for update 
to postgres
using(current_setting('my.username') IN (name));

INSERT INTO public.category (id, name) VALUES
(1, 'Funny'),
(2, 'Weird'),
(3, 'Dumb'),
(4, 'Cute'),
(5, 'Interesting');

CREATE TYPE meme_status AS ENUM ('new', 'old', 'retired');

CREATE TABLE public.memes (
	id serial NOT NULL PRIMARY KEY,
	name text NOT NULL,
	category INTEGER REFERENCES category(id),
	metadata jsonb,
	created_at TIMESTAMP NOT NULL,
	status meme_status DEFAULT 'old'
);

INSERT INTO public.memes (name, category, created_at) VALUES
('NO. Rage Face', 5, NOW()),
('"Not Bad" Obama Face', 5, NOW()),
('You Know I Had to Do It to Em', 5, NOW()),
('Rage Comics', 1, NOW()),
('Okay Guy', 4, NOW()),
('Derp', 2, NOW()),
('Jessi Slaughter', 2, NOW()),
('Brazzers', 3, NOW()),
('Dat Boi', 1, NOW()),
('Bad Luck Brian', 4, NOW()),
('Lemon Party', 1, NOW()),
('Philosoraptor', 4, NOW()),
('Fuck Yea', 3, NOW()),
('Harambe the Gorilla', 4, NOW()),
('Press F to Pay Respects', 1, NOW()),
('GamerGate', 4, NOW()),
('60''s Spider-Man', 1, NOW()),
('MonkaS', 2, NOW()),
('Dick Butt', 3, NOW()),
('Rage Guy (FFFFFUUUUUUUU-)', 4, NOW()),
('Blue Whale Challenge', 5, NOW()),
('Ricardo Milos', 3, NOW()),
('[10] Guy', 1, NOW()),
('Wat', 3, NOW()),
('Big Chungus', 1, NOW()),
('Haters Gonna Hate', 3, NOW()),
('Do You Even Lift?', 1, NOW()),
('Kappa', 5, NOW()),
('Sad Keanu', 5, NOW()),
('"You Are Already Dead" / "Omae Wa Mou Shindeiru"', 1, NOW()),
('Mega Milk / Titty Monster', 4, NOW()),
('Annoying Facebook Girl', 3, NOW()),
('Raise Your Dongers', 3, NOW()),
('Successful Black Man', 5, NOW()),
('Bear Grylls / Better Drink My Own Piss', 4, NOW()),
('Fight Club: 5/7 Movie', 5, NOW()),
('друг', 3, NOW()),
('Reaction Images', 2, NOW()),
('I Hope Senpai Will Notice Me', 1, NOW()),
('Cereal Guy', 4, NOW()),
('Serbia Strong / Remove Kebab', 3, NOW()),
('High Expectations Asian Father', 4, NOW()),
('PTSD Clarinet Boy', 2, NOW()),
('Homophobic Seal', 4, NOW()),
('Fus Ro Dah', 4, NOW()),
('Zalgo', 3, NOW()),
('Aww Yea Guy', 2, NOW()),
('Copypasta', 5, NOW()),
('Futurama Fry / Not Sure If', 2, NOW()),
('I Sexually Identify as an Attack Helicopter', 1, NOW()),
('Are You Serious Face / Seriously?', 4, NOW()),
('One Does Not Simply Walk into Mordor', 4, NOW()),
('Gangnam Style', 1, NOW()),
('Cool Story, Bro', 2, NOW()),
('True Story', 2, NOW()),
('Sweet Brown / Ain''t Nobody Got Time for That', 4, NOW()),
('Darude - Sandstorm', 4, NOW()),
('Creepypasta', 2, NOW()),
('Fuck Her Right in the Pussy / FHRITP', 2, NOW()),
('Based God', 3, NOW()),
('All the Things', 4, NOW()),
('Kek', 1, NOW()),
('Meatspin', 5, NOW()),
('Waifu', 3, NOW()),
('Belle Delphine', 5, NOW()),
('Facepalm', 5, NOW()),
('If You Know What I Mean', 4, NOW()),
('Bye Felicia', 3, NOW()),
('Emergence (Metamorphosis)', 3, NOW()),
('Hide The Pain Harold', 2, NOW()),
('Rule 63', 3, NOW()),
('I Know That Feel Bro', 2, NOW()),
('Cash Me Ousside / Howbow Dah', 2, NOW()),
('Deal With It', 3, NOW()),
('Momo Challenge', 1, NOW()),
('Socially Awkward Penguin', 2, NOW()),
('Nope! Chuck Testa', 3, NOW()),
('To Be Fair, You Have To Have a Very High IQ to Understand Rick and Morty', 5, NOW()),
('First World Problems', 2, NOW()),
('Fap', 4, NOW()),
('That Really Rustled My Jimmies', 1, NOW()),
('Moon Moon', 4, NOW()),
('The Most Interesting Man in the World', 5, NOW()),
('Dank Memes', 5, NOW()),
('Challenge Accepted', 3, NOW()),
('Xzibit Yo Dawg', 4, NOW()),
('Ayy LMAO', 5, NOW()),
('Grumpy Cat', 1, NOW()),
('Nyan Cat', 2, NOW()),
('''Dat Ass', 5, NOW()),
('Boxxy', 3, NOW()),
('2 Girls 1 Cup', 2, NOW()),
('Mr. Hands', 1, NOW()),
('Joseph Ducreux / Archaic Rap', 1, NOW()),
('Harlem Shake', 1, NOW()),
('Oh Crap / OMG Rage Face', 5, NOW()),
('Shrek Is Love, Shrek Is Life', 3, NOW()),
('Delete System32', 1, NOW()),
('Musically Oblivious 8th Grader', 2, NOW()),
('2/10 Would Not Bang', 5, NOW()),
('Insanity Wolf', 2, NOW()),
('Mocking SpongeBob', 4, NOW()),
('Success Kid / I Hate Sandcastles', 2, NOW()),
('JoJo''s Bizarre Adventure', 3, NOW()),
('The Tragedy of Darth Plagueis The Wise', 2, NOW()),
('What People Think I Do / What I Really Do', 2, NOW()),
('Rebecca Black - Friday', 3, NOW()),
('Tide POD Challenge', 2, NOW()),
('Look At All The Fucks I Give', 2, NOW()),
('U WOT M8', 4, NOW()),
('Tubgirl', 3, NOW()),
('Smile.jpg', 2, NOW()),
('Dafuq', 3, NOW()),
('Yaranaika? (やらないか)', 2, NOW()),
('The Fappening / Celebgate', 3, NOW()),
('That''s Racist!', 4, NOW()),
('Genius', 5, NOW()),
('I See What You Did There', 5, NOW()),
('Roll Safe', 3, NOW()),
('Rape Sloth', 3, NOW()),
('PewDiePie', 4, NOW()),
('Weird Flex But Ok', 3, NOW()),
('My Body Is Ready', 1, NOW()),
('Billy Herrington / Gachimuchi', 2, NOW()),
('Don''t Talk To Me Or My Son Ever Again', 2, NOW()),
('Disaster Girl', 3, NOW()),
('Cheeki Breeki', 1, NOW()),
('That Escalated Quickly', 5, NOW()),
('Son, I Am Disappoint', 5, NOW()),
('Nyannyancosplay / Hit or Miss', 3, NOW()),
('Jet Fuel Can''t Melt Steel Beams', 4, NOW()),
('Your Argument Is Invalid', 5, NOW()),
('B Button Emoji 🅱', 5, NOW()),
('Chubby Bubbles Girl', 3, NOW()),
('Miley Cyrus Sex Tape Facebook Scams', 1, NOW()),
('Homestuck', 2, NOW()),
('This Is So Sad Alexa Play Despacito', 3, NOW()),
('Majora''s Mask Creepypasta (BEN DROWNED)', 1, NOW()),
('Sweet Jesus Face', 2, NOW()),
('Come At Me Bro', 5, NOW()),
('Inglip', 5, NOW()),
('Swag', 2, NOW()),
('I Have No Idea What I''m Doing', 1, NOW()),
('Shut Up And Take My Money!', 2, NOW()),
('Neil deGrasse Tyson Reaction', 2, NOW()),
('"Y U NO" Guy', 4, NOW()),
('Rule 34', 5, NOW()),
('Overly Attached Girlfriend', 2, NOW()),
('Scumbag Steve', 2, NOW()),
('I Took an Arrow in the Knee', 1, NOW()),
('Rules of the Internet', 2, NOW()),
('You Don''t Say?', 1, NOW()),
('The Mandela Effect', 4, NOW()),
('Woman Yelling at a Cat', 2, NOW()),
('Good Guy Greg', 2, NOW()),
('ಠ_ಠ Look of Disapproval', 1, NOW()),
('Pepe the Frog', 5, NOW()),
('Ridiculously Photogenic Guy', 3, NOW()),
('Ancient Aliens', 1, NOW()),
('Has Anyone Really Been Far Even as Decided to Use Even Go Want to do Look More Like?', 5, NOW()),
('Slender Man', 2, NOW()),
('Doge', 1, NOW()),
('( ͡° ͜ʖ ͡°) / Lenny Face', 1, NOW()),
('Navy Seal Copypasta', 2, NOW()),
('Forever Alone', 4, NOW()),
('Zerg Rush', 2, NOW()),
('Trollface', 3, NOW()),
('My Little Pony: Friendship is Magic', 4, NOW()),
('Me Gusta', 5, NOW()),
('Do A Barrel Roll', 5, NOW()),
('Flipping Tables / (╯°□°）╯︵ ┻━┻', 2, NOW()),
('Ermahgerd', 4, NOW()),
('Loss', 2, NOW()),
('Dolan', 4, NOW()),
('Ugandan Knuckles', 4, NOW()),
('Yao Ming Face / Bitch Please', 1, NOW()),
('Duck Face', 3, NOW()),
('Boku no Pico', 2, NOW()),
('Senor Chang''s "Ha, Gay!"', 2, NOW()),
('Rickroll', 5, NOW()),
('Bowsette', 3, NOW()),
('Poker Face', 3, NOW()),
('And Not a Single Fuck Was Given That Day', 3, NOW()),
('Twitch Plays Pokemon', 3, NOW()),
('Desu', 3, NOW()),
('What Are Those?', 3, NOW()),
('TheLegend27', 5, NOW()),
('Karen', 5, NOW()),
('Keep Calm and Carry On', 5, NOW()),
('Katy t3h PeNgU1N oF d00m', 2, NOW()),
('Oh God Why', 2, NOW()),
('Polandball', 4, NOW()),
('Ahegaokin - アヘ顔菌', 4, NOW()),
('Slowpoke', 2, NOW()),
('Stonks', 5, NOW()),
('Instagram Quote Rebuttals / Hipster Edits', 3, NOW()),
('Shock Sites', 1, NOW()),
('Shoop Da Whoop', 4, NOW()),
('I Can Count to Potato', 2, NOW()),
('Spaghetti Stories', 3, NOW()),
('Advice Dog', 5, NOW()),
('420 Blaze It', 5, NOW()),
('James Doakes'' "Surprise Motherfucker"', 1, NOW()),
('Business Cat', 3, NOW()),
('Trolling', 5, NOW()),
('Side Eyeing Chloe', 5, NOW()),
('Tendies Stories', 3, NOW()),
('What Is This I Don''t Even', 2, NOW()),
('I''m Twelve Years Old and What is This?', 2, NOW()),
('This Is Fine', 3, NOW()),
('The Narwhal Bacons at Midnight', 4, NOW()),
('Mother of God', 2, NOW()),
('''Murica', 1, NOW()),
('I Came', 4, NOW()),
('ME!ME!ME!', 5, NOW()),
('Draw Me Like One of Your French Girls', 1, NOW()),
('Virgin vs. Chad', 2, NOW()),
('Ahegao', 5, NOW()),
('Are You A Wizard', 5, NOW()),
('Feels', 1, NOW()),
('Pokémon', 5, NOW()),
('Strutting Leo', 4, NOW()),
('Troll Science / Troll Physics', 5, NOW()),
('Sanic Hegehog', 4, NOW()),
('Kekistan', 2, NOW()),
('Mom''s Spaghetti', 2, NOW()),
('I Lied', 2, NOW()),
('Freddie Mercury Rage Pose', 2, NOW()),
('Conspiracy Keanu', 1, NOW()),
('Five Nights at Freddy''s', 1, NOW()),
('Indestructible Nokia 3310', 4, NOW()),
('Distracted Boyfriend', 4, NOW()),
('Piper Perri Surrounded', 3, NOW()),
('Shadman / Shadbase', 1, NOW()),
('LOL Guy', 4, NOW()),
('It''s A Trap!', 1, NOW()),
('Staredad', 3, NOW()),
('Feels Good Man', 3, NOW()),
('ZONE-sama', 1, NOW()),
('Me and the Boys', 4, NOW()),
('Trap', 1, NOW()),
('Confused Black Girl', 5, NOW()),
('WE WUZ KINGS', 4, NOW()),
('Ryan Gosling', 4, NOW()),
('Notices Bulge / OwO What''s This?', 5, NOW()),
('???? PROFIT!!!!', 4, NOW()),
('30-Year-Old Boomer', 4, NOW()),
('Galaxy Brain', 4, NOW()),
('Idiot Nerd Girl', 1, NOW()),
('Pool''s Closed', 4, NOW()),
('Kony 2012', 2, NOW()),
('Video 1444', 1, NOW()),
('Pepega', 3, NOW()),
('Huahuehuahue', 1, NOW()),
('O RLY?', 2, NOW()),
('Feel Like a Sir', 2, NOW()),
('Absolute Unit', 3, NOW()),
('An Hero', 5, NOW()),
('SOON', 1, NOW()),
('Stahp', 5, NOW()),
('Weeaboo', 3, NOW()),
('The Cake Is a Lie', 2, NOW()),
('Lord Marquaad E', 5, NOW()),
('"Miracles" / Fucking Magnets, How Do They Work?', 2, NOW()),
('THEN WHO WAS PHONE?', 2, NOW()),
('Work-Safe Porn', 1, NOW()),
('Logan Paul''s Suicide Forest Video', 2, NOW()),
('Yes, This is Dog', 1, NOW()),
('Chris-Chan / CWC / Christian Weston Chandler', 4, NOW()),
('REEEEEEE', 5, NOW()),
('Honey Badger', 3, NOW()),
('Tree Fiddy', 2, NOW()),
('Greentext Stories', 3, NOW()),
('Minecraft Creeper', 1, NOW()),
('Surprised Pikachu', 1, NOW()),
('Big Smoke''s Order', 3, NOW()),
('College Freshman', 4, NOW()),
('All Your Base Are Belong to Us', 1, NOW()),
('Like A Boss', 3, NOW()),
('Jeff the Killer', 1, NOW()),
('I Herd U Liek Mudkips', 1, NOW()),
('Thicc', 4, NOW()),
('Hover Hand', 3, NOW()),
('The Bongcheon-Dong Ghost', 2, NOW()),
('Lavender Town Syndrome Creepypasta', 2, NOW()),
('Foul Bachelor Frog', 1, NOW()),
('John is Kill', 1, NOW()),
('College Liberal', 2, NOW()),
('Impossibru', 4, NOW()),
('I Accidentally', 2, NOW()),
('U MAD?', 4, NOW()),
('It''s Over 9000!', 5, NOW()),
('Ligma', 5, NOW()),
('Newfags Can''t Triforce', 3, NOW()),
('He Protec but He Also Attac', 1, NOW()),
('Feels Bad Man / Sad Frog', 2, NOW()),
('Are You Fucking Kidding Me?', 5, NOW()),
('Leeroy Jenkins', 2, NOW()),
('I Don''t Want to Live on This Planet Anymore', 2, NOW()),
('Courage Wolf', 1, NOW()),
('Cinnamon Challenge', 5, NOW()),
('But That''s None of My Business', 1, NOW()),
('Goatse', 3, NOW()),
('4chan', 1, NOW()),
('241543903 / Heads In Freezers', 1, NOW()),
('Half-Life 3 Confirmed', 4, NOW()),
('Antoine Dodson / Bed Intruder', 5, NOW()),
('9GAG', 4, NOW()),
('Bobs and Vegana', 1, NOW()),
('The Circle Game', 2, NOW()),
('Is This a Pigeon?', 3, NOW()),
('Good Luck, I''m Behind 7 Proxies', 3, NOW()),
('FAIL / Epic Fail', 2, NOW()),
('Hey Girls, Did You Know...', 5, NOW()),
('Virgin-Killing Sweater', 4, NOW()),
('NPC Wojak', 3, NOW()),
('Deez Nuts', 4, NOW()),
('Handsome Face', 1, NOW()),
('Reaction Guys / Gaijin 4Koma', 2, NOW()),
('In Soviet Russia...', 5, NOW()),
('Scumbag Stacy', 1, NOW()),
('Moth Lamp', 1, NOW()),
('OK Symbol 👌', 1, NOW()),
('Cuck', 1, NOW()),
('Lazy College Senior', 1, NOW()),
('T-Pose', 3, NOW()),
('Filthy Frank', 3, NOW()),
('My Brain is Full of Fuck', 1, NOW()),
('Third World Success', 1, NOW()),
('Rain Drop Drop Top', 3, NOW()),
('Scarlett Johansson Leaked Nudes', 3, NOW()),
('Hugh Mungus', 3, NOW()),
('Hentai Quotes', 4, NOW()),
('Trigger', 2, NOW()),
('Technoviking', 5, NOW()),
('YOLO', 5, NOW()),
('They Don''t Think It Be Like It Is But It Do', 5, NOW()),
('I Came Out to Have a Good Time and I''m Honestly Feeling So Attacked Right Now', 1, NOW()),
('Condescending Wonka / Creepy Wonka', 1, NOW()),
('Trash Doves', 2, NOW()),
('Wojak / Feels Guy', 1, NOW()),
('Electric Boogaloo', 3, NOW()),
('*Tips Fedora*', 3, NOW()),
('I''m Already Tracer', 4, NOW()),
('Epic Sax Guy', 2, NOW()),
('Yes - Roundabout / To Be Continued', 2, NOW()),
('How Is Babby Formed?', 4, NOW()),
('POMF =3', 5, NOW()),
('Some Men Just Want to Watch the World Burn', 4, NOW()),
('Minecraft', 1, NOW()),
('Honey Boo Boo Child', 3, NOW()),
('I Dunno LOL ¯\(°_o)/¯', 2, NOW()),
('Spider-Man Pointing at Spider-Man', 4, NOW()),
('Zyzz', 4, NOW()),
('Wood Sitting on a Bed', 2, NOW()),
('X, X Everywhere', 3, NOW()),
('Clown Pepe / Honk Honk / Clown World', 2, NOW()),
('Computer Reaction Faces', 2, NOW()),
('Git Gud', 1, NOW()),
('He-Man Sings / HEYYEYAAEYAAAEYAEYAA', 5, NOW()),
('Ultra Instinct Shaggy', 2, NOW()),
('Za Warudo / WRYYYYY', 5, NOW()),
('Ruined Childhood', 1, NOW()),
('fsjal', 5, NOW()),
('Giovanna Plowman / Tampon Girl', 3, NOW()),
('Steven Crowder''s "Change My Mind" Campus Sign', 4, NOW()),
('Tumblr', 5, NOW()),
('Jesus is a Jerk', 5, NOW()),
('Wombo Combo', 2, NOW()),
('Yee', 5, NOW()),
('This Kills The Crab', 4, NOW()),
('BME Pain Olympics', 1, NOW()),
('Crying Cat', 2, NOW()),
('Trypophobia', 2, NOW()),
('Brent Rambo', 3, NOW()),
('Tenso', 5, NOW()),
('Duwang', 3, NOW()),
('Johny Johny Yes Papa', 1, NOW()),
('Thot', 3, NOW()),
('Butthurt Dweller / Gordo Granudo', 3, NOW()),
('Didn''t Read LOL', 4, NOW()),
('Russian Sleep Experiment', 3, NOW()),
('Trigglypuff', 4, NOW()),
('Puking Rainbows', 3, NOW()),
('Coldsteel The Hedgeheg', 3, NOW()),
('Moon Man', 3, NOW()),
('Wingboner & Clopping', 2, NOW()),
('Sharkeisha Fight Video', 2, NOW()),
('In This Moment I Am Euphoric', 1, NOW()),
('This Isn''t Even My Final Form', 4, NOW()),
('Dashcon', 3, NOW()),
('Vivian James', 4, NOW()),
('Squidward''s Suicide', 2, NOW()),
('Hail Hydra', 5, NOW()),
('Mormon Porn / Bubble Porn', 4, NOW()),
('Vengeance Dad', 4, NOW()),
('Everybody Walk the Dinosaur', 1, NOW()),
('Puts On Sunglasses / YEEEEAAAHHH', 5, NOW()),
('Casually Pepper Spray Everything Cop', 3, NOW()),
('The Dab', 1, NOW()),
('Carl!', 3, NOW()),
('You Must Construct Additional Pylons!', 2, NOW()),
('Expand Dong', 4, NOW()),
('1 Guy 1 Jar', 2, NOW()),
('PROTIP', 1, NOW()),
('Longcat', 5, NOW()),
('Thanks, Obama!', 2, NOW()),
('Shooting Stars', 4, NOW()),
('Ash Pedreiro / Dat Ash', 2, NOW()),
('Awesome Face / Epic Smiley', 1, NOW()),
('My Immortal / The Worst Fanfiction Ever', 2, NOW()),
('Almost Politically Correct Redneck', 3, NOW()),
('Overly Manly Man', 2, NOW()),
('Natalia Poklonskaya', 3, NOW()),
('Coomer', 5, NOW()),
('CSI 4 Pane Comics', 2, NOW()),
('Skull Trumpet / Doot Doot', 5, NOW()),
('SpongeGar / Primitive Sponge / Caveman Spongebob', 3, NOW()),
('Confused Nick Young', 1, NOW()),
('Gamer Joker / Gamers Rise Up / We Live in a Society', 1, NOW()),
('Prepare Your Anus', 3, NOW()),
('Creepy Chan (Allison Harvard)', 1, NOW()),
('Nothing To Do Here / Jet Pack Guy', 3, NOW()),
('Pretty Cool Guy', 2, NOW()),
('Zoë Quinn', 3, NOW()),
('Mr. Bones'' Wild Ride', 1, NOW()),
('Hitler''s "Downfall" Parodies', 5, NOW()),
('Divide By Zero', 1, NOW()),
('48÷2(9+3) = ?', 3, NOW()),
('Baneposting', 2, NOW()),
('The Grifter', 5, NOW()),
('Unexpected John Cena / And His Name is John Cena', 2, NOW()),
('Check Your Privilege', 2, NOW()),
('It Is Wednesday My Dudes', 3, NOW()),
('We Live In a Society Social Media Reactions', 5, NOW()),
('Friendship Ended With Mudasir', 3, NOW()),
('Neckbeard', 5, NOW()),
('tl;dr', 4, NOW()),
('Trololo Guy', 2, NOW()),
('Hentai Woody / 変態ウッディー', 2, NOW()),
('Cupcakes', 3, NOW()),
('OP is a Faggot', 3, NOW()),
('Cats', 3, NOW()),
('Super Smash Brothers', 4, NOW()),
('Earth-chan', 1, NOW()),
('Derpy Hooves', 3, NOW()),
('Unhelpful High School Teacher', 5, NOW()),
('Nicolas Cage', 1, NOW()),
('Dubs Guy / “Check ’Em”', 5, NOW()),
('Burger King Foot Lettuce', 5, NOW()),
('Brian Peppers', 2, NOW()),
('Arthur''s Fist', 1, NOW()),
('Horse Head Mask', 2, NOW()),
('Deus Vult', 3, NOW()),
('Smudge the Cat', 2, NOW()),
('You Know Nothing, Jon Snow', 3, NOW()),
('The Rake', 3, NOW()),
('Herobrine', 3, NOW()),
('Salt Bae', 3, NOW()),
('Horrifying House-guest / Shadowlurker', 1, NOW()),
('Caught Me Sleeping / Bae Caught Me Slippin', 4, NOW()),
('Math Lady / Confused Lady', 4, NOW()),
('KEKW', 4, NOW()),
('Shitposting', 2, NOW()),
('Warlizard Gaming Forum', 4, NOW()),
('It Was Me, Dio!', 3, NOW()),
('Blue Waffle', 5, NOW()),
('Memes', 1, NOW()),
('Super S Stussy', 5, NOW()),
('Reddit', 4, NOW()),
('Guile''s Theme Goes with Everything', 5, NOW()),
('Alternate Universe', 4, NOW()),
('Yoshi Committed Tax Fraud', 1, NOW()),
('Somebody Toucha My Spaghet', 1, NOW()),
('Bone Hurting Juice', 5, NOW()),
('Why Not Both? / Why Don''t We Have Both?', 4, NOW()),
('Nope.avi', 1, NOW()),
('Steven Universe', 3, NOW()),
('Cave Johnson / Combustible Lemons', 5, NOW()),
('Kanye Interrupts / Imma Let You Finish', 5, NOW()),
('*Record Scratch* *Freeze Frame*', 4, NOW()),
('Old Gregg', 3, NOW()),
('I, For One, Welcome Our New Insect Overlords', 2, NOW()),
('Goodnight Sweet Prince', 2, NOW()),
('Padoru', 4, NOW()),
('"Anime Was a Mistake"', 2, NOW()),
('>Shadman', 1, NOW()),
('Finger Boxes', 4, NOW()),
('Feeling Cute, Might Delete Later', 2, NOW()),
('Peachette / Super Crown', 4, NOW()),
('Imminent Ned / Brace Yourselves, Winter is Coming', 5, NOW()),
('Trollestia / Molestia / Tyrant Celestia', 5, NOW()),
('Seems Legit / Sounds Legit', 3, NOW()),
('Potato Jesus', 3, NOW()),
('*Teleports Behind You* Nothing Personal, Kid', 3, NOW()),
('McKayla is Not Impressed', 5, NOW()),
('Now Kiss!', 4, NOW()),
('Donde Esta La Biblioteca / Spanish Rap', 2, NOW()),
('Candle Cove', 2, NOW()),
('The Glorious PC Gaming Master Race', 1, NOW()),
('The Dress / What Color Is This Dress?', 2, NOW()),
('Waffles? Don''t You Mean Carrots?', 4, NOW()),
('Karate Kyle', 4, NOW()),
('Spoderman / Spodermen', 5, NOW()),
('Steamed Hams', 2, NOW()),
('Too Much Water', 1, NOW()),
('Slaps Roof of Car', 3, NOW()),
('Bitches Love Smiley Faces', 4, NOW()),
('Phteven / Tuna the Dog', 1, NOW()),
('Sudden Clarity Clarence', 5, NOW()),
('The Backrooms', 5, NOW()),
('Mereana Mordegard Glesgorv', 1, NOW()),
('Dear Sister Parodies / "Mmm Whatcha'' Say"', 5, NOW()),
('Tourette''s Guy', 1, NOW()),
('Begone, Thot', 1, NOW()),
('A Cat Is Fine Too', 4, NOW()),
('There Are No Girls on the Internet', 2, NOW()),
('Go Home, You Are Drunk', 1, NOW()),
('Pawn Stars', 1, NOW()),
('Spoopy', 1, NOW()),
('Gotta Go Fast', 1, NOW()),
('Kill Yourself', 1, NOW()),
('Banana For Scale', 4, NOW()),
('My Parents Are Dead / Batman Slapping Robin', 1, NOW()),
('uwu', 1, NOW()),
('Gary Oak', 1, NOW()),
('The Main Difference Between Europe and USA', 3, NOW()),
('9 + 10 = 21', 4, NOW()),
('Shit Was So Cash', 4, NOW()),
('Name Puns', 4, NOW()),
('Wonderwall', 3, NOW()),
('Pokeparents / Pokedads', 4, NOW()),
('THE GAME', 3, NOW()),
('Chad Thundercock', 2, NOW()),
('Eyebrows on Fleek', 1, NOW()),
('Weegee', 2, NOW()),
('Montage Parodies', 1, NOW()),
('Actual Advice Mallard', 1, NOW()),
('Inception', 2, NOW()),
('You''re Doing It Wrong', 3, NOW()),
('This Looks Shopped', 2, NOW()),
('Advice Animals', 3, NOW()),
('He Will Not Divide Us', 3, NOW()),
('Close Enough', 1, NOW()),
('"This Is the Ideal Male Body"', 4, NOW()),
('Battletoads Pre-order', 5, NOW()),
('Boardroom Suggestion', 2, NOW()),
('Cocaine Bear', 3, NOW()),
('Carl the Cuck and AIDS Skrillex', 5, NOW()),
('Oh, You', 4, NOW()),
('Epic Beard Man', 2, NOW()),
('Everything Went Better Than Expected', 2, NOW()),
('Ah Shit, Here We Go Again', 4, NOW()),
('Limes Guy / Why Can''t I Hold All These Limes?', 1, NOW()),
('"Mitochondria is the Powerhouse of the Cell"', 2, NOW()),
('Normie', 3, NOW()),
('Alt + F4', 5, NOW()),
('Download More RAM', 3, NOW()),
('Confused Travolta', 2, NOW()),
('Troll Quotes', 4, NOW()),
('Nigel Thornberry Remixes', 1, NOW()),
('Hipster Mermaid / Hipster Ariel', 4, NOW()),
('My Name Is Jeff', 2, NOW()),
('Daily Dose / Piccolo Dick', 4, NOW()),
('X Grab My Y', 3, NOW()),
('Cory in the House', 5, NOW()),
('Doomer', 3, NOW()),
('Zangief Kid', 4, NOW()),
('Descriptive Noise', 1, NOW()),
('Jebaited', 4, NOW()),
('How Can She Slap?', 5, NOW()),
('Cracking Open a Cold One With the Boys', 4, NOW()),
('Release The Kraken!', 2, NOW()),
('What Has Been Seen Cannot Be Unseen', 1, NOW()),
('Nobody:', 4, NOW()),
('Yeah Science, Bitch', 4, NOW()),
('Diabeetus', 4, NOW()),
('Cake Farts', 3, NOW()),
('Ted Cruz Zodiac Killer', 2, NOW()),
('Anti-Joke Chicken', 2, NOW()),
('spritecranberry.net', 5, NOW()),
('Pacha Edits / When The Sun Hits That Ridge Just Right', 1, NOW()),
('Sonic.exe', 1, NOW()),
('That''s What She Said', 4, NOW()),
('Bee Movie Script / According To All Known Laws Of Aviation', 1, NOW()),
('JonTron', 2, NOW()),
('Girls Laughing', 3, NOW()),
('YouTube Poop / YTP', 5, NOW()),
('It''s Something', 3, NOW()),
('U Jelly?', 2, NOW()),
('Trolldad', 4, NOW()),
('Gabe Newell', 5, NOW()),
('Wololo', 1, NOW()),
('Stefán Karl Stefánsson / Robbie Rotten', 3, NOW()),
('Dragon Dildos', 5, NOW()),
('PINGAS', 4, NOW()),
('Oh Stop It, You', 2, NOW()),
('This Ain''t It, Chief', 4, NOW()),
('Who''s Getting the Best Head?', 4, NOW()),
('Feels Good', 1, NOW()),
('Sam Hyde', 3, NOW()),
('What in Tarnation', 1, NOW()),
('This Nigga Eating Beans', 1, NOW()),
('We Are Number One', 2, NOW()),
('Happy Merchant', 1, NOW()),
('Netflix and Chill', 1, NOW()),
('Right In Front Of My Salad', 4, NOW()),
('You Keep Using That Word, I Do Not Think It Means What You Think It Means', 1, NOW()),
('Om Nom Nom Nom', 4, NOW()),
('The Rock Driving', 1, NOW()),
('RIP in Peace', 3, NOW()),
('SCP Foundation', 1, NOW()),
('Hipster Kitty', 4, NOW()),
('What''s All This Racket? / Mirada Fija', 1, NOW()),
('BORN TO DIE / WORLD IS A FUCK / Kill Em All 1989 / I am trash man / 410,757,864,530 DEAD COPS', 3, NOW()),
('Bepis', 2, NOW()),
('Why Do Slavs Squat? / Slav Squat', 3, NOW()),
('Ken Bone', 4, NOW()),
('Team Fortress 2', 5, NOW()),
('Butthurt', 5, NOW()),
('It''s Free Real Estate', 5, NOW()),
('Tits or GTFO', 2, NOW()),
('Cult of Kek', 3, NOW()),
('Gabe the Dog / Bork Remixes', 2, NOW()),
('Forced to Drink Milk', 4, NOW()),
('Meme Man', 3, NOW()),
('Interior Semiotics', 2, NOW()),
('YouTube', 5, NOW()),
('Rekt', 1, NOW()),
('I Put on My Robe and Wizard Hat', 1, NOW()),
('Thai Political Crisis Breakup', 3, NOW()),
('Furries', 5, NOW()),
('The Wadsworth Constant', 3, NOW()),
('Bogdanoff Twins', 1, NOW()),
('Do Want / Do Not Want', 4, NOW()),
('Brendan Fraser''s Alimony / Just Fuck My Shit Up', 5, NOW()),
('Actual Cannibal Shia LaBeouf', 5, NOW()),
('Ah, I See You''re a Man of Culture As Well', 5, NOW()),
('RWBY', 1, NOW()),
('It''s Dangerous to Go Alone! Take This', 3, NOW()),
('Double Rainbow', 2, NOW()),
('You Just Activated My Trap Card!', 3, NOW()),
('Oh Fuck Yeah Spread It', 5, NOW()),
('Adalia Rose', 3, NOW()),
('Dark Souls', 4, NOW()),
('Guys Literally Only Want One Thing And It''s Fucking Disgusting', 4, NOW()),
('Zuckerberg Note Pass', 4, NOW()),
('Asians in the Library', 4, NOW()),
('Conceited Reaction', 4, NOW()),
('Undertale', 2, NOW()),
('Ben Swolo', 3, NOW()),
('This Is Why We Can''t Have Nice Things', 3, NOW()),
('Bee Movie', 2, NOW()),
('Ted the Caver', 2, NOW()),
('Give Her The Dick', 5, NOW()),
('Why Are We Still Here? Just To Suffer?', 3, NOW()),
('Boruto''s Dad', 2, NOW()),
('Suh Dude', 5, NOW()),
('The Casting Couch', 4, NOW()),
('Soy Boy', 1, NOW()),
('Deep Fried Memes', 4, NOW()),
('They Told Me I Could Be Anything I Wanted', 3, NOW()),
('Wew Lad', 1, NOW()),
('Put Your Finger Here', 2, NOW()),
('Gaben', 3, NOW()),
('Internet Husband', 5, NOW()),
('Did He Died?', 4, NOW()),
('Rare Pepe', 3, NOW()),
('The Song of My People!', 4, NOW()),
('Ladies and Gentlemen, We Got Him', 5, NOW()),
('Justin Bieber', 2, NOW()),
('SO HARDCORE', 5, NOW()),
('Shit Tyrone, Get It Together', 1, NOW()),
('Chonk / Oh Lawd He Comin''', 5, NOW()),
('Le Monke / Uh Oh Stinky', 2, NOW()),
('Costanza.jpg / George Costanza Reaction Face', 1, NOW()),
('"I Saw Flying Lotus in a Grocery Store..." Copypasta', 2, NOW()),
('Does Bruno Mars Is Gay?', 4, NOW()),
('Daquan', 5, NOW()),
('Pokémon Creepy Black', 5, NOW()),
('Ebola-chan', 2, NOW()),
('Katawa Shoujo', 4, NOW()),
('Candlejack', 1, NOW()),
('They''re Good Dogs Brent', 5, NOW()),
('Kreygasm', 5, NOW()),
('Three Wolf Moon', 3, NOW()),
('Dating Site Murderer', 2, NOW()),
('Supa Hot Fire', 1, NOW()),
('Full Retard', 4, NOW()),
('"It''s Gonna Be May"', 1, NOW()),
('Futurama Zoidberg / Why Not Zoidberg?', 1, NOW()),
('Yeet', 3, NOW()),
('Skeleton War', 5, NOW()),
('Gonna Cry? Gonna Piss Your Pants Maybe?', 2, NOW()),
('I''m Here To Kick Ass And Chew Bubblegum', 4, NOW()),
('Edgy', 4, NOW()),
('2Spooky', 1, NOW()),
('Dindu Nuffin', 3, NOW()),
('No Fap September / No Fap Months', 3, NOW()),
('Aesthetic', 2, NOW()),
('Make Me a Sandwich', 5, NOW()),
('Chemistry Cat', 4, NOW()),
('Ainsley Harriott', 3, NOW()),
('Soy Boy Face', 5, NOW()),
('I Like Turtles', 3, NOW()),
('Dog Fort', 1, NOW()),
('SpongeBob SquarePants', 4, NOW()),
('JoJo''s Pose', 3, NOW()),
('Crying Michael Jordan', 2, NOW()),
('Doom Paul / It''s Happening', 3, NOW()),
('PogChamp', 2, NOW()),
('hunter2', 4, NOW()),
('Oh Fuck, Put It Back In', 3, NOW()),
('Whomst', 1, NOW()),
('This Man (Ever Dream This Man)', 1, NOW()),
('Agar.io', 1, NOW()),
('The Undertaker Threw Mankind Off Hell in a Cell', 2, NOW()),
('Suicide Mouse', 5, NOW()),
('People Die If They Are Killed', 3, NOW()),
('I Should Buy a Boat Cat', 3, NOW()),
('Amber Lamps', 2, NOW()),
('My Faggot Dog', 4, NOW()),
('Keemstar', 4, NOW()),
('Fukouna Shoujo 03', 1, NOW()),
('Damn Daniel', 1, NOW()),
('Overwatch', 5, NOW()),
('Dub the Dew', 3, NOW()),
('Kill It With Fire', 1, NOW()),
('Instructions Unclear', 5, NOW()),
('Black Guy on the Phone', 4, NOW()),
('Adventure Time', 4, NOW()),
('Sheltered College Freshman', 1, NOW()),
('Didney Worl', 4, NOW()),
('Bruh', 3, NOW()),
('It''s So Fucking Big', 4, NOW()),
('8chan / 8kun', 2, NOW()),
('iPhone Whale', 1, NOW()),
('This Is Sparta!', 5, NOW()),
('My Name Is Yoshikage Kira', 2, NOW()),
('Is This a JoJo Reference?', 3, NOW()),
('Aww Yiss', 1, NOW()),
('Succ', 2, NOW()),
('Persian Cat Room Guardian', 1, NOW()),
('Ight Imma Head Out', 3, NOW()),
('GachiGASM / GachiBASS', 3, NOW()),
('Emoticons', 5, NOW()),
('Cats Wanting Fruit Loops', 4, NOW()),
('Eggplant Emoji 🍆', 5, NOW()),
('Dummy Thicc', 5, NOW()),
('You''ve Been Gnomed', 3, NOW()),
('Drake The Type Of...', 1, NOW()),
('Ramirez, Do Everything!', 1, NOW()),
('ROFLcopter', 1, NOW()),
('Florida Man', 4, NOW()),
('Fap Guy', 4, NOW()),
('LOLWUT', 5, NOW()),
('Understandable, Have a Nice Day', 3, NOW()),
('Crab Rave', 5, NOW()),
('What You Think You Look Like vs. What You Actually Look Like', 5, NOW()),
('OK Boomer', 5, NOW()),
('Pokéfusion / Pokémon Fusion', 3, NOW()),
('INB4', 4, NOW()),
('Emo Dad', 1, NOW()),
('FrankerZ', 2, NOW()),
('Godwin''s Law', 3, NOW()),
('Hello Darkness, My Old Friend', 2, NOW()),
('[Intensifies]', 1, NOW()),
('Snowclone', 1, NOW()),
('3 Guys 1 Hammer', 1, NOW()),
('MULTI-TRACK DRIFTING', 1, NOW()),
('Impact', 3, NOW()),
('Brother, May I Have Some Oats', 2, NOW()),
('Menacing / ゴゴゴゴ', 2, NOW()),
('Demotivational Posters', 4, NOW()),
('I Have The Weirdest Boner', 5, NOW()),
('You Had One Job', 4, NOW()),
('Doki Doki Literature Club', 2, NOW()),
('Oh? You''re Approaching Me? / JoJo Approach', 3, NOW()),
('Harp Darp / Herp Derp', 3, NOW()),
('Shut Down Everything', 5, NOW()),
('Designated Shitting Streets / Poo in the Loo', 3, NOW()),
('Woll Smoth', 3, NOW()),
('First Day on the Internet Kid', 4, NOW()),
('Wheaton''s Law', 5, NOW()),
('Fedora Shaming', 1, NOW()),
('I Crave That Mineral', 3, NOW()),
('I''m Rick Harrison and This Is My Pawn Shop', 3, NOW()),
('Obedece a la morsa / Obey the walrus', 3, NOW()),
('Confession Bear', 3, NOW()),
('Roof Koreans', 1, NOW()),
('Brother Sharp (犀利哥)', 3, NOW()),
('Grammar Nazi', 2, NOW()),
('Delet This', 4, NOW()),
('I Must Go', 2, NOW()),
('Pokepuns', 4, NOW()),
('Vaporwave', 4, NOW()),
('Tony Kornheiser''s "Why"', 4, NOW()),
('My Face When (MFW) / That Face When (TFW)', 1, NOW()),
('Cringeworthy', 4, NOW()),
('Pepperidge Farm Remembers', 2, NOW()),
('Solaire of Astora', 2, NOW()),
('Kyubey', 5, NOW()),
('Nigga Stole My Bike', 1, NOW()),
('HNNNNNNG', 3, NOW()),
('Coffin Dance / Dancing Pallbearers', 4, NOW()),
('It''s Goofy Time!', 2, NOW()),
('Let''s Get This Bread', 3, NOW()),
('Derpina', 1, NOW()),
('fortniteburger.net', 1, NOW()),
('Crying Laughing Emoji 😂', 4, NOW()),
('Loli-chan', 2, NOW()),
('Hipster Barista', 1, NOW()),
('Friend Zone', 2, NOW()),
('Marauder Shields', 3, NOW()),
('Falcon Punch', 2, NOW()),
('"Tunak Tunak Tun" Dance', 2, NOW()),
('The Illuminati', 1, NOW()),
('You Gonna Get Raped', 5, NOW()),
('Destroy Dick December', 4, NOW()),
('I Will Survive', 1, NOW()),
('Increasingly Verbose Memes', 4, NOW()),
('Gnome Child', 1, NOW()),
('Thanos Car', 2, NOW()),
('I Didn''t Choose The Thug Life, The Thug Life Chose Me', 2, NOW()),
('Exploitables', 3, NOW()),
('Autonomous Sensory Meridian Response (ASMR)', 5, NOW()),
('Luke, I am Your Father', 1, NOW()),
('Gold Membership Trolling', 1, NOW()),
('Matrix Morpheus', 2, NOW()),
('They See Me Rollin''', 3, NOW()),
('Anime / Manga', 5, NOW()),
('Cthulhu', 4, NOW()),
('YTMND', 1, NOW()),
('Face Swap', 1, NOW()),
('I''m The Goddamn Batman', 3, NOW()),
('The Barber', 3, NOW()),
('Hackerman', 4, NOW()),
('Pepe Silvia', 3, NOW()),
('Cole Sprouse''s Tumblr Experiment', 3, NOW()),
('Gremlin D.Va', 4, NOW()),
('Mariah Mallad (Momokun)', 1, NOW()),
('Best Cry Ever', 3, NOW()),
('Shrek', 3, NOW()),
('Goth GF', 4, NOW()),
('Rose / randytaylor69', 4, NOW()),
('League of Legends', 3, NOW()),
('Women Logic', 5, NOW()),
('Queensland Rail Etiquette Posters', 4, NOW()),
('/r9k/', 4, NOW()),
('Do It Faggot', 5, NOW()),
('When I''m Bored', 1, NOW()),
('Dimitri Finds Out', 3, NOW()),
('Disintegration Effect / I Don''t Feel So Good', 2, NOW()),
('Give Pikachu a Face', 4, NOW()),
('Sonic the Hedgehog', 1, NOW()),
('Mesothelioma Ad Copypasta', 4, NOW()),
('2014 Tumblr-4chan Raids', 5, NOW()),
('Amy''s Baking Company PR Scandal', 1, NOW()),
('Donald Trump', 5, NOW()),
('NO U', 1, NOW()),
('Sonichu', 5, NOW()),
('QUALITY', 2, NOW()),
('Lyra Plushie', 3, NOW()),
('*breath in* Boi', 4, NOW()),
('Doggo', 2, NOW()),
('Everything Changed When The Fire Nation Attacked', 1, NOW()),
('Big Man Tyrone', 1, NOW()),
('Autistic Screeching', 4, NOW()),
('Cleganebowl', 4, NOW()),
('When You See it...', 1, NOW()),
('Unflattering Beyonce', 3, NOW()),
('Apply Cold Water To That Burn', 4, NOW()),
('COMBO BREAKER', 4, NOW()),
('Put Shoe on Head', 5, NOW()),
('It Will Be Fun, They Said', 3, NOW()),
('Trumpet Boy', 3, NOW()),
('Blinking White Guy', 2, NOW()),
('TR-8R the Stormtrooper', 2, NOW()),
('QWOP', 3, NOW()),
('Touhou Project (東方Project)', 3, NOW()),
('Anti-Zombie Fortress', 4, NOW()),
('This is Bob', 2, NOW()),
('Planking', 3, NOW()),
('Poot Lovato', 4, NOW()),
('Giga Pudding', 4, NOW()),
('I''m Ethan Bradberry', 4, NOW()),
('Pun Dog', 4, NOW()),
('We''re a Culture, Not a Costume', 4, NOW()),
('Rape Face', 1, NOW()),
('Racists On 4chan', 4, NOW()),
('Ceiling Cat', 5, NOW()),
('"How Do You Do, Fellow Kids?"', 4, NOW()),
('Boonk Gang', 5, NOW()),
('Henlo', 4, NOW()),
('Commit Sudoku', 5, NOW()),
('iDubbbz', 3, NOW()),
('Chocolate Bird', 4, NOW()),
('The Room', 1, NOW()),
('Surprised Patrick', 1, NOW()),
('If It Fits I Sits', 2, NOW()),
('Big Red', 5, NOW()),
('Gentlemen', 4, NOW()),
('Send Nudes', 4, NOW()),
('Pootis', 5, NOW()),
('Dipper Goes To Taco Bell', 2, NOW()),
('Splatoon', 4, NOW()),
('Nuclear Gandhi', 1, NOW()),
('P-P-P-Powerbook!', 5, NOW()),
('+1', 2, NOW()),
('Ameno', 5, NOW()),
('Schrute Facts', 2, NOW()),
('Encyclopedia Dramatica', 5, NOW()),
('Esther Verkest''s Help Sign', 3, NOW()),
('Starter Packs', 1, NOW()),
('Twitter', 1, NOW()),
('Smoke Weed Everyday', 5, NOW()),
('Groyper', 5, NOW()),
('Money Printer Go Brrr', 2, NOW()),
('Thug Life', 2, NOW()),
('Mass Effect 3 Endings Reception', 2, NOW()),
('Pornhub Community Intro', 1, NOW()),
('Fuck The Police', 2, NOW()),
('If Young Metro Don''t Trust You', 4, NOW()),
('Push It Somewhere Else Patrick', 4, NOW()),
('Special Feeling / 特別な気分', 5, NOW()),
('Ed, Edd n Eddy', 3, NOW()),
('Pusheen', 2, NOW()),
('Yaoi Hands', 4, NOW()),
('U.N. Owen Was Her?', 5, NOW()),
('You Are A Pirate', 1, NOW()),
('How Do I Shot Web?', 3, NOW()),
('GiantDad', 1, NOW()),
('Am I a Joke To You?', 4, NOW()),
('Annoyed Picard', 5, NOW()),
('Ellen Baker (New Horizon)', 4, NOW()),
('You So Precious When You Smile', 1, NOW()),
('Cat Breading', 1, NOW()),
('LulzSec Hacks', 5, NOW()),
('Obunga', 3, NOW()),
('Surprise Buttsecks', 1, NOW()),
('Okay, This Is Epic', 1, NOW()),
('Am I the Only One Around Here', 5, NOW()),
('Stop Right There, Criminal Scum', 3, NOW()),
('Buenos Dias, Mandy', 5, NOW()),
('Paul Christoforo Ocean Marketing Emails', 2, NOW()),
('If You Watch X Backwards, It''s About Y', 4, NOW()),
('E3 Sony 2006 / Giant Enemy Crab', 4, NOW()),
('Storm Area 51', 4, NOW()),
('Yare Yare Daze', 4, NOW()),
('This Could Be Us But You Playing', 2, NOW()),
('Paranoid Parrot', 3, NOW()),
('Die Cis Scum', 3, NOW()),
('Evil Kermit', 2, NOW()),
('Breaking Bad Comics', 5, NOW()),
('Nobody Expects The Spanish Inquisition', 3, NOW()),
('WTF Is This Shit!?', 4, NOW()),
('Google Ultron', 3, NOW()),
('Just According to Keikaku', 2, NOW()),
('Unlimited Blade Works', 5, NOW()),
('Bad Joke Eel', 3, NOW()),
('Anonymous', 3, NOW()),
('Bronyspeak', 5, NOW()),
('[Help!] The Girl I Like Won’t Respond to My Emails (´･ω･`)', 2, NOW()),
('Twitch Emotes', 5, NOW()),
('Checkmate, Atheists', 5, NOW()),
('Cursed Image', 4, NOW()),
('Nailed It', 3, NOW()),
('Peanut Butter Jelly Time', 2, NOW()),
('4chumblr', 3, NOW()),
('Reply Girls', 5, NOW()),
('Man''s Not Hot', 2, NOW()),
('The Rent is Too Damn High / Jimmy McMillan', 3, NOW()),
('Turn To Page 394', 5, NOW()),
('Social Justice Warrior', 1, NOW()),
('A Wild X Appears! / Wild X Appeared!', 4, NOW()),
('Bimbofication', 4, NOW()),
('Brainlet', 1, NOW()),
('Bad Apple!!', 2, NOW()),
('Comic Sans', 3, NOW()),
('Chris Hansen', 2, NOW()),
('Bonsai Kittens', 1, NOW()),
('The Tails Doll', 1, NOW()),
('Hatsune Miku / Vocaloid', 2, NOW()),
('This Is a Flammenwerfer, It Werfs Flammen', 1, NOW()),
('You Reposted in the Wrong Neighborhood', 2, NOW()),
('Chuck Norris Facts', 5, NOW()),
('ManningFace', 3, NOW()),
('Alignment Charts', 5, NOW()),
('Fire Emblem', 3, NOW()),
('Excuse Me What the Fuck', 4, NOW()),
('Body Inflation', 4, NOW()),
('Nice Girl Bike', 2, NOW()),
('LOLcats', 4, NOW()),
('The Ass Was Fat / Arthur Sees A Fat Ass', 2, NOW()),
('Handsome Squidward / Squidward Falling', 2, NOW()),
('Technologically Impaired Duck', 3, NOW()),
('Johnny Sins', 5, NOW()),
('Mind = Blown', 4, NOW()),
('Mission Report: December 16th, 1991', 2, NOW()),
('Ben Garrison', 2, NOW()),
('Pee Is Stored in the Balls', 1, NOW()),
('Cigar Guy', 3, NOW()),
('Queen of England Death Predictions', 4, NOW()),
('IKEA Monkey', 4, NOW()),
('Long Neck Reaction Guy', 4, NOW()),
('Dril', 1, NOW()),
('HowToBasic', 1, NOW()),
('Lie Down / Try Not To Cry / Cry A Lot', 3, NOW()),
('We''re Fucking Cock Destroyers', 2, NOW()),
('Pepehands', 5, NOW()),
('Amanda Todd''s Death', 3, NOW()),
('Every Day I''m Shufflin', 4, NOW()),
('I Love You 3000', 5, NOW()),
('Super Smash Brothers Ultimate', 1, NOW()),
('Smug Frog', 1, NOW()),
('GigaChad', 4, NOW()),
('Despacito 2', 1, NOW()),
('You Dense Motherfucker', 5, NOW()),
('Crash Bandicoot "Woah"', 1, NOW()),
('Time Traveling Hipster', 2, NOW()),
('Respect Women', 3, NOW()),
('American Chopper Argument', 3, NOW()),
('"Milhouse Is Not A Meme"', 3, NOW()),
('Why The Fuck You Lyin''', 1, NOW()),
('Goosh Goosh', 1, NOW()),
('My Bike Got Stolen Recently', 2, NOW()),
('I''m in That Weird Part of YouTube', 2, NOW()),
('GiIvaSunner / SiIvaGunner', 2, NOW()),
('Oh No, It''s Retarded', 2, NOW()),
('Everyday We Stray Further From God''s Light', 1, NOW()),
('Bel-Air (Fresh Prince)', 4, NOW()),
('Attack on Titan / Shingeki No Kyojin', 5, NOW()),
('Avatar: The Last Airbender / The Legend of Korra', 5, NOW()),
('A.I.Channel / Ai Kizuna', 3, NOW()),
('Gondola', 5, NOW()),
('Brad''s Wife', 4, NOW()),
('What Is the Airspeed Velocity of an Unladen Swallow?', 3, NOW()),
('Diglett Underground', 5, NOW()),
('Nigga, You Gay', 3, NOW()),
('Stop Girl', 3, NOW()),
('Bongo Cat', 4, NOW()),
('Ken-Sama', 1, NOW()),
('Etika', 2, NOW()),
('Attractive Convict', 1, NOW()),
('Bronies', 4, NOW()),
('Shia LaBeouf''s Intense Motivational Speech / Just Do It', 2, NOW()),
('Top 10 Anime List Parodies', 2, NOW()),
('I Told You About Stairs', 3, NOW()),
('30-Year-Old Virgin Wizard', 4, NOW()),
('You Tried', 5, NOW()),
('Bitch I Might Be', 1, NOW()),
('Special Delivery Instructions', 1, NOW()),
('Naked Banana', 5, NOW()),
('Raptor Jesus', 2, NOW()),
('Youngster Joey', 1, NOW()),
('What You See vs. What She Sees', 1, NOW()),
('LOL Jesus', 2, NOW()),
('Do It For Her', 4, NOW()),
('Sad Panda', 2, NOW()),
('Gingers Do Have Souls!', 3, NOW()),
('Hand Me the Aux Cord', 5, NOW()),
('Apu Apustaja', 1, NOW()),
('You Just Have to Say That You''re Fine', 1, NOW()),
('The Absolute Madman', 3, NOW()),
('Sea-Lioning', 1, NOW()),
('Pony Reactions', 4, NOW()),
('Nut Button', 2, NOW()),
('Video Game Logic', 4, NOW()),
('Biggie Cheese', 5, NOW()),
('Pakalu Papito', 3, NOW()),
('Describe Yourself in 3 Fictional Characters', 5, NOW()),
('Call Me Maybe', 5, NOW()),
('A Winner Is You', 3, NOW()),
('Pics or It Didn''t Happen', 4, NOW()),
('Get Down (Geddan)', 4, NOW()),
('Poggers', 3, NOW()),
('Real Nigga Hours', 5, NOW()),
('Laughing Tom Cruise', 1, NOW()),
('Vibe Check', 1, NOW()),
('Amerimutt / Le 56% Face', 5, NOW()),
('Good Girl Gina', 2, NOW()),
('Ant-Man Will Defeat Thanos by Crawling Up His Butt and Expanding', 2, NOW()),
('James Franco “First Time?”', 4, NOW()),
('Shadilay', 2, NOW()),
('Snek', 4, NOW()),
('Big Nigga', 4, NOW()),
('I''m in Me Mum''s Car, Broom Broom', 5, NOW()),
('Yamcha''s Death Pose', 4, NOW()),
('Amanda Cummings'' Death', 4, NOW()),
('Circle Jerk', 5, NOW()),
('DJ P0N-3 / Vinyl Scratch', 4, NOW()),
('Luna Game / The End is Neigh', 4, NOW()),
('Kill la Kill', 4, NOW()),
('Luigi''s Death Stare', 3, NOW()),
('Anti-Masturbation Cross', 2, NOW()),
('I Regret Nothing', 2, NOW()),
('Brazilian Fart Porn', 3, NOW()),
('You Must Be New Here', 5, NOW()),
('Fuck Me, Right?', 1, NOW()),
('Friendzone Johnny', 2, NOW()),
('Fukkireta (吹っ切れた)', 3, NOW()),
('Birthday Dog', 2, NOW()),
('You Vs. The Guy She Told You Not to Worry About', 3, NOW()),
('Rage Quit', 2, NOW()),
('Differenze Linguistiche', 4, NOW()),
('Wake Me Up Inside (Can''t Wake Up)', 2, NOW()),
('I Studied the Blade', 5, NOW()),
('Crazy Frog Brothers', 5, NOW()),
('Inappropriate Timing Spongebob Banner', 2, NOW()),
('Despacito', 2, NOW()),
('Amazing Horse', 5, NOW()),
('Hipster Glasses', 1, NOW()),
('You Either Die A Hero, Or You Live Long Enough To See Yourself Become The Villain', 1, NOW()),
('Eat Hot Chip and Lie', 3, NOW()),
('Steve Buscemeyes', 4, NOW()),
('I''m an Anteater!!!', 2, NOW()),
('Vape Nation', 3, NOW()),
('Friend Zone Fiona', 1, NOW()),
('Starecat / Grafics Cat', 4, NOW()),
('Ralph Pootawn', 5, NOW()),
('What is Love?', 5, NOW()),
('Wolf Girl With You', 5, NOW()),
('Ayaya', 5, NOW()),
('Learn to Code', 2, NOW()),
('My Little Pony Character Fandom', 2, NOW()),
('Dancing Spider-Man', 5, NOW()),
('Why Wub Woo / Dashface', 2, NOW()),
('America: Fuck Yeah!', 1, NOW()),
('Meanwhile in...', 3, NOW()),
('It''s Super Effective!', 5, NOW()),
('Cummies', 3, NOW()),
('White People Dancing / LOL White People', 5, NOW()),
('Just As Planned', 5, NOW()),
('Absolutely Disgusting', 5, NOW()),
('Big Enough', 4, NOW()),
('Bro Fist', 1, NOW()),
('Vladimir Putin', 4, NOW()),
('5ever', 4, NOW()),
('It Was At This Moment He Knew... He Fucked Up', 1, NOW()),
('Sweating Towel Guy', 3, NOW()),
('You''re Mom Gay', 5, NOW()),
('Moonbase Alpha Text to Speech', 4, NOW()),
('Nutted But She Still Sucking', 4, NOW()),
('Dis Gon B Gud', 2, NOW()),
('Linda Glocke / I Will Destroy ISIS', 2, NOW()),
('He Will Never Have a Girlfriend', 3, NOW()),
('Ocean Man', 3, NOW()),
('Family Guy Effect', 5, NOW()),
('Owling', 3, NOW()),
('Bitch I''m Fabulous', 1, NOW()),
('DSPGaming', 3, NOW()),
('Savage Patrick', 2, NOW()),
('Awoo~', 2, NOW()),
('Stock Photo Clichés', 4, NOW()),
('Cookie Clicker', 3, NOW()),
('LUL', 1, NOW()),
('Howard the Alien / Money Longer Alien', 5, NOW()),
('Image Macros', 5, NOW()),
('Griefing', 5, NOW()),
('I Did It for the Lulz', 1, NOW()),
('Yiff', 4, NOW()),
('Change Da World... My Final Message', 4, NOW()),
('Interior Crocodile Alligator', 5, NOW()),
('That Wasn''t Very Cash Money of You', 2, NOW()),
('Facebook', 3, NOW()),
('Streisand Effect', 1, NOW()),
('Professor Badass', 2, NOW()),
('Unpopular Opinion Puffin', 5, NOW()),
('Get To The Choppa', 4, NOW()),
('Zamii070 Harassment Controversy', 2, NOW()),
('Salty', 1, NOW()),
('BadBoy2 / I''m 18, Do I Have Potential?', 5, NOW()),
('No Items, Fox Only, Final Destination', 2, NOW()),
('Super Mario', 5, NOW()),
('Improvise. Adapt. Overcome', 3, NOW()),
('Shaggy''s Power', 2, NOW()),
('Game Grumps', 2, NOW()),
('I Drink Your Milkshake!', 3, NOW()),
('I Don''t Like Sand', 3, NOW()),
('Diretide', 3, NOW()),
('360 No Scope', 1, NOW()),
('Facebook Cartoon Profile Picture Week', 3, NOW()),
('Cuteness Overload', 1, NOW()),
('Instagram', 2, NOW()),
('That''s How Mafia Works', 3, NOW()),
('Boneless Pizza', 4, NOW()),
('Milkshake Duck', 3, NOW()),
('Misunderstood D-Bag', 3, NOW()),
('Magikarp Guy', 1, NOW()),
('Content Aware Scaling', 4, NOW()),
('0.5x A Presses / But First We Need to Talk About Parallel Universes', 2, NOW()),
('Spanish Laughing Guy / "El Risitas" Interview Parodies', 5, NOW()),
('Untoons', 5, NOW()),
('/pol/', 3, NOW()),
('Katya Lischina', 2, NOW()),
('Polybius', 3, NOW()),
('Bold Move Cotton', 1, NOW()),
('Super Cool Ski Instructor', 1, NOW()),
('Gijinka / Moe Anthropomorphism', 5, NOW()),
('Hey Beter', 4, NOW()),
('Bait / This is Bait', 4, NOW()),
('Nickelback', 2, NOW()),
('Sitting Lyra', 1, NOW()),
('Keyboard Cat', 4, NOW()),
('It''s Not Lupus', 4, NOW()),
('Row Row Fight the Powah', 1, NOW()),
('Monster Musume / Daily Life with Monster Girl', 5, NOW()),
('Naruto Run', 1, NOW()),
('Blyat / Cyka Blyat', 4, NOW()),
('How About No?', 1, NOW()),
('Le Toucan', 2, NOW()),
('Cats Can Have a Little Salami', 1, NOW()),
('You''ve Heard of the Elf on the Shelf...', 5, NOW()),
('They''re Taking the Hobbits to Isengard', 3, NOW()),
('Recorded with a Potato', 4, NOW()),
('Best Gore', 1, NOW()),
('Supercut', 5, NOW()),
('That Would Be Great', 2, NOW()),
('Legal Loli', 3, NOW()),
('What is a man?', 3, NOW()),
('Oh Long Johnson', 2, NOW()),
('So Long, Gay Bowser', 3, NOW()),
('Sweet Apple Massacre (My Little Pony Fanfiction)', 5, NOW()),
('Nico Nico Nii', 5, NOW()),
('Awkward Moment Seal', 4, NOW()),
('Straight Outta Somewhere / #StraightOutta', 3, NOW()),
('The Alot', 2, NOW()),
('Jasmine Masters "And I Oop"', 3, NOW()),
('In Ur Base', 4, NOW()),
('4chan Party Van', 3, NOW()),
('Grandma Finds the Internet', 2, NOW()),
('Super Bowl XLIX Halftime "Left Shark"', 2, NOW()),
('S[he] Be[lie]ve[d] (Sbeve)', 5, NOW()),
('The Picard Song', 5, NOW()),
('What The Fuck Am I Reading?', 3, NOW()),
('Plastic Love', 4, NOW()),
('Celebrity Pokemon Evolutions', 2, NOW()),
('BBQ Becky', 3, NOW()),
('"You Could Stop at Five or Six Stores"', 4, NOW()),
('Allahu Akbar', 4, NOW()),
('Zelda''s Response', 5, NOW()),
('Slide Into Your DMs', 2, NOW()),
('Astronaut Sloth', 5, NOW()),
('Nice Boat.', 4, NOW()),
('Unsettled Tom', 2, NOW()),
('Oh No Baby! What Is You Doin???', 5, NOW()),
('Bunchie', 5, NOW()),
('Winnie The Pooh''s Home Run Derby', 1, NOW()),
('What Are You Doing, Step Bro?', 2, NOW()),
('All Right, Gentlemen!', 5, NOW()),
('Boar Vessel', 2, NOW()),
('Happy Cat', 3, NOW()),
('NOMA - Brain Power', 4, NOW()),
('Fuck Logic', 3, NOW()),
('Don''t Worry, He Knows', 5, NOW()),
('Here in My Garage', 1, NOW()),
('I''m Literally the Guy in the Pic', 4, NOW()),
('Dinkleberg', 4, NOW()),
('Brushie Brushie Brushie', 2, NOW()),
('OK So Basically I''m Monky', 1, NOW()),
('Just Kidding... Unless?', 1, NOW()),
('Bench Tails', 1, NOW()),
('Make Your Own Album Cover', 2, NOW()),
('Woody Harrelson Reddit AMA', 1, NOW()),
('Strong Black Woman Who Don''t Need No Man', 3, NOW()),
('Dihydrogen Monoxide Hoax', 3, NOW()),
('Clever Girl', 5, NOW()),
('The D', 1, NOW()),
('Globglogabgalab', 2, NOW()),
('WTF BOOM!', 1, NOW()),
('Sheltering Suburban Mom', 3, NOW()),
('Fakemon', 4, NOW()),
('Race Guy', 2, NOW()),
('Gadsden Flag / Don''t Tread On Me', 1, NOW()),
('Spider-Man Ass Slap', 3, NOW()),
('Adolf Hitler', 2, NOW()),
('You Win the Internet!', 2, NOW()),
('I''m Watching You', 1, NOW()),
('Dick Flattening', 2, NOW()),
('Dankey Kang', 3, NOW()),
('What Year Is It?', 2, NOW()),
('Ara Ara', 5, NOW()),
('L.A. Noire "Doubt" / Press X To Doubt', 2, NOW()),
('How to Wear a Men''s Shirt', 3, NOW()),
('Gravity Falls', 3, NOW()),
('Pop Team Epic', 2, NOW()),
('Interior Monologue Captioning', 5, NOW()),
('I Showed You My Dick Please Respond', 2, NOW()),
('Dragons Having Sex with Cars', 5, NOW()),
('Baldi''s Basics in Education and Learning', 2, NOW()),
('I Was Only Pretending To Be Retarded', 4, NOW()),
('Creepy Villager', 3, NOW()),
('Annoying Childhood Friend', 4, NOW()),
('Manly Tears', 4, NOW()),
('>Implying (Implying Implications)', 1, NOW()),
('Thinking Face Emoji 🤔', 3, NOW()),
('Corey Worthington''s Party', 4, NOW()),
('Bone Apple Tea', 3, NOW()),
('R+L=J', 5, NOW()),
('Still a Better Love Story than Twilight', 5, NOW()),
('That''s the Evilest Thing I Can Imagine', 1, NOW()),
('Hipster', 2, NOW()),
('Smugleaf', 5, NOW()),
('NSFW', 4, NOW()),
('Sarah Jessica Parker Looks Like a Horse', 5, NOW()),
('Rasta Science Teacher', 1, NOW()),
('Ken M', 4, NOW()),
('Tiger Mom', 3, NOW()),
('Magibon', 1, NOW()),
('Top Gun Hat', 2, NOW()),
('Party Hard', 1, NOW()),
('Did You Just Assume My Gender?', 4, NOW()),
('Lord Tachanka', 1, NOW()),
('Activated Almonds', 4, NOW()),
('Fifty Shades of Grey', 3, NOW()),
('New Guy', 5, NOW()),
('Bro, I''m Straight Up Not Having a Good Time', 2, NOW()),
('Charlie Sheen Rant / #tigerblood', 3, NOW()),
('Cracky-chan', 4, NOW()),
('"You And Me" Parodies', 5, NOW()),
('The YouTube Sexual Abuse Scandal', 5, NOW()),
('That Post Gave Me Cancer', 3, NOW()),
('Assuming Control', 2, NOW()),
('Get A Brain Morans', 5, NOW()),
('I''m Baby', 4, NOW()),
('Trust Nobody, Not Even Yourself', 4, NOW()),
('How Italians Do Things', 4, NOW()),
('I''ve Seen Enough Hentai To Know Where This Is Going', 3, NOW()),
('Nazi Pepe Controversy', 3, NOW()),
('Feeling Cute Challenge', 5, NOW()),
('Shiny Pidgey', 2, NOW()),
('Yes Chad', 1, NOW()),
('Cheeky Nando''s', 2, NOW()),
('BonbiBonkers', 1, NOW()),
('It''s Okay to Be White', 3, NOW()),
('Portal 2 Space Personality Core', 1, NOW()),
('Lex Luthor Took Forty Cakes', 3, NOW()),
('Video Games Appeal to the Male Fantasy', 3, NOW()),
('Spooky Scary Skeletons', 4, NOW()),
('Greg Paul Sex Tape Leak', 5, NOW()),
('Mary Sue', 1, NOW()),
('The Last Page of the Internet', 1, NOW()),
('BLACKED', 2, NOW()),
('Gohan Blanco', 3, NOW()),
('Piracy, It''s a Crime', 4, NOW()),
('What I Watched / What I Expected / What I Got', 1, NOW()),
('You Get Nothing! You Lose! Good Day, Sir!', 2, NOW()),
('Demopan', 4, NOW()),
('-fag (Suffix)', 1, NOW()),
('Surprise, Bitch', 1, NOW()),
('Girugamesh', 5, NOW()),
('Don''t Look at Her', 1, NOW()),
('Who Created Kirby?', 3, NOW()),
('White Knight', 5, NOW()),
('Medieval Tapestry Edits', 5, NOW()),
('Loud Nigra', 5, NOW()),
('Lonk', 4, NOW()),
('Caramelldansen', 5, NOW()),
('No Nut November', 2, NOW()),
('Shipping', 4, NOW()),
('Todd Howard', 4, NOW()),
('Chocolate Rain', 4, NOW()),
('Where Is Your God Now?', 4, NOW()),
('Fuckboy', 5, NOW()),
('Desiree Jennings Dystonia Hoax', 5, NOW()),
('Welcome To The Salty Spitoon. How Tough Are Ya?', 3, NOW()),
('Well Yes, But Actually No', 1, NOW()),
('Lame Pun Coon', 5, NOW()),
('I Cri Evrytiem', 1, NOW()),
('Then Perish', 3, NOW()),
('I Got 99 Problems But a Bitch Ain''t One', 1, NOW()),
('/b/', 2, NOW()),
('DOOM: Repercussions of Evil', 2, NOW()),
('Zoomer', 4, NOW()),
('Wrong Lyrics Christina', 5, NOW()),
('Brittany Venti', 3, NOW()),
('You See Ivan...', 5, NOW()),
('Ponify', 5, NOW()),
('Unidan', 3, NOW()),
('Red Shirt Guy', 1, NOW()),
('How to Break Your Thumb Ligament', 5, NOW()),
('Ding Fries Are Done', 5, NOW()),
('Stu Making Chocolate Pudding At 4 AM', 3, NOW()),
('Thank You Kanye, Very Cool!', 1, NOW()),
('Lonely Computer Guy / Net Noob', 3, NOW()),
('Game of Thrones', 2, NOW()),
('YES! YES!', 5, NOW()),
('Graphic Design Is My Passion', 2, NOW()),
('It''s High Noon', 5, NOW()),
('Bikini Bridge', 5, NOW()),
('Single-Serving Site', 1, NOW()),
('Gavin', 4, NOW()),
('Meme Magic', 2, NOW()),
('2019 Tokyo Yandere Stabbing', 3, NOW()),
('Budd Dwyer Suicide Video', 3, NOW()),
('ProJared Cheating Scandal', 1, NOW()),
('Urban Dictionary', 2, NOW()),
('Bill O''Reilly Rant', 1, NOW()),
('Christopher Poole / moot', 3, NOW()),
('Polite Cat', 2, NOW()),
('The Woah', 2, NOW()),
('Trump Is Playing 4D Chess', 4, NOW()),
('Whatcha Thinkin Bout?', 1, NOW()),
('Don''t Hug Me I''m Scared', 1, NOW()),
('Can You Please Photoshop The Sun Between My Fingers?', 1, NOW()),
('Dakimakura / Body Pillow', 3, NOW()),
('Domo', 2, NOW()),
('But I Poop From There', 4, NOW()),
('Smug Wendy''s', 3, NOW()),
('Grape-kun', 5, NOW()),
('Monster Girls', 1, NOW()),
('Angry Pepe', 2, NOW()),
('Final Boss of the Internet', 2, NOW()),
('Brock Obama', 1, NOW()),
('Star Wars', 4, NOW()),
('GIF', 1, NOW()),
('Fuck Yeah Seaking', 1, NOW()),
('Lenin Cat', 2, NOW()),
('Pornhub', 1, NOW()),
('Kowalski', 4, NOW()),
('Tumblr Nose', 5, NOW()),
('Big Dick Energy', 5, NOW()),
('It Really Do Be Like That Sometimes', 3, NOW()),
('Erratas', 3, NOW()),
('Honk Honk / Chen Edits', 2, NOW()),
('The More You Know', 2, NOW()),
('Anita Sarkeesian', 3, NOW()),
('Spy Crab', 1, NOW()),
('e621', 5, NOW()),
('Super Smash Bros Character Predictions', 4, NOW()),
('9/11 Tourist Guy', 4, NOW()),
('Angelina Jolie''s Leg', 5, NOW()),
('Y Tho', 2, NOW()),
('My Hero Academia', 2, NOW()),
('Do She Got a Booty? (She Do)', 3, NOW()),
('Doctor Whooves / Time Turner', 1, NOW()),
('Meth, Not Even Once', 5, NOW()),
('Stoner Dog', 4, NOW()),
('Don''t Judge Challenge', 2, NOW()),
('Red Leader Standing By', 5, NOW()),
('That Pool', 2, NOW()),
('Spiders Georg', 4, NOW()),
('Topkek', 3, NOW()),
('Lying Down Game', 2, NOW()),
('Dancing Baby', 1, NOW()),
('Renai Circulation', 4, NOW()),
('Mia Khalifa Death Threats', 3, NOW()),
('Clippy', 2, NOW()),
('Some Of You Guys Are Alright', 5, NOW()),
('Sonic Original Characters', 5, NOW()),
('Eli Porter', 2, NOW()),
('asdfmovie', 2, NOW()),
('Benis', 5, NOW()),
('Horse-Sized Duck', 2, NOW()),
('Hmm Today I Will', 2, NOW()),
('SourPls', 3, NOW()),
('Don''t Blink "The Weeping Angels"', 2, NOW()),
('Original vs. Un-Tumblrized', 5, NOW()),
('Yotsuba Koiwai / 404 Girl', 2, NOW()),
('He Needs Some Milk', 2, NOW()),
('Babby', 5, NOW()),
('Happy Keanu', 4, NOW()),
('Gordon Ramsay', 1, NOW()),
('Cock and Ball Torture', 5, NOW()),
('Pregnancy Announcement', 2, NOW()),
('That Damn Smile', 4, NOW()),
('What 4chan Cries Out During Sex', 1, NOW()),
('I''m sorry, I can''t hear you over the sound of how awesome I am', 5, NOW()),
('Hunger Games Simulator', 5, NOW()),
('Christ-chan', 3, NOW()),
('Look at This Dude / Flipagram Roast Videos', 2, NOW()),
('Everyone Loses Their Minds', 5, NOW()),
('Nevada-Tan', 1, NOW()),
('Beautiful Cinnamon Roll Too Good For This World, Too Pure', 4, NOW()),
('I Can''t Believe You''ve Done This!', 4, NOW()),
('Barack Obama', 4, NOW()),
('Your Music''s Bad and You Should Feel Bad', 1, NOW()),
('Excuse Me Sir, Do You Have a Moment to Talk About Jesus Christ?', 3, NOW()),
('Swole', 2, NOW()),
('Glen Coco', 2, NOW()),
('Bread Helmet Man', 1, NOW()),
('Lick Icons', 3, NOW()),
('She Was His Queen...', 5, NOW()),
('Skinny Legend', 1, NOW()),
('Sage', 5, NOW()),
('You Have My Sword, And My Bow, And My Axe', 1, NOW()),
('Keyhole Turtleneck', 4, NOW()),
('Hitler Did Nothing Wrong', 3, NOW()),
('God I Wish That Were Me', 1, NOW()),
('Prancing Cera', 3, NOW()),
('Vince McMahon Reaction', 2, NOW()),
('Protect IP Act / Stop Online Piracy Act (PIPA / SOPA)', 2, NOW()),
('Channel Awesome Implosion / #ChangeTheChannel', 4, NOW()),
('Penis Goes Where/Cock goes where', 4, NOW()),
('Robot Unicorn Attack / Harmony Harmony', 5, NOW()),
('The "!1" Phenomenon', 5, NOW()),
('Fish4Hoes', 2, NOW()),
('King Crimson (JoJo)', 1, NOW()),
('Mirai Nikki Yandere Face', 3, NOW()),
('Le', 4, NOW()),
('MEMRI TV', 3, NOW()),
('Olympics or Gay Porn?', 5, NOW()),
('Faces of Marijuana', 1, NOW()),
('orz', 4, NOW()),
('I''m Going To Build My Own Theme Park With Blackjack and Hookers', 3, NOW()),
('#SlaneGirl', 3, NOW()),
('Curb Your Enthusiasm Theme Remixes', 2, NOW()),
('You Shall Not Pass!!!', 4, NOW()),
('NOT THE BEES!', 2, NOW()),
('You Cheated Not Only the Game, But Yourself', 4, NOW()),
('Perfectly Timed Photos', 4, NOW()),
('Filthy Casual', 1, NOW()),
('Warhammer 40,000', 1, NOW()),
('I Can''t Even', 1, NOW()),
('Angry German Kid / Keyboard Crasher', 1, NOW()),
('Updog', 4, NOW()),
('Ryan Gosling Won''t Eat His Cereal', 5, NOW()),
('Trainers Hate Him', 1, NOW()),
('IDDQD', 1, NOW()),
('Unnecessary Censorship', 4, NOW()),
('Marge Krumping', 3, NOW()),
('Cr1TiKaL', 4, NOW()),
('You On Kazoo', 4, NOW()),
('Black Twitter', 2, NOW()),
('I Watch It For The Plot', 2, NOW()),
('Actual Sexual Advice Girl', 1, NOW()),
('The FitnessGram Pacer Test', 1, NOW()),
('Dogs', 5, NOW()),
('Wii Fit Girl', 4, NOW()),
('Oh God What Have I Done?', 3, NOW()),
('Get Out Frog / Frogout / Me Obrigue', 5, NOW()),
('The Great Subscriber War / Subscribe to PewDiePie', 4, NOW()),
('Swiggity Swag', 4, NOW()),
('Slow Clap', 2, NOW()),
('Old Man Yells at Cloud', 4, NOW()),
('Wait, That''s Illegal', 1, NOW()),
('The World According To...', 5, NOW()),
('Hurr Durr', 4, NOW()),
('Bianca Devins'' Murder', 3, NOW()),
('Alberto Barbosa', 5, NOW()),
('420', 3, NOW()),
('Senior College Student', 1, NOW()),
('Annoyed Bird', 1, NOW()),
('Emojipasta', 5, NOW()),
('And It''s Gone', 1, NOW()),
('Toto''s "Africa"', 4, NOW()),
('Ctrl+Alt+Del', 2, NOW()),
('"Speak to the Manager" Haircut', 4, NOW()),
('iDubbbz''s "I''m Gay"', 1, NOW()),
('Laundry Room Viking', 5, NOW()),
('Glowing Eyes', 4, NOW()),
('Baby Godfather', 4, NOW()),
('Guess I''ll Die', 5, NOW()),
('Epic Boobs Girl', 3, NOW()),
('Polish Jerry', 2, NOW()),
('Pokémon Sun and Moon', 1, NOW()),
('Crazy Girlfriend Praying Mantis', 3, NOW()),
('I''m At Soup / Soup Store', 4, NOW()),
('It''s More Likely Than You Think', 1, NOW()),
('Disney''s Frozen Whitewashing Controversy', 2, NOW()),
('Guido Jesus', 4, NOW()),
('Fuck Yo Couch', 3, NOW()),
('Weber Cooks', 3, NOW()),
('People Who Thank the Bus Driver', 3, NOW()),
('Jesusland', 3, NOW()),
('Nigerian Scams', 2, NOW()),
('But Can It Run Crysis?', 1, NOW()),
('Kumamon', 3, NOW()),
('Immature High Schoolers', 4, NOW()),
('Jam It In! / You Lost Me', 3, NOW()),
('You''re A Wizard, Harry!', 4, NOW()),
('Serious Cat', 2, NOW()),
('Fake History', 5, NOW()),
('"S" Stands For? / Smile Sweet Sister Sadistic Suprise Service', 5, NOW()),
('The Holders', 1, NOW()),
('The Human Centipede', 3, NOW()),
('Tabby', 5, NOW()),
('LazyTown', 1, NOW()),
('Days Without Sex', 4, NOW()),
('Safety Not Guaranteed', 2, NOW()),
('Sweetie Belle Derelle', 1, NOW()),
('Pony Re-Imaginings', 2, NOW()),
('Forever Resentful Mother', 1, NOW()),
('Trying to Hold a Fart Next to a Cute Girl in Class', 2, NOW()),
('Enderman', 2, NOW()),
('Billie Eilish''s 18th Birthday', 4, NOW()),
('Hentai Haven', 4, NOW()),
('Creepy Katara', 4, NOW()),
('Ben Shapiro DESTROYS Liberals', 1, NOW()),
('Leekspin / Loituma Girl', 5, NOW()),
('Advice God', 3, NOW()),
('Flutterrage / Flutterbitch', 5, NOW()),
('Saturdays Are For The Boys', 4, NOW()),
('Logan Paul', 2, NOW()),
('Endless Eight / Kyon-kun Denwa!', 4, NOW()),
('Vic Mignogna Sexual Harassment Allegations', 2, NOW()),
('It''s Time to Stop', 4, NOW()),
('Nelson the Bull Terrier / Walter', 5, NOW()),
('GET', 4, NOW()),
('Doesn''t Matter, Had Sex', 5, NOW()),
('Rotten.com', 4, NOW()),
('Van-sama / Fercussion', 3, NOW()),
('I AM ERROR', 3, NOW()),
('Let''s Go Bowling', 3, NOW()),
('Sleep Tight Pupper', 4, NOW()),
('69', 3, NOW()),
('Behind The Meme', 2, NOW()),
('Tobuscus', 2, NOW()),
('My Wife''s Son', 1, NOW()),
('Alinity', 5, NOW()),
('Nightcore', 1, NOW()),
('Hampster Dance', 4, NOW()),
('Gee Bill! How Come Your Mom Lets You Eat Two Wieners?', 5, NOW()),
('Tuxedo Winnie the Pooh', 3, NOW()),
('ExHentai / SadPanda', 4, NOW()),
('Skeptical Baby', 5, NOW()),
('Batman', 4, NOW()),
('Food Network Recipe Reviews', 1, NOW()),
('Sosig', 2, NOW()),
('ISIS-chan', 2, NOW()),
('Sminem', 3, NOW()),
('The Amazing Atheist', 4, NOW()),
('Needs More Cowbell', 5, NOW()),
('Mic Drop', 4, NOW()),
('Original Character Do Not Steal', 5, NOW()),
('John Cena', 1, NOW()),
('Monkey Puppet', 1, NOW()),
('Eddy Wally''s "Wow"', 3, NOW()),
('Hi, My Name Is Reggie', 1, NOW()),
('Based Stickman', 5, NOW()),
('Pew Pew', 3, NOW()),
('Ayuwoki', 1, NOW()),
('Drakeposting', 3, NOW()),
('Occupy Wall Street', 5, NOW()),
('Caturday', 3, NOW()),
('A Midsummer Night''s Lewd Dream / 真夏の夜の淫夢', 4, NOW()),
('You''re Gonna Have a Bad Time', 4, NOW()),
('Wii Fit Trainer', 2, NOW()),
('Minor Mistake Marvin', 2, NOW()),
('Facebomb', 3, NOW()),
('Twerking', 5, NOW()),
('NEDM', 5, NOW()),
('CathyMay15', 2, NOW()),
('Involuntary Celibacy / Incel', 2, NOW()),
('Hungry Kim Jong-un', 5, NOW()),
('Gay Test', 1, NOW()),
('Patrick Bateman With an Axe', 3, NOW()),
('Keanu Reeves', 4, NOW()),
('I Never Asked For This', 4, NOW()),
('Don''t Ask Who Joe Is / Joe Mama', 5, NOW()),
('The Weighted Companion Cube', 4, NOW()),
('Tom Preston', 1, NOW()),
('Layers of Irony', 2, NOW()),
('Nuke It From Orbit', 3, NOW()),
('How About I Slap Your Shit', 5, NOW()),
('Three Seashells', 5, NOW()),
('Cumbox', 5, NOW()),
('Snails Sleep 3', 3, NOW()),
('And In That Moment I Swear We Were Infinite', 4, NOW()),
('Depression Dog', 3, NOW()),
('They Had Us In the First Half', 3, NOW()),
('Delete This Nephew', 3, NOW()),
('Wise Confucius', 1, NOW()),
('Pancake Bunny', 4, NOW()),
('No God, Please No!', 2, NOW()),
('One-Punch Man', 4, NOW()),
('Oprah''s "You Get a Car"', 1, NOW()),
('Sleeping Shaq', 4, NOW()),
('Going to the Store', 2, NOW()),
('TheReportOfTheWeek', 3, NOW()),
('Welcome to The Internet', 3, NOW()),
('Photo Fads', 4, NOW()),
('Crossed-Out Pride Flag Emoji Combination', 5, NOW()),
('When U Mom Com Home And Make Hte Spagheti', 4, NOW()),
('I Too Like to Live Dangerously', 3, NOW()),
('ProjektMelody', 2, NOW()),
('Me Me Big Boy', 1, NOW()),
('Flat Is Justice / Delicious Flat Chest', 3, NOW()),
('Epic Handshake', 3, NOW()),
('1337 speak', 3, NOW()),
('Epic Fail Guy', 4, NOW()),
('We Did It Reddit!', 5, NOW()),
('Why Would You Say Something So Controversial Yet So Brave?', 2, NOW()),
('Fallout', 3, NOW()),
('4chan Word Filter', 4, NOW()),
('Oh Joy Sex Toy''s "Cuck" Comic', 3, NOW()),
('Why So Serious?', 3, NOW()),
('Ordinary Muslim Man', 4, NOW()),
('You Are NOT The Father!', 5, NOW()),
('Snape Kills Dumbledore', 2, NOW()),
('Pokemon Lost Silver', 3, NOW()),
('The Legend of Zelda', 5, NOW()),
('OMG Cat', 4, NOW()),
('Kanye West', 2, NOW()),
('Be Strong For Mother', 1, NOW()),
('Argentina Is White', 1, NOW()),
('But Our Princess is in Another Castle!', 5, NOW()),
('Oh God How Did This Get Here I Am Not Good With Computer', 4, NOW()),
('Nope', 3, NOW()),
('Shit People Say', 1, NOW()),
('What Cleopatra May Have Looked Like', 5, NOW()),
('Numa Numa', 2, NOW()),
('Hold My Beer', 4, NOW()),
('Stand Cries / ORA ORA ORA / MUDA MUDA MUDA', 5, NOW()),
('In The Way Guy', 5, NOW()),
('High Impact Sexual Violence', 2, NOW()),
('Ram Ranch', 5, NOW()),
('Short Tyler1', 2, NOW()),
('Featuring Dante From The Devil May Cry Series', 3, NOW()),
('Limecat', 3, NOW()),
('Ultimate Insult Man', 4, NOW()),
('Indonesian Reporting Commission Facebook Takedowns', 5, NOW()),
('Pink Shirt Guy', 4, NOW()),
('Foul Bachelorette Frog', 5, NOW()),
('Wat Do?', 4, NOW()),
('Kim Jong-un', 5, NOW()),
('Internet Tough Guy', 3, NOW()),
('"i lik the bred"', 3, NOW()),
('Scumbag Hat', 3, NOW()),
('Sans', 2, NOW()),
('Don''t Look at Them Ricky!', 3, NOW()),
('John Lennon The Absolute Madman', 4, NOW()),
('Nic Cage as Everyone', 2, NOW()),
('Inappropriate Timing Bill Clinton', 4, NOW()),
('Doxing', 1, NOW()),
('Salad Fingers', 5, NOW()),
('HABEEB IT', 3, NOW()),
('Privilege Denying Dude', 4, NOW()),
('Fat Yoshi', 1, NOW()),
('Amouranth', 3, NOW()),
('h3h3productions', 2, NOW()),
('Doctor Who', 4, NOW()),
('Desk Flip', 5, NOW()),
('Massimo D''Alema', 1, NOW()),
('Running Butthole Challenge', 3, NOW()),
('I Throw My Hands Up In The Air Sometimes Saying Ayo', 4, NOW()),
('Roses Are Red, Violets Are Blue', 1, NOW()),
('Jesus Take The Wheel', 5, NOW()),
('Over-Educated Problems', 1, NOW()),
('I Can Be Your Angle Or Yuor Devil', 5, NOW()),
('But It''s Honest Work', 1, NOW()),
('Kyle', 5, NOW()),
('Cicada Block', 4, NOW()),
('& Knuckles', 2, NOW()),
('Has Science Gone Too Far?', 1, NOW()),
('And Then I Said', 1, NOW()),
('Calm Your Tits', 1, NOW()),
('30-50 Feral Hogs', 1, NOW()),
('PS3 Has No Games', 5, NOW()),
('I''m The Juggernaut, Bitch!', 2, NOW()),
('Anime Tiddies', 1, NOW()),
('Gordon Ramsay''s Lamb Sauce', 3, NOW()),
('Pokémon Sword and Shield', 5, NOW()),
('England Is My City', 3, NOW()),
('Nanomachines, Son', 3, NOW()),
('Noob Tube', 4, NOW()),
('Mah Nigga', 1, NOW()),
('Extra Thicc', 1, NOW()),
('Who Would Win?', 5, NOW()),
('Pony Cum Jar Project', 5, NOW()),
('Crabcore', 5, NOW()),
('Horse Armor', 4, NOW()),
('Fortnite', 2, NOW()),
('Maru the Cat', 4, NOW()),
('Shamefur Dispray', 3, NOW()),
('Free Helicopter Rides', 2, NOW()),
('Skipping Leg Day', 5, NOW()),
('Star Wars Kid', 4, NOW()),
('Fully Automated Luxury Gay Space Communism', 1, NOW()),
('Tentaquil', 1, NOW()),
('Dancing Stormtrooper', 5, NOW()),
('Bazinga', 1, NOW()),
('Horny Samus', 3, NOW()),
('Dinner with Waifu / Otaku Dates', 5, NOW()),
('Professor Oak', 3, NOW()),
('Wow Queen, You''re So Beautiful', 3, NOW()),
('Free Candy Van', 3, NOW()),
('Shit That Siri Says', 5, NOW()),
('Scottish Pokémon Trainer', 2, NOW()),
('So I Got That Goin'' For Me, Which is Nice', 3, NOW()),
('The Old Reddit Switch-a-roo', 4, NOW()),
('Who Is She? (Vine)', 2, NOW()),
('Evil Duolingo Owl', 1, NOW()),
('Duane!', 1, NOW()),
('Sweet Home Alabama', 1, NOW()),
('Overconfident Alcoholic', 2, NOW()),
('I Made You a Cookie, But I Eated It', 2, NOW()),
('Panty and Stocking', 5, NOW()),
('Kyle Punches Drywall', 1, NOW()),
('How People View Me After I Say I''m...', 4, NOW()),
('I''ll Take a Potato Chip and EAT IT!', 3, NOW()),
('Gaston', 3, NOW()),
('A Small Loan of a Million Dollars', 4, NOW()),
('Deepfakes', 2, NOW()),
('Infomercial Fails', 5, NOW()),
('Mafia City', 4, NOW()),
('Monster Girl Quest', 2, NOW()),
('"They Ask You How You Are and You Say That You''re Fine"', 5, NOW()),
('Internet Fight', 1, NOW()),
('Ha Ha Ha, No', 5, NOW()),
('Woomy', 5, NOW()),
('I Swear On Me Mum', 2, NOW()),
('MAD', 5, NOW()),
('Leonardo DiCaprio''s Oscar', 1, NOW()),
('You Have Died of Dysentery', 1, NOW()),
('At First I Was Like...', 2, NOW()),
('"Come On, It''s 2015" / Current Year', 4, NOW()),
('NONONONO Cat', 4, NOW()),
('Starbucks Drake Hands', 4, NOW()),
('Surreal Memes', 4, NOW()),
('Waluigi', 2, NOW()),
('Staring Hamster', 5, NOW()),
('I find your lack of faith disturbing', 5, NOW()),
('Basic Bitch', 1, NOW()),
('Forced Meme', 4, NOW()),
('Pleb', 5, NOW()),
('Internet Is Leaking', 4, NOW()),
('DJ Khaled', 2, NOW()),
('Hypnotoad', 1, NOW()),
('Who''s That Pokémon?', 5, NOW()),
('They Did Surgery On a Grape', 5, NOW()),
('Berserk', 5, NOW()),
('That''s a Penis', 3, NOW()),
('Sturgeon Face', 2, NOW()),
('The Almighty Loaf', 4, NOW()),
('Bitch Lasagna', 3, NOW()),
('On All Levels Except Physical, I am a Wolf', 2, NOW()),
('Autism', 3, NOW()),
('Otaku Test', 3, NOW()),
('Cosplay', 4, NOW()),
('Onii-chan', 3, NOW()),
('Goose on Fire / Fire Duck', 2, NOW()),
('Uvuvwevwevwe', 4, NOW()),
('Creepy Garfield', 1, NOW()),
('Flying Lawnmower', 4, NOW()),
('Hey Its Me Ur Brother', 2, NOW()),
('Engrish', 3, NOW()),
('Grimdark', 2, NOW()),
('TriHard', 3, NOW()),
('Bart, Get Out! I''m Piss!', 1, NOW()),
('Imagefap Trolling', 1, NOW()),
('Dramatic Chipmunk', 1, NOW()),
('Captain Hydra / Captain America "Hail Hydra" Edits', 5, NOW()),
('Just Waiting For A Mate', 1, NOW()),
('That''s The Joke', 4, NOW()),
('Glenn Beck Rape & Murder Hoax', 2, NOW()),
('I Can''t Fap to This', 4, NOW()),
('VTEC just kicked in, yo!', 5, NOW()),
('Scene Wolf', 3, NOW()),
('Javert Reaction GIFs', 5, NOW()),
('Social Justice Blogging', 3, NOW()),
('September 11th, 2001 Attacks', 3, NOW()),
('Well Meme''d', 5, NOW()),
('Say Sike Right Now', 1, NOW()),
('Club Penguin', 1, NOW()),
('The End of the World', 3, NOW()),
('Crack Kid', 5, NOW()),
('A Potato Flew Around My Room', 1, NOW()),
('Oh My God, Karen, You Can’t Just Ask Someone Why They''re White', 4, NOW()),
('McNuggies', 5, NOW()),
('Tsundere', 3, NOW()),
('Nyanyanyanyanyanyanya!', 5, NOW()),
('I Whip My Hair Back and Forth', 4, NOW()),
('Steve Jobs vs. Bill Gates', 5, NOW()),
('One Finger Selfie Challenge', 5, NOW()),
('The Scroll of Truth', 1, NOW()),
('Big Bill Hell''s', 5, NOW()),
('No, This Is Patrick', 1, NOW()),
('4chan Drinking Game Cards', 3, NOW()),
('You Are Now Breathing Manually', 3, NOW()),
('Daily Struggle', 4, NOW()),
('Fluffy Ponies', 3, NOW()),
('Lolrus', 1, NOW()),
('Captain Obvious', 3, NOW()),
('Birds with Arms', 5, NOW()),
('Vore', 2, NOW()),
('1 Lunatic 1 Ice Pick', 3, NOW()),
('Bait and Switch Videos / Pictures', 5, NOW()),
('Sopa de Macaco / Uma Delicia', 1, NOW()),
('Priority Peter', 1, NOW()),
('Oblivious Suburban Mom', 4, NOW()),
('My Disappointment Is Immeasurable', 3, NOW()),
('Sweet Jesus, Pooh! That''s Not Honey!', 5, NOW()),
('Get In The Fucking Robot Shinji', 4, NOW()),
('Name a More Iconic Duo', 5, NOW()),
('Albert Einstein Copypasta', 3, NOW()),
('Big, If True', 4, NOW()),
('Madara Uchiha Copypasta', 1, NOW()),
('Watermelon Headshot', 2, NOW()),
('It''s Just a Prank', 1, NOW()),
('Your Ecards / Someecards.com', 2, NOW()),
('Mitt Romney', 2, NOW()),
('Fluttercry / Characters Watching Tv', 1, NOW()),
('Yaass', 2, NOW()),
('Roller Coaster Chess', 2, NOW()),
('Beep Beep Lettuce', 4, NOW()),
('Mike Inel / Manyakis', 5, NOW()),
('The Worst Trade Deal', 2, NOW()),
('TikTok', 3, NOW()),
('Be Like Bill', 5, NOW()),
('Just Little Things', 4, NOW()),
('"Pen Pineapple Apple Pen"', 2, NOW()),
('That Is Mahogany', 5, NOW()),
('The Hacker Known as 4Chan', 3, NOW()),
('Confused Mr. Krabs', 5, NOW()),
('Gratata', 1, NOW()),
('Steve Rambo Videos / "Oh Shit, I''m Sorry"', 4, NOW()),
('Megami Tensei - Persona', 1, NOW()),
('Mikey Wilson (Middle Finger kid)', 4, NOW()),
('Epstein Didn''t Kill Himself', 3, NOW()),
('Lonelygirl15', 5, NOW()),
('Even Speedwagon Is Afraid!', 2, NOW()),
('Picardía', 5, NOW()),
('Net Neutrality', 3, NOW()),
('Somebody Once Told Me', 5, NOW()),
('The Situation Room', 4, NOW()),
('Dancing Hot Dog Snapchat Filter', 5, NOW()),
('Operation Darknet', 3, NOW()),
('Kill Me', 2, NOW()),
('Who Killed Hannibal?', 4, NOW()),
('Espurr''s Stare', 1, NOW()),
('Slaps Chicken at 3275.95 MPH', 2, NOW()),
('Ebin', 5, NOW()),
('I Want to Cum Inside Rainbow Dash', 5, NOW()),
('Look At Me, I''m The Captain Now', 4, NOW()),
('*Hits Blunt*', 1, NOW()),
('Sweden Yes', 5, NOW()),
('Sauce', 2, NOW()),
('Darth Vader''s Noooooooooooo!', 2, NOW()),
('Oh, Worm?', 5, NOW()),
('The Flying Spaghetti Monster', 2, NOW()),
('Shit Just Got Real', 5, NOW()),
('This Is Snek', 1, NOW()),
('Baton Roue', 2, NOW()),
('How To Draw an Owl', 2, NOW()),
('All Star', 3, NOW()),
('Dark Knight 4 Pane', 1, NOW()),
('Star vs. the Forces of Evil', 1, NOW()),
('Just Go On The Internet and Tell Lies', 3, NOW()),
('7 Grand Dad', 1, NOW()),
('Lurk Moar', 2, NOW()),
('Fake and Gay', 1, NOW()),
('Kitler', 4, NOW()),
('VideoGameDunkey', 3, NOW()),
('Operation Payback', 1, NOW()),
('Oh Baby, a Triple!', 4, NOW()),
('Gar', 2, NOW()),
('DansGame', 3, NOW()),
('Osama Bin Laden''s Death', 4, NOW()),
('Shit, I''m Late For School', 1, NOW()),
('Hello My Future Girlfriend', 3, NOW()),
('France Is Bacon', 5, NOW()),
('Get In The Bag, Nebby', 2, NOW()),
('Scout Face', 5, NOW()),
('Dedotated Wam', 1, NOW()),
('Perfection', 1, NOW()),
('Corona-chan', 3, NOW()),
('Turn 360 Degrees and Walk Away', 4, NOW()),
('Weird Twitter', 3, NOW()),
('You Came to the Wrong Neighborhood', 1, NOW()),
('Smol', 3, NOW()),
('Auto-Tune', 3, NOW()),
('Press X to Jason', 3, NOW()),
('Jesus', 3, NOW()),
('Rip and Tear', 3, NOW()),
('Something Awful', 2, NOW()),
('That Awkward Moment', 4, NOW()),
('Iridocyclitis', 3, NOW()),
('Stawp it, Rahn!', 5, NOW()),
('Snu-Snu', 5, NOW()),
('Despite Being Only 13 Percent of the Population', 4, NOW()),
('I''m About to End This Man''s Whole Career', 1, NOW()),
('Sheeeit', 3, NOW()),
('No Way Fag', 3, NOW()),
('Coaxed Into a Snafu', 2, NOW()),
('Pajama Kid', 4, NOW()),
('Netorare', 1, NOW()),
('Kai the Hatchet-Wielding Hitchhiker', 1, NOW()),
('Internet Explorer', 3, NOW()),
('Stop Bullying Comics', 2, NOW()),
('Listen Here You Little Shit', 1, NOW()),
('I Hope You Step on a LEGO', 4, NOW()),
('Google Search Suggestions', 1, NOW()),
('Solo Jazz Pattern', 4, NOW()),
('Kevin Durant MVP Speech', 5, NOW()),
('ISIS / Daesh', 3, NOW()),
('Ooh Mister Darcy', 1, NOW()),
('Hey Man You See That Guy Over There', 3, NOW()),
('Furry Scale', 5, NOW()),
('I''m OK With This', 1, NOW()),
('Y''all Got Anymore of...', 4, NOW()),
('Taiwan #1', 5, NOW()),
('#CuttingForBieber', 3, NOW()),
('Paul Blart: Mall Cop', 5, NOW()),
('Mishapocalypse', 4, NOW()),
('XD', 4, NOW()),
('I Have The High Ground', 2, NOW()),
('Jesus', 4, NOW()),
('Cheezburger', 2, NOW()),
('Heart-Shaped Boob Challenge', 3, NOW()),
('Rush B', 3, NOW()),
('I Wish I Was At Home', 3, NOW()),
('Pineapple on Pizza Debate', 5, NOW()),
('MaximilianMus "Oh Yeah Yeah"', 2, NOW()),
('Walt Jr. Loves Breakfast', 4, NOW()),
('I Am The Table', 3, NOW()),
('Awaken, My Masters', 4, NOW()),
('Pizza is a Vegetable', 4, NOW()),
('Noot Noot', 1, NOW()),
('Swearing on a Christian Server', 5, NOW()),
('Karma Is a Bitch', 3, NOW()),
('Lemme Smash', 2, NOW()),
('Splat Tim', 5, NOW()),
('We Need To Go Deeper', 3, NOW()),
('eHarmony Video Bio', 3, NOW()),
('Thinking With Portals', 1, NOW()),
('Misinformationalized / You Hear About Video Games?', 5, NOW()),
('DURR PLANT', 2, NOW()),
('First', 3, NOW()),
('Dragon Ball', 1, NOW()),
('Me, An Intellectual', 5, NOW()),
('What If Zelda Was A Girl?', 4, NOW()),
('The Sneaky Hat', 4, NOW()),
('Pretty Girls, Ugly Faces', 2, NOW()),
('It''s Simple, We Kill The Batman', 5, NOW()),
('Another One', 5, NOW()),
('Trivago Guy', 5, NOW()),
('Gru''s Plan', 5, NOW()),
('Y U Do Dis?', 4, NOW()),
('Beyblades eBay Auction', 2, NOW()),
('This is someone dying while having an MRI scan.', 2, NOW()),
('We Can''t Stop Here, This is Bat Country', 5, NOW()),
('@Wendys', 4, NOW()),
('Please Disconnect The Bluetooth Speaker', 3, NOW()),
('UNITINU / UNITIИU', 5, NOW()),
('Spengbab', 5, NOW()),
('Put Some Respeck on My Name', 3, NOW()),
('The Ratio', 4, NOW()),
('Electronic Entertainment Expo (E3)', 5, NOW()),
('Bush Did 9/11', 4, NOW()),
('Michelle Jenneke''s Warm Up Dance', 5, NOW()),
('How-Old.net', 3, NOW()),
('The Simpsons', 2, NOW()),
('No Homo', 2, NOW()),
('PFFFTTTCHH', 1, NOW()),
('Ugly Children Lawsuit Hoax', 4, NOW()),
('Facebook University Meme Pages', 3, NOW()),
('Eccentric Witness Lady / Backin'' Up', 1, NOW()),
('Fake Pokémon Battles', 4, NOW()),
('Sherlock', 2, NOW()),
('MySpace Angles', 5, NOW()),
('The Floor is Lava / Hot Lava Game', 2, NOW()),
('You Laugh, You Lose', 4, NOW()),
('Rawr XD', 4, NOW()),
('Taylor Swift', 4, NOW()),
('David Kalac''s 4chan Murder Confession', 5, NOW()),
('Half-Life', 2, NOW()),
('Greater Internet Fuckwad Theory', 4, NOW()),
('Angry Dog Noises', 4, NOW()),
('I''m Gonna Do What''s Called a Pro Gamer Move', 2, NOW()),
('Internet Death Hoaxes', 4, NOW()),
('Ali-A''s Intro', 5, NOW()),
('¿Quieres?', 1, NOW()),
('Cooking by the Book', 5, NOW()),
('Online Pornography', 4, NOW()),
('Lil Bub', 4, NOW()),
('Are Ya Winning, Son?', 2, NOW()),
('I Want to Believe', 2, NOW()),
('Most People Rejected His Message', 3, NOW()),
('Hoenn Confirmed', 1, NOW()),
('Figwit', 4, NOW()),
('Turn Up the Volume', 5, NOW()),
('"Copy That"', 5, NOW()),
('Welcome to Chili''s', 3, NOW()),
('niconico', 1, NOW()),
('I Didn''t Get No Sleep ''Cause Of Ya''ll', 5, NOW()),
('Stannis the Mannis', 1, NOW()),
('Stupid Sexy Flanders', 4, NOW()),
('Drunk Baby', 3, NOW()),
('Into The Trash It Goes / Opinion Discarded', 5, NOW()),
('Binders Full of Women', 4, NOW()),
('Steam Sales', 1, NOW()),
('Antonio Banderas'' Laptop Reaction', 3, NOW()),
('LOL', 1, NOW()),
('With Great Power Comes Great Responsibility', 3, NOW()),
('NYC Cardstand Earthcam Trolling / "I''ll Be There in 30 Minutes"', 1, NOW()),
('"Bitch I Look Like Goku"', 2, NOW()),
('He Does It for Free', 5, NOW()),
('Jazz Music Stops', 5, NOW()),
('>tfw no gf', 1, NOW()),
('Internet Slang', 4, NOW()),
('Wolverine Crush', 3, NOW()),
('Nyanners', 2, NOW()),
('Like Skyrim With Guns', 5, NOW()),
('Wheelchair Drake', 3, NOW()),
('WataMote / It''s Not My Fault That I''m Not Popular', 2, NOW()),
('Abandon Thread', 4, NOW()),
('Arthur', 4, NOW()),
('Cupcake Dog', 1, NOW()),
('Free Bleeding', 2, NOW()),
('Have You Ever Been So Angry That You...', 1, NOW()),
('BRODYQUEST', 1, NOW()),
('Koichi Pose', 3, NOW()),
('They Took Our Jobs!', 3, NOW()),
('Brotherman Bill', 2, NOW()),
('Trayvon Martin''s Death', 3, NOW()),
('Brazilian Slutwalk Flasher', 3, NOW()),
('Gekyume''s Circumcision', 1, NOW()),
('The Pumpkin Dance', 4, NOW()),
('Chadwardenn', 1, NOW()),
('Breaking Bad', 1, NOW()),
('Emily Faked Cancer', 5, NOW()),
('Ear Rape', 2, NOW()),
('Dubstep', 1, NOW()),
('Snickers "Hungry?" Commercials', 4, NOW()),
('RCDart', 2, NOW()),
('Me Explaining to My Mom', 3, NOW()),
('Homer Simpson Backs Into Bushes', 1, NOW()),
('Mr. Worldwide', 4, NOW()),
('Website Anthropomorphism', 4, NOW()),
('Mehmet My Son', 5, NOW()),
('Mods Are Asleep', 2, NOW()),
('Modern Problems Require Modern Solutions', 5, NOW()),
('The Enigma of Amigara Fault / This Is My Hole', 3, NOW()),
('Duckroll', 1, NOW()),
('Woke', 3, NOW()),
('Imgur', 1, NOW()),
('Webcomics', 2, NOW()),
('Country Girls Make Do', 3, NOW()),
('Vinesauce', 5, NOW()),
('Lolicon', 5, NOW()),
('Simp', 3, NOW()),
('I Forced a Bot', 2, NOW()),
('Michael Rosen', 5, NOW()),
('Choo Choo Motherfucker', 2, NOW()),
('Ran Off Da Plug Twice', 2, NOW()),
('Waiting for OP', 5, NOW()),
('The Nuzlocke Challenge', 2, NOW()),
('Painis Cupcake (Penis Cupcake)', 4, NOW()),
('Kim Jong Il Looking At Things', 2, NOW()),
('Plebcomics', 3, NOW()),
('Impossible is Nothing', 1, NOW()),
('Beanos', 3, NOW()),
('I;m Thinking About Thos Beans', 3, NOW()),
('Over 9000 Penises', 1, NOW()),
('Childhood Enhanced', 3, NOW()),
('When Did This Become Hotter Than This', 1, NOW()),
('Objection!', 2, NOW()),
('Disgustang', 4, NOW()),
('Noice', 2, NOW()),
('LeafyIsHere', 1, NOW()),
('Ironic Memes', 4, NOW()),
('Cool Dog', 5, NOW()),
('Totally Looks Like / Separated At Birth', 3, NOW()),
('Vomit-chan', 3, NOW()),
('Pokémon GO', 4, NOW()),
('Dick Neck', 3, NOW()),
('Stop It Son, You Are Doing Me A Frighten', 3, NOW()),
('The Nutshack', 1, NOW()),
('G.I. Joe PSAs', 2, NOW()),
('Drake', 5, NOW()),
('Bernie Sanders', 2, NOW()),
('True Capitalist Radio', 1, NOW()),
('I''m Commander Shepard', 3, NOW()),
('Captain Hindsight', 4, NOW()),
('DeviantArt', 3, NOW()),
('Salil Sawarim / Saleel al-Sawarim', 2, NOW()),
('More Dakka', 2, NOW()),
('Voiceoverpete', 2, NOW()),
('Redneck Randal', 5, NOW()),
('Horse_ebooks', 3, NOW()),
('Let Me In', 5, NOW()),
('FunnyJunk', 2, NOW()),
('Check Out My Mixtape', 1, NOW()),
('MOAR', 3, NOW()),
('I''ve Made a Huge Mistake', 3, NOW()),
('Nyoro~n', 1, NOW()),
('Because of Parkinson''s', 4, NOW()),
('Outstanding Move / Maravillosa Jugada', 2, NOW()),
('Poe''s Law', 5, NOW()),
('Cinemagraphs', 4, NOW()),
('Ideal GF', 1, NOW()),
('Kamina Glasses', 3, NOW()),
('Hold My Flower', 5, NOW()),
('We Irritating', 1, NOW()),
('Fermi Paradox', 3, NOW()),
('Follow The Damn Train, CJ!', 5, NOW()),
('Sonic For Real Justice', 5, NOW()),
('Mike Wazowski-Sulley Face Swap', 4, NOW()),
('Tails Gets Trolled', 5, NOW()),
('Floating Chinese Government Officials', 2, NOW()),
('Bitches Don''t Know', 1, NOW()),
('Skidaddle Skidoodle Your Dick Is Now a Noodle', 5, NOW()),
('7-day No Fap Challenge', 2, NOW()),
('Floral Shoppe (フローラルの専門店)', 3, NOW()),
('200% Mad', 4, NOW()),
('"Why Is the FBI Here?"', 5, NOW()),
('Smitty Werbenjagermanjensen', 5, NOW()),
('The Warriors Blew a 3-1 Lead', 5, NOW()),
('I Lived Bitch', 5, NOW()),
('Moon''s Haunted', 5, NOW()),
('I Will Now Buy Your Game', 5, NOW()),
('The Miz Girl', 2, NOW()),
('Triple Parentheses / (((Echo)))', 1, NOW()),
('Gag Names', 1, NOW()),
('Vibrating GIFs', 2, NOW()),
('Back to the Future Day', 2, NOW()),
('Never Say No to Panda', 1, NOW()),
('Carlos', 2, NOW()),
('Do You Think This Is a Game?', 4, NOW()),
('Masahiro Sakurai', 1, NOW()),
('Down With Cis', 3, NOW()),
('Inhaling Seagull', 3, NOW()),
('We''ll bang, OK?', 2, NOW()),
('Meme Economy', 5, NOW()),
('Come to Brazil', 4, NOW()),
('The Internet Is For Porn', 4, NOW()),
('The Walking Dead', 1, NOW()),
('Lana Del Rey', 5, NOW()),
('Stoner Comics / Tree Comics', 1, NOW()),
('Me IRL', 1, NOW()),
('Garry''s Mod', 2, NOW()),
('Cockmongler', 4, NOW()),
('Story Time Jesus', 3, NOW()),
('YouTube Comment Memes', 4, NOW()),
('Twilight Sparkle Alicorn Controversy', 3, NOW()),
('Miss Kobayashi''s Dragon Maid', 3, NOW()),
('Sakurafish / Every Day Until You Like It', 1, NOW()),
('Condom Challenge', 5, NOW()),
('CD Emotes', 3, NOW()),
('Gardevoir', 5, NOW()),
('I''m You, But Stronger', 1, NOW()),
('Scumbag Brain', 3, NOW()),
('#NotMyRodrick', 2, NOW()),
('Taxmaster', 4, NOW()),
('They''re Eating Her!', 3, NOW()),
('Leave Britney Alone', 2, NOW()),
('Exodia the Forbidden One', 5, NOW()),
('This is delicious cake', 2, NOW()),
('Ice Cream Cone Guy', 2, NOW()),
('Vagineer', 1, NOW()),
('Casey Anthony Trial', 5, NOW()),
('OMG RUN Guy / Tampon Head Rage Face', 1, NOW()),
('Sco Pa Tu Manaa', 1, NOW()),
('My Brand', 5, NOW()),
('Meme of the Month Calendars', 3, NOW()),
('A Man Has Fallen Into the River in Lego City', 3, NOW()),
('Jaden Smith', 5, NOW()),
('McDonald''s Mulan Szechuan Sauce', 5, NOW()),
('Neon Genesis Evangelion', 5, NOW()),
('Dog Poo Girl', 2, NOW()),
('I Want My Hat Back', 1, NOW()),
('Sakuya''s breast padding', 5, NOW()),
('Throwback Thursday', 3, NOW()),
('Megalovania', 5, NOW()),
('They''re The Same Picture', 3, NOW()),
('They Played Us Like A Damn Fiddle!', 4, NOW()),
('YouTube Automatic Caption FAIL', 2, NOW()),
('Nice Meme', 2, NOW()),
('Dawn of the Final Day', 3, NOW()),
('The Legend of Zelda Timeline Theories', 1, NOW()),
('Nicki Minaj', 4, NOW()),
('Elf on the Shelf', 5, NOW()),
('Anthony Fantano', 2, NOW()),
('But Can You Do This?', 1, NOW()),
('Sexually Oblivious Female', 2, NOW()),
('George Takei Calls Out Anti-Gay School Board Member', 3, NOW()),
('Sky King / Richard Russell', 1, NOW()),
('Miss Me With That Gay Shit', 2, NOW()),
('Donglegate / Adria Richards', 2, NOW()),
('Spirit Pokémon', 5, NOW()),
('Roblox', 4, NOW()),
('Headless Mami', 2, NOW()),
('You Forgot Poland', 1, NOW()),
('Bottom Text', 5, NOW()),
('Vsauce', 2, NOW()),
('I Have Drawn You', 3, NOW()),
('What''s Wrong Big Boy?', 1, NOW()),
('Milo Yiannopoulos', 3, NOW()),
('Krispy Kreme / Froggy Fresh', 1, NOW()),
('I Fear No Man', 5, NOW()),
('Bitches Be Like', 5, NOW()),
('I''m Really Feeling It', 5, NOW()),
('Monkey Haircut', 1, NOW()),
('Why Are You Booing Me? I''m Right', 3, NOW()),
('Cancer', 4, NOW()),
('University of Maryland Sorority E-Mail Rant', 5, NOW()),
('Moe', 4, NOW()),
('Human Bean', 4, NOW()),
('Goblin Slayer', 5, NOW()),
('Evil Toddler', 2, NOW()),
('Can I Be Drawn Better?', 4, NOW()),
('The Gendo Pose', 3, NOW()),
('I Hope Mom and Dad Don''t Find Out', 2, NOW()),
('Pot of Greed', 4, NOW()),
('WHARRGARBL / Sprinkler Dog', 3, NOW()),
('Alt-right', 4, NOW()),
('Tebowing', 4, NOW()),
('Ted Williams / The Golden Voice', 1, NOW()),
('McDonald''s "Ran Ran Ru" Commercial', 1, NOW()),
('Open Eye Crying Laughing Emoji', 2, NOW()),
('Subway Sandwich Porn', 3, NOW()),
('Weaponized Autism', 2, NOW()),
('3DPD', 5, NOW()),
('Dr DisRespect', 3, NOW()),
('That''s just like, your opinion, man', 5, NOW()),
('Surprised Kitty', 2, NOW()),
('Happy Gary', 3, NOW()),
('Paula Deen Riding Things', 1, NOW()),
('Hot Dog Legs', 2, NOW()),
('Holy Shit It''s a Dinosaur!', 1, NOW()),
('Grape Lady', 4, NOW()),
('Fistful of Yen', 5, NOW()),
('Squart Guy', 1, NOW()),
('Sir, This Is an Arby''s', 4, NOW()),
('Folgers "Brother and Sister" Commercial', 4, NOW()),
('Who Killed Captain Alex?', 2, NOW()),
('fgsfds', 1, NOW()),
('Are You Not Entertained?', 5, NOW()),
('Shitlord', 3, NOW()),
('Cone-ing', 3, NOW()),
('Yamero', 5, NOW()),
('Single Topic Blogs', 3, NOW()),
('Angery', 3, NOW()),
('Squidward Fad', 2, NOW()),
('Enjoy Your AIDS', 1, NOW()),
('Vancouver Riot Kiss', 3, NOW()),
('Who''s Awesome? You''re Awesome! / Sos Groso, Sabelo!', 3, NOW()),
('Oh God! I Can See Forever!', 3, NOW()),
('Crossguard Lightsaber', 1, NOW()),
('Cyanide and Happiness', 3, NOW()),
('When Mama Isn''t Home', 4, NOW()),
('Cheems', 3, NOW()),
('Joe Biden', 3, NOW()),
('A Weapon to Surpass Metal Gear', 1, NOW()),
('Markiplier', 4, NOW()),
('Have You Ever Had A Dream Like This?', 2, NOW()),
('2 Guys 1 Fish', 2, NOW()),
('The Floor Is...', 5, NOW()),
('Shitty Charmander', 5, NOW()),
('Tonight''s Big Loser', 4, NOW()),
('Scary Maze Game', 5, NOW()),
('Lewd', 3, NOW()),
('"Millennials Are Killing..."', 4, NOW()),
('Beta Uprising', 1, NOW()),
('Don''t Tase Me Bro!', 4, NOW()),
('Pickup Line Panda', 3, NOW()),
('Chinese Cartoons', 4, NOW()),
('Lauren Phillips Lifting Alice Merchesi', 5, NOW()),
('World of Warcraft', 4, NOW()),
('Team Siren', 2, NOW()),
('Long Boy', 4, NOW()),
('How''d It Get Burned?', 5, NOW()),
('Covfefe', 2, NOW()),
('MissingNo.', 5, NOW()),
('Deadass', 5, NOW()),
('Damn Nature, You Scary!', 4, NOW()),
('Attack on Titan Opening Credits Parodies', 3, NOW()),
('Soraya Montenegro', 1, NOW()),
('Friendship Arsenal', 4, NOW()),
('Once-ler', 1, NOW()),
('Bertstrips', 2, NOW()),
('Mimikyu', 4, NOW()),
('Wanna Sprite Cranberry', 3, NOW()),
('The Emoji Movie', 1, NOW()),
('This Is So Sad', 1, NOW()),
('Vidya', 3, NOW()),
('Red Equal Sign', 2, NOW()),
('Mini Keanu Reeves', 1, NOW()),
('xkcd', 5, NOW()),
('What If We Kissed In', 5, NOW()),
('Bully Hunters', 1, NOW()),
('50 Cent Drive By', 3, NOW()),
('That Fucking Cat', 2, NOW()),
('Stop Trying to Make Fetch Happen', 1, NOW()),
('Internet Hate Machine', 1, NOW()),
('Dammit Jim, I''m a Doctor, Not a X', 5, NOW()),
('Andy'' Sixx''s Log of Shit', 5, NOW()),
('Danbooru', 3, NOW()),
('Fuck This Gay Earth', 3, NOW()),
('The Great Toilet Paper Debate', 3, NOW()),
('The Goggles Do Nothing!', 3, NOW()),
('Miss Teen USA South Carolina', 1, NOW()),
('Rappin'' for Jesus', 3, NOW()),
('Ridley is Too Big', 2, NOW()),
('Curb Your Enthusiasm', 1, NOW()),
('Billie Eilish''s Body Reveal Tour Video', 1, NOW()),
('MOM HOLY FUCK', 2, NOW()),
('Lemon Stealing Whores', 2, NOW()),
('Anarcho-Capitalism', 4, NOW()),
('Nickelback''s "Photograph"', 5, NOW()),
('Squidward Dab', 5, NOW()),
('Yesn''t', 3, NOW()),
('Grand Theft Auto', 1, NOW()),
('Drinking Out of Cups', 4, NOW()),
('Sonic the Hedgehog (2020 Film)', 4, NOW()),
('Art Student Owl', 4, NOW());

\c postgres