// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { VideoOff } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconVideoOff(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={VideoOff} {...props} />
}

export default IconVideoOff
