// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Thermometer } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconThermometer(props: any) {
    return <IconBase icon={Thermometer} {...props} />
  }

  export default IconThermometer
  