// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconPackage(props: IconProps) {
  return <Icon type="Package" {...props} />
}

export default IconPackage
