// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconThumbsDown(props: IconProps) {
  return <Icon type="ThumbsDown" {...props} />
}

export default IconThumbsDown
