// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconCalendar(props: IconProps) {
  return <Icon type="Calendar" {...props} />
}

export default IconCalendar
