// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { CornerLeftUp } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconCornerLeftUp(props: any) {
    return <IconBase icon={CornerLeftUp} {...props} />
  }

  export default IconCornerLeftUp
  