// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Minimize } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconMinimize(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Minimize} {...props} />
}

export default IconMinimize
