// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconFrown(props: IconProps) {
  return <Icon type="Frown" {...props} />
}

export default IconFrown
