// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconHeadphones(props: IconProps) {
  return <Icon type="Headphones" {...props} />
}

export default IconHeadphones
