// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Headphones } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconHeadphones(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Headphones} {...props} />
}

export default IconHeadphones
