// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconStar(props: IconProps) {
  return <Icon type="Star" {...props} />
}

export default IconStar
