// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Link2 } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconLink2(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Link2} {...props} />
}

export default IconLink2
