// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconLink2(props: IconProps) {
  return <Icon type="Link2" {...props} />
}

export default IconLink2
