- name: UFW - Allow connections to GoTrue metrics exporter
  community.general.ufw:
    port: '9122'
    rule: 'allow'
    
# use this user for the Gotrue build and for running the service
- name: Gotrue - group
  ansible.builtin.group:
    name: gotrue
    gid: 1006
    state: present

- name: Gotrue - system user
  ansible.builtin.user:
    name: gotrue
    uid: "{{ 1001 if not qemu else 1002 }}"
    group: gotrue
    state: present

- name: gotrue - download commit archive
  ansible.builtin.get_url:
    url: "{{ gotrue_artifacts[platform]['url'] }}"
    checksum: "{{ gotrue_artifacts[platform]['checksum'] }}"
    dest: '/tmp/gotrue.tar.gz'
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 2

- name: gotrue - create /opt/gotrue and /etc/auth.d
  ansible.builtin.file:
    mode: '0775'
    owner: 'gotrue'
    path: "{{ gotrue_dir_item }}"
    state: 'directory'
  loop:
    - '/etc/auth.d'
    - '/opt/gotrue'
  loop_control:
    loop_var: 'gotrue_dir_item'

- name: gotrue - unpack archive in /opt/gotrue
  ansible.builtin.unarchive:
    dest: '/opt/gotrue'
    owner: 'gotrue'
    remote_src: true
    src: '/tmp/gotrue.tar.gz'

# libpq is a C library that enables user programs to communicate with
# the PostgreSQL database server.
# - name: gotrue - system dependencies
#   apt:
#     pkg:
#       - libpq-dev

- name: gotrue - create service file
  ansible.builtin.template:
    dest: '/etc/systemd/system/gotrue.service'
    src: 'files/gotrue.service.j2'

- name: gotrue - create optimizations file
  ansible.builtin.template:
    dest: '/etc/systemd/system/gotrue-optimizations.service'
    src: 'files/gotrue-optimizations.service.j2'

- name: gotrue - reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
