// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { ZoomOut } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconZoomOut(props: any) {
    return <IconBase icon={ZoomOut} {...props} />
  }

  export default IconZoomOut
  