import { STRIPE_PRODUCT_IDS } from 'lib/constants'

// This file will get deleted soon and superseded by components in BillingV2/*

export const PRICING_META = {
  [STRIPE_PRODUCT_IDS.FREE]: {
    id: 'tier_free',
    new: false,
    name: 'Free',
    description: 'Perfect for passion projects & simple websites.',
    priceMonthly: 0,
    priceUnit: '/ month',
    warning: 'Limit of 2 free projects',
    preface: 'Get started with:',
    features: [
      'Unlimited API requests',
      'Social OAuth providers',
      'Up to 500MB database space',
      'Up to 1GB file storage',
      'Up to 2GB bandwidth',
      'Up to 50MB file uploads',
      'Up to 50,000 monthly active users',
      'Up to 500K Edge Function invocations',
      'Up to 200 concurrent Realtime connections',
      'Up to 2 million Realtime messages',
      '1-day log retention',
      'Community support',
    ],
    scale: 'Free projects are paused after 1 week of inactivity.',
  },
  [STRIPE_PRODUCT_IDS.PRO]: {
    id: 'tier_pro',
    new: false,
    name: 'Pro',
    description: 'For production applications with the option to scale.',
    priceMonthly: 25,
    priceUnit: '/ month',
    warning: 'Usage-based plan',
    preface: 'Everything in the Free plan, plus:',
    features: [
      'No project pausing',
      'Daily backups stored for 7 days',
      '8GB database space included',
      '100GB file storage included',
      '50GB bandwidth included',
      '5GB file uploads included',
      '100,000 monthly active users included',
      '2M Edge Function invocations included',
      '500 concurrent Realtime connections included',
      '5 million Realtime messages included',
      '7-day log retention',
      'Email support',
    ],
  },
  [STRIPE_PRODUCT_IDS.TEAM]: {
    id: 'tier_team',
    new: true,
    name: 'Team',
    description: 'Collaborate with different permissions and access patterns.',
    priceMonthly: 599,
    priceUnit: '/ month',
    warning: 'Usage-based plan',
    preface: 'Everything in the Pro plan, plus:',
    features: [
      'Additional Organization member roles',
      'Daily backups stored for 14 days',
      'Standardised Security Questionnaire',
      'SOC2',
      'SSO for Supabase Dashboard',
      'Priority email support & SLAs',
      '28-day log retention',
    ],
  },
  Enterprise: {
    id: 'tier_enterprise',
    new: false,
    name: 'Enterprise',
    href: '/contact/enterprise',
    description: 'For large-scale applications managing serious workloads.',
    priceMonthly: undefined,
    features: [
      `Designated Support manager & SLAs`,
      `Enterprise OAuth providers`,
      `SSO/SAML`,
      `On-premise support`,
      `24×7×365 premium enterprise support`,
      `Private Slack channel`,
    ],
  },
}
