// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconCloudDrizzle(props: IconProps) {
  return <Icon type="CloudDrizzle" {...props} />
}

export default IconCloudDrizzle
