GET http://postgrest/
Prefer: tx=commit

HEAD http://postgrest/actors?actor=eq.1
Prefer: tx=commit

GET http://postgrest/actors?select=*,roles(*,films(*))
Prefer: tx=commit

POST http://postgrest/films?columns=id,title
Prefer: tx=rollback
@post.json

POST http://postgrest/films?columns=id,title,year,runtime,genres,director,actors,plot,posterUrl
Prefer: tx=rollback
# this bulk.json was obtained from https://github.com/erik-sytnyk/movies-list/blob/master/db.json
@bulk.json

PUT http://postgrest/actors?actor=eq.1&columns=name
Prefer: tx=rollback
@put.json

PATCH http://postgrest/actors?actor=eq.1
Prefer: tx=rollback
@patch.json

DELETE http://postgrest/roles
Prefer: tx=rollback

GET http://postgrest/rpc/call_me?name=John

POST http://postgrest/rpc/call_me
@rpc.json

OPTIONS http://postgrest/actors

# Misspelled relations
GET http://postgrest/actoxs?actor=eq.1
Prefer: tx=commit

# Misspelled relations on embeds
GET http://postgrest/actors?select=*,rolws(*,films(*))
Prefer: tx=commit

# Misspelled function names
GET http://postgrest/rpc/call_me_x?name=John
Prefer: tx=commit

# Permission denied errors
GET http://postgrest/actors_1
Prefer: tx=commit
