-- testing sql found in https://supabase.com/docs/guides/database/indexes

create table persons (
  id bigint generated by default as identity primary key,
  age int,
  height int,
  weight int,
  name text,
  deceased boolean
);

insert into persons (age, height, weight, name, deceased) values (32, 180, 70, 'John Doe', false);

select name from persons where age = 32;

create index idx_persons_age on persons (age);

create index idx_living_persons_age on persons (age) where deceased is false;

create index idx_persons_age_desc on persons (age desc nulls last);

reindex index concurrently idx_persons_age;

reindex table concurrently persons;

drop table persons cascade;
