// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Feather } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconFeather(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Feather} {...props} />
}

export default IconFeather
