// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconChevronsUp(props: IconProps) {
  return <Icon type="ChevronsUp" {...props} />
}

export default IconChevronsUp
