// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { ChevronsUp } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconChevronsUp(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={ChevronsUp} {...props} />
}

export default IconChevronsUp
