// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconBatteryCharging(props: IconProps) {
  return <Icon type="BatteryCharging" {...props} />
}

export default IconBatteryCharging
