// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Framer } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconFramer(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Framer} {...props} />
}

export default IconFramer
