// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconChevronUp(props: IconProps) {
  return <Icon type="ChevronUp" {...props} />
}

export default IconChevronUp
