// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { ChevronUp } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconChevronUp(props: any) {
    return <IconBase icon={ChevronUp} {...props} />
  }

  export default IconChevronUp
  