// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Wind } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconWind(props: any) {
    return <IconBase icon={Wind} {...props} />
  }

  export default IconWind
  