// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconPhone(props: IconProps) {
  return <Icon type="Phone" {...props} />
}

export default IconPhone
