// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Instagram } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconInstagram(props: any) {
    return <IconBase icon={Instagram} {...props} />
  }

  export default IconInstagram
  