// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Slack } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconSlack(props: any) {
    return <IconBase icon={Slack} {...props} />
  }

  export default IconSlack
  