name: Mirror Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image tag'
        required: true
        type: string

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ secrets.PROD_AWS_ROLE }}
          aws-region: us-east-1
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: public.ecr.aws
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: akhilerm/tag-push-action@f35ff2cb99d407368b5c727adbcc14a2ed81d509 # v2.2.0
        with:
          src: docker.io/supabase/postgres-meta:${{ inputs.version }}
          dst: |
            public.ecr.aws/supabase/postgres-meta:${{ inputs.version }}
            ghcr.io/supabase/postgres-meta:${{ inputs.version }}
