// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Type } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconType(props: any) {
    return <IconBase icon={Type} {...props} />
  }

  export default IconType
  