// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { GitCommit } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconGitCommit(props: any) {
    return <IconBase icon={GitCommit} {...props} />
  }

  export default IconGitCommit
  