// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Volume2 } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconVolume2(props: any) {
    return <IconBase icon={Volume2} {...props} />
  }

  export default IconVolume2
  