// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { TrendingUp } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconTrendingUp(props: any) {
    return <IconBase icon={TrendingUp} {...props} />
  }

  export default IconTrendingUp
  