// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconCreditCard(props: IconProps) {
  return <Icon type="CreditCard" {...props} />
}

export default IconCreditCard
