// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { CreditCard } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconCreditCard(props: any) {
    return <IconBase icon={CreditCard} {...props} />
  }

  export default IconCreditCard
  