// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconThumbsUp(props: IconProps) {
  return <Icon type="ThumbsUp" {...props} />
}

export default IconThumbsUp
