#!/usr/bin/env python3
"""
Generate Envoy CDS (Cluster Discovery Service) configuration from the database registry.
Produces clusters for both auth (GoTrue) and rest (PostgREST) per database.

Usage: python3 scripts/generate-envoy-clusters.py > docker/volumes/api/envoy/cds.yaml
"""
import json
import os
import yaml

registry_path = os.environ.get(
    "DATABASE_REGISTRY_PATH",
    "docker/volumes/registry/databases.json"
)

with open(registry_path) as f:
    registry = json.load(f)

databases = registry["databases"]

base = {
    "resources": []
}

for db in databases:
    ref = db["ref"]

    # Auth (GoTrue) cluster
    auth_cluster = {
        "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
        "name": f"auth-{ref}",
        "type": "STRICT_DNS",
        "connect_timeout": "15s",
        "dns_lookup_family": "V4_ONLY",
        "lb_policy": "ROUND_ROBIN",
        "load_assignment": {
            "cluster_name": f"auth-{ref}",
            "endpoints": [{
                "lb_endpoints": [{
                    "endpoint": {
                        "address": {
                            "socket_address": {
                                "address": f"supabase-auth-{ref}",
                                "port_value": 9999
                            }
                        }
                    }
                }]
            }]
        }
    }
    base["resources"].append(auth_cluster)

    # Rest (PostgREST) cluster
    rest_cluster = {
        "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
        "name": f"rest-{ref}",
        "type": "STRICT_DNS",
        "connect_timeout": "15s",
        "dns_lookup_family": "V4_ONLY",
        "lb_policy": "ROUND_ROBIN",
        "load_assignment": {
            "cluster_name": f"rest-{ref}",
            "endpoints": [{
                "lb_endpoints": [{
                    "endpoint": {
                        "address": {
                            "socket_address": {
                                "address": f"supabase-rest-{ref}",
                                "port_value": 3000
                            }
                        }
                    }
                }]
            }]
        }
    }
    base["resources"].append(rest_cluster)

print("# Auto-generated by scripts/generate-envoy-clusters.py")
print("# Do not edit manually - regenerate with: python3 scripts/generate-envoy-clusters.py")
print(yaml.dump(base, default_flow_style=False, allow_unicode=True))