#!/usr/bin/env python3
"""Generate per-database Storage service definitions (Option B — full isolation).

Reads the database registry and emits a docker-compose override file that runs
one supabase/storage-api container per database, each with its own TENANT_ID
and DATABASE_URL pointing to the correct PostgreSQL instance.

Usage:
    python3 scripts/generate-compose-storage.py > docker/docker-compose.storage.yml

    # Bring up with overrides:
    docker compose -f docker/docker-compose.yml -f docker/docker-compose.storage.yml up -d

Environment:
    DATABASE_REGISTRY_PATH  Path to databases.json (default: docker/volumes/registry/databases.json)
    STORAGE_IMAGE           Storage API image tag (default: supabase/storage-api:v1.22.25)
"""

import json
import os
import sys

REGISTRY_PATH = os.environ.get(
    "DATABASE_REGISTRY_PATH",
    "docker/volumes/registry/databases.json"
)

# Match the image version pinned in docker/docker-compose.yml
STORAGE_IMAGE = os.environ.get("STORAGE_IMAGE", "supabase/storage-api:v1.22.25")

# ── Load registry ─────────────────────────────────────────────────────────────
try:
    with open(REGISTRY_PATH) as f:
        registry = json.load(f)
except FileNotFoundError:
    print(f"Error: registry not found at {REGISTRY_PATH}", file=sys.stderr)
    print("Run from the supabase/ directory or set DATABASE_REGISTRY_PATH.", file=sys.stderr)
    sys.exit(1)

databases = registry.get("databases", [])
if not databases:
    print("Error: registry has no databases entries.", file=sys.stderr)
    sys.exit(1)

# ── Output ────────────────────────────────────────────────────────────────────
lines = [
    "# Auto-generated by scripts/generate-compose-storage.py",
    "# DO NOT EDIT — regenerate with: python3 scripts/generate-compose-storage.py",
    "",
    "services:",
]

for db in databases:
    ref          = db["ref"]
    password_env = db.get("password_env", "POSTGRES_PASSWORD")
    jwt_env      = db.get("jwt_secret_env", "JWT_SECRET")
    anon_env     = db.get("anon_key_env",    "ANON_KEY")
    service_env  = db.get("service_key_env", "SERVICE_ROLE_KEY")
    host         = db.get("host", "db")
    port         = db.get("port", 5432)
    database     = db.get("database", "postgres")

    # Only add supabase_network_{ref} if it's a different network than the default
    ref_network = f"supabase_network_{ref}"
    extra_network = [] if ref_network == "supabase_network_default" else [f"      - {ref_network}"]

    lines += [
        f"  storage-{ref}:",
        f"    container_name: supabase-storage-{ref}",
        f"    image: {STORAGE_IMAGE}",
        f"    restart: unless-stopped",
        f"    depends_on:",
        f"      db:",
        f"        condition: service_healthy",
        f"    environment:",
        f"      ANON_KEY: ${{{anon_env}}}",
        f"      SERVICE_KEY: ${{{service_env}}}",
        f"      POSTGREST_URL: http://rest-{ref}:3000",
        f"      PGRST_JWT_SECRET: ${{{jwt_env}}}",
        f'      DATABASE_URL: "postgresql://supabase_storage_admin:${{{password_env}}}@{host}:{port}/{database}"',
        f"      FILE_SIZE_LIMIT: ${{FILE_SIZE_LIMIT:-52428800}}",
        f"      STORAGE_BACKEND: ${{STORAGE_BACKEND:-file}}",
        f"      FILE_STORAGE_BACKEND_PATH: /var/lib/storage",
        f'      TENANT_ID: "{ref}"',
        f"      GLOBAL_S3_BUCKET: ${{STORAGE_S3_BUCKET:-supabase-storage}}",
        f"      REGION: ${{STORAGE_S3_REGION:-us-east-1}}",
        f"      GLOBAL_S3_ENDPOINT: ${{STORAGE_S3_ENDPOINT:-}}",
        f"      AWS_ACCESS_KEY_ID: ${{STORAGE_S3_KEY_ID:-}}",
        f"      AWS_SECRET_ACCESS_KEY: ${{STORAGE_S3_ACCESS_KEY:-}}",
        f"      ENABLE_IMAGE_TRANSFORMATION: ${{IMGPROXY_ENABLE_WEBP_DETECTION:-true}}",
        f"      IMGPROXY_URL: http://imgproxy:5001",
        f"      PGSSLMODE: ${{PGSSLMODE:-disable}}",
        f"    volumes:",
        f"      - ./volumes/storage/{ref}:/var/lib/storage:z",
        f"    networks:",
        f"      - supabase_network_default",
    ] + extra_network + [
        f"    healthcheck:",
        f"      test: [\"CMD\", \"wget\", \"--no-verbose\", \"--tries=1\", \"--spider\", \"http://localhost:5000/status\"]",
        f"      timeout: 5s",
        f"      interval: 5s",
        f"      retries: 3",
        f"",
    ]

# Declare networks so the override is self-contained (deduplicate)
seen_networks = set()
network_lines = ["networks:"]

def add_network(name: str) -> None:
    if name not in seen_networks:
        seen_networks.add(name)
        network_lines.append(f"  {name}:")
        network_lines.append(f"    external: true")
        network_lines.append(f"    name: {name}")

# supabase_network_default is always needed
add_network("supabase_network_default")
for db in databases:
    ref = db["ref"]
    add_network(f"supabase_network_{ref}")

network_lines.append("")
lines += network_lines

print("\n".join(lines))