local all  supabase_admin     scram-sha-256
local all  all                peer map=supabase_map

host  authdbsupabase all  127.0.0.1/32 scram-sha-256
host  authdbsupabase all  ::1/128 scram-sha-256

host  all  pgbouncer 0.0.0.0/0   scram-sha-256
host  all  supabase_admin 0.0.0.0/0   scram-sha-256

hostnossl  all  all  0.0.0.0/0    scram-sha-256
hostnossl  all  all  ::0/0        scram-sha-256
hostssl  all  all  0.0.0.0/0    pam
hostssl  all  all  ::0/0    pam
