-- Role-based access control with JWT custom claims.
-- See: https://supabase.com/docs/guides/api/custom-claims-and-role-based-access-control-rbac

create type public.app_permission as enum (
  'items.read',
  'items.write',
  'items.delete',
  'admin.access'
);

create type public.app_role as enum ('admin', 'moderator', 'member');

create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  role public.app_role not null,
  unique (user_id, role)
);

comment on table public.user_roles is 'Application roles assigned to each user.';

create table public.role_permissions (
  id bigint generated by default as identity primary key,
  role public.app_role not null,
  permission public.app_permission not null,
  unique (role, permission)
);

comment on table public.role_permissions is 'Permissions granted to each application role.';

create or replace function public.authorize(requested_permission public.app_permission)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  bind_permissions int;
  user_role public.app_role;
begin
  select (auth.jwt() ->> 'user_role')::public.app_role into user_role;

  select count(*)
  into bind_permissions
  from public.role_permissions
  where role_permissions.permission = requested_permission
    and role_permissions.role = user_role;

  return bind_permissions > 0;
end;
$$;

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  select role
  into user_role
  from public.user_roles
  where user_id = (event ->> 'user_id')::uuid
  order by
    case role
      when 'admin' then 1
      when 'moderator' then 2
      else 3
    end
  limit 1;

  claims := event -> 'claims';

  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  else
    claims := jsonb_set(claims, '{user_role}', 'null');
  end if;

  return jsonb_set(event, '{claims}', claims);
end;
$$;

grant usage on schema public to supabase_auth_admin;

grant execute on function public.custom_access_token_hook to supabase_auth_admin;

revoke execute on function public.custom_access_token_hook
from authenticated, anon, public;

grant all on table public.user_roles to supabase_auth_admin;

revoke all on table public.user_roles from authenticated, anon, public;

alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;

create policy "Allow auth admin to read user roles"
on public.user_roles
as permissive
for select
to supabase_auth_admin
using (true);

create policy "Allow authenticated read access to role permissions"
on public.role_permissions
for select
to authenticated
using (true);

-- Example protected table using authorize()
create table public.items (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users on delete cascade not null,
  title text not null,
  created_at timestamptz default now()
);

alter table public.items enable row level security;

create policy "Allow authenticated read access"
on public.items
for select
to authenticated
using (true);

create policy "Allow owners to insert items"
on public.items
for insert
to authenticated
with check (auth.uid() = owner_id);

create policy "Allow owners to update items"
on public.items
for update
to authenticated
using (auth.uid() = owner_id);

create policy "Allow authorized delete access"
on public.items
for delete
to authenticated
using ((select public.authorize('items.delete')));
