# Generated by Django 4.0.5 on 2022-07-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='photo',
            field=models.FileField(default=None, upload_to='photos'),
        ),
    ]
