_format_version: "1.1"
services:
-   name: auth-v1
    _comment: 'GoTrue: /auth/v1/* -> http://auth:9999/*'
    url: http://auth:9999/
    routes:
    -   name: auth-v1-all
        strip_path: true
        paths:
        - /auth/v1/
    plugins:
    -   name: cors
    -   name: key-auth
        config:
            hide_credentials: true
-   name: rest-v1
    _comment: 'PosgREST: /rest/v1/* -> http://rest:3000/*'
    url: http://rest:3000/
    routes:
    -   name: rest-v1-all
        strip_path: true
        paths:
        - /rest/v1/
    plugins:
    -   name: cors
    -   name: key-auth
        config:
            hide_credentials: true
-   name: realtime-v1
    _comment: 'Realtime: /realtime/v1/* -> ws://realtime:4000/socket/*'
    url: http://realtime:4000/socket/
    routes:
    -   name: realtime-v1-all
        strip_path: true
        paths:
        - /realtime/v1/
    plugins:
    -   name: cors
    -   name: key-auth
        config:
            hide_credentials: true
consumers:
-   username: 'private-key'
    keyauth_credentials:
    -   key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJhdWQiOiIiLCJzdWIiOiIiLCJSb2xlIjoicG9zdGdyZXMifQ.magCcozTMKNrl76Tj2dsM7XTl_YH0v0ilajzAvIlw3U
