// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconPhoneOff(props: IconProps) {
  return <Icon type="PhoneOff" {...props} />
}

export default IconPhoneOff
