// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { PhoneOff } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconPhoneOff(props: any) {
    return <IconBase icon={PhoneOff} {...props} />
  }

  export default IconPhoneOff
  