// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconEdit3(props: IconProps) {
  return <Icon type="Edit3" {...props} />
}

export default IconEdit3
