// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconCode(props: IconProps) {
  return <Icon type="Code" {...props} />
}

export default IconCode
