// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconZapOff(props: IconProps) {
  return <Icon type="ZapOff" {...props} />
}

export default IconZapOff
