// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { ZapOff } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconZapOff(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={ZapOff} {...props} />
}

export default IconZapOff
