import './globals.css'
import dynamic from 'next/dynamic'

const DynamicSyntaxHighlighter = dynamic(() => import('react-syntax-highlighter'))

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <DynamicSyntaxHighlighter language="javascript">
          {children}
        </DynamicSyntaxHighlighter>
      </body>
    </html>
  )
}
