// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { MinusCircle } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconMinusCircle(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={MinusCircle} {...props} />
}

export default IconMinusCircle
