// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconMinusCircle(props: IconProps) {
  return <Icon type="MinusCircle" {...props} />
}

export default IconMinusCircle
