// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconPlayCircle(props: IconProps) {
  return <Icon type="PlayCircle" {...props} />
}

export default IconPlayCircle
