// AUTO-GENERATED by scripts/gen-lucide-icons.mjs — do not edit by hand.
// Curated Lucide icons (ISC license) in SeedIcon shape. Re-run the script to update.
import type { SeedIcon } from '@/lib/assets/seed-icons'

export const LUCIDE_ICONS: SeedIcon[] = [
  {
    "name": "server",
    "label": "Server",
    "tags": [
      "server",
      "backend",
      "host",
      "compute",
      "deployment",
      "infrastructure",
      "api"
    ],
    "viewBox": "0 0 24 24",
    "body": "<rect width=\"20\" height=\"8\" x=\"2\" y=\"2\" rx=\"2\" ry=\"2\" /> <rect width=\"20\" height=\"8\" x=\"2\" y=\"14\" rx=\"2\" ry=\"2\" /> <line x1=\"6\" x2=\"6.01\" y1=\"6\" y2=\"6\" /> <line x1=\"6\" x2=\"6.01\" y1=\"18\" y2=\"18\" />"
  },
  {
    "name": "cloud",
    "label": "Cloud",
    "tags": [
      "cloud",
      "hosting",
      "saas",
      "storage",
      "backup",
      "platform"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z\" />"
  },
  {
    "name": "shield",
    "label": "Shield",
    "tags": [
      "security",
      "protection",
      "safe",
      "defense",
      "trust",
      "compliance"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z\" />"
  },
  {
    "name": "shield-check",
    "label": "Shield check",
    "tags": [
      "security",
      "verified",
      "compliance",
      "audit",
      "trust",
      "soc2"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z\" /> <path d=\"m9 12 2 2 4-4\" />"
  },
  {
    "name": "key",
    "label": "Key",
    "tags": [
      "auth",
      "api key",
      "secret",
      "credentials",
      "access",
      "token",
      "authentication"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4\" /> <path d=\"m21 2-9.6 9.6\" /> <circle cx=\"7.5\" cy=\"15.5\" r=\"5.5\" />"
  },
  {
    "name": "users",
    "label": "Users",
    "tags": [
      "team",
      "users",
      "collaboration",
      "community",
      "accounts",
      "multiplayer"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" /> <path d=\"M16 3.128a4 4 0 0 1 0 7.744\" /> <path d=\"M22 21v-2a4 4 0 0 0-3-3.87\" /> <circle cx=\"9\" cy=\"7\" r=\"4\" />"
  },
  {
    "name": "user",
    "label": "User",
    "tags": [
      "user",
      "account",
      "profile",
      "identity",
      "auth",
      "session"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2\" /> <circle cx=\"12\" cy=\"7\" r=\"4\" />"
  },
  {
    "name": "code",
    "label": "Code",
    "tags": [
      "code",
      "developer",
      "programming",
      "snippet",
      "api",
      "sdk"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m16 18 6-6-6-6\" /> <path d=\"m8 6-6 6 6 6\" />"
  },
  {
    "name": "terminal",
    "label": "Terminal",
    "tags": [
      "cli",
      "terminal",
      "command",
      "shell",
      "devtools",
      "console"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M12 19h8\" /> <path d=\"m4 17 6-6-6-6\" />"
  },
  {
    "name": "git-branch",
    "label": "Branch",
    "tags": [
      "git",
      "branch",
      "version control",
      "workflow",
      "ci",
      "preview"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M15 6a9 9 0 0 0-9 9V3\" /> <circle cx=\"18\" cy=\"6\" r=\"3\" /> <circle cx=\"6\" cy=\"18\" r=\"3\" />"
  },
  {
    "name": "cpu",
    "label": "CPU",
    "tags": [
      "compute",
      "performance",
      "processing",
      "hardware",
      "cpu",
      "edge"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M12 20v2\" /> <path d=\"M12 2v2\" /> <path d=\"M17 20v2\" /> <path d=\"M17 2v2\" /> <path d=\"M2 12h2\" /> <path d=\"M2 17h2\" /> <path d=\"M2 7h2\" /> <path d=\"M20 12h2\" /> <path d=\"M20 17h2\" /> <path d=\"M20 7h2\" /> <path d=\"M7 20v2\" /> <path d=\"M7 2v2\" /> <rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" /> <rect x=\"8\" y=\"8\" width=\"8\" height=\"8\" rx=\"1\" />"
  },
  {
    "name": "network",
    "label": "Network",
    "tags": [
      "network",
      "connections",
      "graph",
      "distributed",
      "mesh",
      "topology"
    ],
    "viewBox": "0 0 24 24",
    "body": "<rect x=\"16\" y=\"16\" width=\"6\" height=\"6\" rx=\"1\" /> <rect x=\"2\" y=\"16\" width=\"6\" height=\"6\" rx=\"1\" /> <rect x=\"9\" y=\"2\" width=\"6\" height=\"6\" rx=\"1\" /> <path d=\"M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3\" /> <path d=\"M12 12V8\" />"
  },
  {
    "name": "box",
    "label": "Box",
    "tags": [
      "package",
      "container",
      "box",
      "bundle",
      "storage",
      "object"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z\" /> <path d=\"m3.3 7 8.7 5 8.7-5\" /> <path d=\"M12 22V12\" />"
  },
  {
    "name": "package",
    "label": "Package",
    "tags": [
      "package",
      "module",
      "library",
      "dependency",
      "release",
      "bundle"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z\" /> <path d=\"M12 22V12\" /> <polyline points=\"3.29 7 12 12 20.71 7\" /> <path d=\"m7.5 4.27 9 5.15\" />"
  },
  {
    "name": "activity",
    "label": "Activity",
    "tags": [
      "analytics",
      "monitoring",
      "metrics",
      "activity",
      "observability",
      "logs",
      "uptime"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2\" />"
  },
  {
    "name": "chart-column",
    "label": "Chart",
    "tags": [
      "analytics",
      "chart",
      "metrics",
      "dashboard",
      "stats",
      "reporting",
      "growth"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M3 3v16a2 2 0 0 0 2 2h16\" /> <path d=\"M18 17V9\" /> <path d=\"M13 17V5\" /> <path d=\"M8 17v-3\" />"
  },
  {
    "name": "search",
    "label": "Search",
    "tags": [
      "search",
      "query",
      "find",
      "discovery",
      "full text",
      "index",
      "lookup"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m21 21-4.34-4.34\" /> <circle cx=\"11\" cy=\"11\" r=\"8\" />"
  },
  {
    "name": "bell",
    "label": "Bell",
    "tags": [
      "notifications",
      "alerts",
      "webhooks",
      "events",
      "reminders"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M10.268 21a2 2 0 0 0 3.464 0\" /> <path d=\"M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326\" />"
  },
  {
    "name": "mail",
    "label": "Mail",
    "tags": [
      "email",
      "mail",
      "messaging",
      "notifications",
      "transactional",
      "smtp"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7\" /> <rect x=\"2\" y=\"4\" width=\"20\" height=\"16\" rx=\"2\" />"
  },
  {
    "name": "folder",
    "label": "Folder",
    "tags": [
      "storage",
      "files",
      "folder",
      "buckets",
      "organization",
      "objects"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z\" />"
  },
  {
    "name": "file-text",
    "label": "File",
    "tags": [
      "file",
      "document",
      "content",
      "docs",
      "text",
      "markdown"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" /> <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /> <path d=\"M10 9H8\" /> <path d=\"M16 13H8\" /> <path d=\"M16 17H8\" />"
  },
  {
    "name": "settings",
    "label": "Settings",
    "tags": [
      "settings",
      "config",
      "configuration",
      "controls",
      "preferences",
      "options"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915\" /> <circle cx=\"12\" cy=\"12\" r=\"3\" />"
  },
  {
    "name": "webhook",
    "label": "Webhook",
    "tags": [
      "webhook",
      "events",
      "integration",
      "api",
      "callback",
      "trigger"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M18 16.98h-5.99c-1.1 0-1.95.94-2.48 1.9A4 4 0 0 1 2 17c.01-.7.2-1.4.57-2\" /> <path d=\"m6 17 3.13-5.78c.53-.97.1-2.18-.5-3.1a4 4 0 1 1 6.89-4.06\" /> <path d=\"m12 6 3.13 5.73C15.66 12.7 16.9 13 18 13a4 4 0 0 1 0 8\" />"
  },
  {
    "name": "workflow",
    "label": "Workflow",
    "tags": [
      "workflow",
      "automation",
      "pipeline",
      "orchestration",
      "jobs",
      "queue"
    ],
    "viewBox": "0 0 24 24",
    "body": "<rect width=\"8\" height=\"8\" x=\"3\" y=\"3\" rx=\"2\" /> <path d=\"M7 11v4a2 2 0 0 0 2 2h4\" /> <rect width=\"8\" height=\"8\" x=\"13\" y=\"13\" rx=\"2\" />"
  },
  {
    "name": "bot",
    "label": "Bot",
    "tags": [
      "ai",
      "bot",
      "agent",
      "assistant",
      "automation",
      "llm",
      "chat"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M12 8V4H8\" /> <rect width=\"16\" height=\"12\" x=\"4\" y=\"8\" rx=\"2\" /> <path d=\"M2 14h2\" /> <path d=\"M20 14h2\" /> <path d=\"M15 13v2\" /> <path d=\"M9 13v2\" />"
  },
  {
    "name": "sparkles",
    "label": "Sparkles",
    "tags": [
      "ai",
      "magic",
      "generate",
      "new",
      "launch",
      "features",
      "smart"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z\" /> <path d=\"M20 2v4\" /> <path d=\"M22 4h-4\" /> <circle cx=\"4\" cy=\"20\" r=\"2\" />"
  },
  {
    "name": "rocket",
    "label": "Rocket",
    "tags": [
      "launch",
      "ship",
      "release",
      "startup",
      "growth",
      "deploy"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5\" /> <path d=\"M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09\" /> <path d=\"M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z\" /> <path d=\"M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05\" />"
  },
  {
    "name": "plug",
    "label": "Plug",
    "tags": [
      "integration",
      "connect",
      "plugin",
      "extension",
      "connector",
      "api"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M12 22v-5\" /> <path d=\"M15 8V2\" /> <path d=\"M17 8a1 1 0 0 1 1 1v4a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1z\" /> <path d=\"M9 8V2\" />"
  },
  {
    "name": "lock-keyhole",
    "label": "Lock keyhole",
    "tags": [
      "security",
      "private",
      "encryption",
      "rls",
      "access",
      "protected"
    ],
    "viewBox": "0 0 24 24",
    "body": "<circle cx=\"12\" cy=\"16\" r=\"1\" /> <rect x=\"3\" y=\"10\" width=\"18\" height=\"12\" rx=\"2\" /> <path d=\"M7 10V7a5 5 0 0 1 10 0v3\" />"
  },
  {
    "name": "table",
    "label": "Table",
    "tags": [
      "table",
      "data",
      "rows",
      "columns",
      "postgres",
      "schema",
      "sql"
    ],
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M12 3v18\" /> <rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" /> <path d=\"M3 9h18\" /> <path d=\"M3 15h18\" />"
  }
]
