// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconMicOff(props: IconProps) {
  return <Icon type="MicOff" {...props} />
}

export default IconMicOff
