insert into public.role_permissions (role, permission)
values
  ('owner', 'organizations.read'),
  ('owner', 'organizations.update'),
  ('owner', 'organizations.delete'),
  ('owner', 'members.read'),
  ('owner', 'members.invite'),
  ('owner', 'members.update'),
  ('owner', 'members.remove'),
  ('owner', 'projects.read'),
  ('owner', 'projects.create'),
  ('owner', 'projects.update'),
  ('owner', 'projects.delete'),
  ('admin', 'organizations.read'),
  ('admin', 'organizations.update'),
  ('admin', 'members.read'),
  ('admin', 'members.invite'),
  ('admin', 'projects.read'),
  ('admin', 'projects.create'),
  ('admin', 'projects.update'),
  ('admin', 'projects.delete'),
  ('member', 'organizations.read'),
  ('member', 'members.read'),
  ('member', 'projects.read'),
  ('member', 'projects.create'),
  ('member', 'projects.update')
on conflict do nothing;
