
\ir 01-postgis.sql
\ir 02-pgrouting.sql
\ir 03-pgtap.sql
\ir 04-pg_cron.sql
\ir 05-pgaudit.sql
\ir 06-pgjwt.sql
\ir 07-pgsql-http.sql
\ir 08-plpgsql_check.sql
\ir 09-pg-safeupdate.sql
\ir 10-timescaledb.sql
\ir 11-wal2json.sql
-- \ir 12-pljava.sql
\ir 13-plv8.sql
\ir 14-pg_plan_filter.sql
\ir 15-pg_net.sql
\ir 16-rum.sql
\ir 17-pg_hashids.sql
\ir 18-pgsodium.sql
\ir 19-pg_graphql.sql
\ir 20-pg_stat_monitor.sql
\ir 21-auto_explain.sql
\ir 22-pg_jsonschema.sql
\ir 23-vault.sql
\ir 24-pgroonga.sql
\ir 25-wrappers.sql
\ir 26-hypopg.sql
\ir 27-pg_repack.sql
\ir 28-pgvector.sql
\ir 29-pg_tle.sql
\ir 30-pg_partman.sql
