// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Scissors } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconScissors(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Scissors} {...props} />
}

export default IconScissors
