import type { TableSuggestion } from './types'

export const tableTemplates: Record<string, TableSuggestion[]> = {
  'User Management': [
    {
      tableName: 'profiles',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'user_id', type: 'uuid', nullable: false, unique: true, isForeign: true, references: 'auth.users(id)' },
        { name: 'username', type: 'varchar', nullable: true, unique: true },
        { name: 'full_name', type: 'text', nullable: true },
        { name: 'avatar_url', type: 'text', nullable: true },
        { name: 'bio', type: 'text', nullable: true },
        { name: 'website', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'User profile information extending Supabase Auth',
      source: 'template' as const,
    },
    {
      tableName: 'teams',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'varchar', nullable: false },
        { name: 'slug', type: 'varchar', nullable: false, unique: true },
        { name: 'owner_id', type: 'uuid', nullable: false, isForeign: true, references: 'profiles(id)' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Team/organization structure for multi-user collaboration',
      source: 'template' as const,
    },
    {
      tableName: 'team_members',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'team_id', type: 'uuid', nullable: false, isForeign: true, references: 'teams(id)' },
        { name: 'user_id', type: 'uuid', nullable: false, isForeign: true, references: 'profiles(id)' },
        { name: 'role', type: 'varchar', nullable: false, default: "'member'" },
        { name: 'joined_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Team membership and role assignments',
      source: 'template' as const,
    },
  ],
  'E-commerce': [
    {
      tableName: 'products',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'varchar', nullable: false },
        { name: 'slug', type: 'varchar', nullable: false, unique: true },
        { name: 'description', type: 'text', nullable: true },
        { name: 'price', type: 'numeric', nullable: false },
        { name: 'compare_at_price', type: 'numeric', nullable: true },
        { name: 'cost', type: 'numeric', nullable: true },
        { name: 'sku', type: 'varchar', nullable: true, unique: true },
        { name: 'barcode', type: 'varchar', nullable: true },
        { name: 'stock_quantity', type: 'int4', nullable: false, default: '0' },
        { name: 'weight', type: 'numeric', nullable: true },
        { name: 'published', type: 'bool', nullable: false, default: 'false' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Product catalog with inventory management',
      source: 'template' as const,
    },
    {
      tableName: 'orders',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'order_number', type: 'varchar', nullable: false, unique: true },
        { name: 'customer_id', type: 'uuid', nullable: false, isForeign: true, references: 'profiles(id)' },
        { name: 'status', type: 'varchar', nullable: false, default: "'pending'" },
        { name: 'subtotal', type: 'numeric', nullable: false },
        { name: 'tax', type: 'numeric', nullable: false, default: '0' },
        { name: 'shipping', type: 'numeric', nullable: false, default: '0' },
        { name: 'total', type: 'numeric', nullable: false },
        { name: 'notes', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Order management and tracking',
      source: 'template' as const,
    },
    {
      tableName: 'cart_items',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'user_id', type: 'uuid', nullable: false, isForeign: true, references: 'profiles(id)' },
        { name: 'product_id', type: 'uuid', nullable: false, isForeign: true, references: 'products(id)' },
        { name: 'quantity', type: 'int4', nullable: false, default: '1' },
        { name: 'added_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Shopping cart functionality',
      source: 'template' as const,
    },
  ],
  'Content Management': [
    {
      tableName: 'posts',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'title', type: 'varchar', nullable: false },
        { name: 'slug', type: 'varchar', nullable: false, unique: true },
        { name: 'content', type: 'text', nullable: true },
        { name: 'excerpt', type: 'text', nullable: true },
        { name: 'author_id', type: 'uuid', nullable: false, isForeign: true, references: 'profiles(id)' },
        { name: 'status', type: 'varchar', nullable: false, default: "'draft'" },
        { name: 'published_at', type: 'timestamptz', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Blog posts or articles',
      source: 'template' as const,
    },
    {
      tableName: 'categories',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'varchar', nullable: false },
        { name: 'slug', type: 'varchar', nullable: false, unique: true },
        { name: 'description', type: 'text', nullable: true },
        { name: 'parent_id', type: 'uuid', nullable: true, isForeign: true, references: 'categories(id)' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Hierarchical content categorization',
      source: 'template' as const,
    },
    {
      tableName: 'comments',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'post_id', type: 'uuid', nullable: false, isForeign: true, references: 'posts(id)' },
        { name: 'author_id', type: 'uuid', nullable: false, isForeign: true, references: 'profiles(id)' },
        { name: 'content', type: 'text', nullable: false },
        { name: 'parent_id', type: 'uuid', nullable: true, isForeign: true, references: 'comments(id)' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Threaded comments system',
      source: 'template' as const,
    },
  ],
  'Analytics': [
    {
      tableName: 'events',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'user_id', type: 'uuid', nullable: true, isForeign: true, references: 'profiles(id)' },
        { name: 'session_id', type: 'varchar', nullable: true },
        { name: 'event_type', type: 'varchar', nullable: false },
        { name: 'properties', type: 'jsonb', nullable: true },
        { name: 'user_agent', type: 'text', nullable: true },
        { name: 'ip_address', type: 'varchar', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Event tracking for analytics',
      source: 'template' as const,
    },
    {
      tableName: 'page_views',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'user_id', type: 'uuid', nullable: true, isForeign: true, references: 'profiles(id)' },
        { name: 'session_id', type: 'varchar', nullable: true },
        { name: 'path', type: 'varchar', nullable: false },
        { name: 'referrer', type: 'text', nullable: true },
        { name: 'duration', type: 'int4', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Page view tracking',
      source: 'template' as const,
    },
    {
      tableName: 'metrics',
      fields: [
        { name: 'id', type: 'uuid', nullable: false, isPrimary: true, default: 'gen_random_uuid()' },
        { name: 'metric_name', type: 'varchar', nullable: false },
        { name: 'value', type: 'numeric', nullable: false },
        { name: 'tags', type: 'jsonb', nullable: true },
        { name: 'timestamp', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'aggregation_period', type: 'varchar', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Custom metrics and KPI tracking',
      source: 'template' as const,
    },
  ],
}