import { TableSource, TableSuggestion } from './types'

export const tableTemplates: Record<string, TableSuggestion[]> = {
  'Social Network': [
    {
      tableName: 'profiles',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'user_id', type: 'uuid', nullable: false, unique: true },
        { name: 'username', type: 'text', nullable: true, unique: true },
        { name: 'display_name', type: 'text', nullable: true },
        { name: 'avatar_url', type: 'text', nullable: true },
        { name: 'bio', type: 'text', nullable: true },
        { name: 'location', type: 'text', nullable: true },
        { name: 'website', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Stores user profile details such as name, avatar, and bio',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'posts',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'author_id', type: 'uuid', nullable: false },
        { name: 'content', type: 'text', nullable: false },
        { name: 'image_url', type: 'text', nullable: true },
        { name: 'likes_count', type: 'int4', nullable: false, default: '0' },
        { name: 'comments_count', type: 'int4', nullable: false, default: '0' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Stores user posts, images, and engagement counts',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'follows',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'follower_id', type: 'uuid', nullable: false },
        { name: 'following_id', type: 'uuid', nullable: false },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Tracks relationships between followers and followed users',
      source: TableSource.TEMPLATE,
    },
  ],
  'E-commerce': [
    {
      tableName: 'products',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'name', type: 'text', nullable: false },
        { name: 'slug', type: 'text', nullable: false, unique: true },
        { name: 'description', type: 'text', nullable: true },
        { name: 'price', type: 'numeric', nullable: false },
        { name: 'compare_at_price', type: 'numeric', nullable: true },
        { name: 'cost', type: 'numeric', nullable: true },
        { name: 'sku', type: 'text', nullable: true, unique: true },
        { name: 'barcode', type: 'text', nullable: true },
        { name: 'stock_quantity', type: 'int4', nullable: false, default: '0' },
        { name: 'weight', type: 'numeric', nullable: true },
        { name: 'published', type: 'bool', nullable: false, default: 'false' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Stores product details, pricing, and stock levels',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'orders',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'order_number', type: 'text', nullable: false, unique: true },
        { name: 'customer_id', type: 'uuid', nullable: false },
        { name: 'status', type: 'text', nullable: false, default: 'pending' },
        { name: 'subtotal', type: 'numeric', nullable: false },
        { name: 'tax', type: 'numeric', nullable: false, default: '0' },
        { name: 'shipping', type: 'numeric', nullable: false, default: '0' },
        { name: 'total', type: 'numeric', nullable: false },
        { name: 'notes', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Manages customer orders, payment totals, and statuses',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'cart_items',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'user_id', type: 'uuid', nullable: false },
        { name: 'product_id', type: 'uuid', nullable: false },
        { name: 'quantity', type: 'int4', nullable: false, default: '1' },
        { name: 'added_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Tracks products added to customer shopping carts',
      source: TableSource.TEMPLATE,
    },
  ],
  Blog: [
    {
      tableName: 'articles',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'title', type: 'text', nullable: false },
        { name: 'slug', type: 'text', nullable: false, unique: true },
        { name: 'content', type: 'text', nullable: true },
        { name: 'excerpt', type: 'text', nullable: true },
        { name: 'cover_image', type: 'text', nullable: true },
        { name: 'author_id', type: 'uuid', nullable: false },
        { name: 'status', type: 'text', nullable: false, default: "'draft'" },
        { name: 'published_at', type: 'timestamptz', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Stores blog posts with author, status, and publish dates',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'categories',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'name', type: 'text', nullable: false },
        { name: 'slug', type: 'text', nullable: false, unique: true },
        { name: 'description', type: 'text', nullable: true },
        { name: 'color', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Organizes articles into categories or tags for filtering',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'comments',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'article_id', type: 'uuid', nullable: false },
        { name: 'author_name', type: 'text', nullable: false },
        { name: 'author_email', type: 'text', nullable: false },
        { name: 'content', type: 'text', nullable: false },
        { name: 'approved', type: 'bool', nullable: false, default: 'false' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Stores reader comments and approval status for moderation',
      source: TableSource.TEMPLATE,
    },
  ],
  'To-Do List': [
    {
      tableName: 'tasks',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'title', type: 'text', nullable: false },
        { name: 'description', type: 'text', nullable: true },
        { name: 'completed', type: 'bool', nullable: false, default: 'false' },
        { name: 'priority', type: 'text', nullable: true, default: 'medium' },
        { name: 'due_date', type: 'date', nullable: true },
        { name: 'user_id', type: 'uuid', nullable: false },
        { name: 'list_id', type: 'uuid', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Stores user tasks with priorities, due dates, and status',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'lists',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'name', type: 'text', nullable: false },
        { name: 'description', type: 'text', nullable: true },
        { name: 'color', type: 'text', nullable: true },
        { name: 'icon', type: 'text', nullable: true },
        { name: 'user_id', type: 'uuid', nullable: false },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Groups tasks into named lists for better organization',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'subtasks',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'task_id', type: 'uuid', nullable: false },
        { name: 'title', type: 'text', nullable: false },
        { name: 'completed', type: 'bool', nullable: false, default: 'false' },
        { name: 'position', type: 'int4', nullable: false, default: '0' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Tracks smaller subtasks linked to a main task',
      source: TableSource.TEMPLATE,
    },
  ],
  Analytics: [
    {
      tableName: 'events',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'user_id', type: 'uuid', nullable: true },
        { name: 'session_id', type: 'text', nullable: true },
        { name: 'event_type', type: 'text', nullable: false },
        { name: 'properties', type: 'jsonb', nullable: true },
        { name: 'user_agent', type: 'text', nullable: true },
        { name: 'ip_address', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Captures user events and properties for analytics tracking',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'page_views',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'user_id', type: 'uuid', nullable: true },
        { name: 'session_id', type: 'text', nullable: true },
        { name: 'path', type: 'text', nullable: false },
        { name: 'referrer', type: 'text', nullable: true },
        { name: 'duration', type: 'int4', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Tracks user page views, referrers, and session info',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'metrics',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'metric_name', type: 'text', nullable: false },
        { name: 'value', type: 'numeric', nullable: false },
        { name: 'tags', type: 'jsonb', nullable: true },
        { name: 'timestamp', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'aggregation_period', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Stores aggregated metrics and KPIs with timestamps',
      source: TableSource.TEMPLATE,
    },
  ],
}
