import { TableSuggestion, TableSource } from './types'

export const tableTemplates: Record<string, TableSuggestion[]> = {
  'Social Network': [
    {
      tableName: 'profiles',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'user_id',
          type: 'uuid',
          nullable: false,
          unique: true,
          isForeign: true,
          references: 'auth.users(id)',
        },
        { name: 'username', type: 'text', nullable: true, unique: true },
        { name: 'display_name', type: 'text', nullable: true },
        { name: 'avatar_url', type: 'text', nullable: true },
        { name: 'bio', type: 'text', nullable: true },
        { name: 'location', type: 'text', nullable: true },
        { name: 'website', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'User profiles for social networking',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'posts',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'author_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'profiles(id)',
        },
        { name: 'content', type: 'text', nullable: false },
        { name: 'image_url', type: 'text', nullable: true },
        { name: 'likes_count', type: 'int4', nullable: false, default: '0' },
        { name: 'comments_count', type: 'int4', nullable: false, default: '0' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Social media posts and updates',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'follows',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'follower_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'profiles(id)',
        },
        {
          name: 'following_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'profiles(id)',
        },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'User follow relationships',
      source: TableSource.TEMPLATE,
    },
  ],
  'E-commerce': [
    {
      tableName: 'products',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'name', type: 'text', nullable: false },
        { name: 'slug', type: 'text', nullable: false, unique: true },
        { name: 'description', type: 'text', nullable: true },
        { name: 'price', type: 'numeric', nullable: false },
        { name: 'compare_at_price', type: 'numeric', nullable: true },
        { name: 'cost', type: 'numeric', nullable: true },
        { name: 'sku', type: 'text', nullable: true, unique: true },
        { name: 'barcode', type: 'text', nullable: true },
        { name: 'stock_quantity', type: 'int4', nullable: false, default: '0' },
        { name: 'weight', type: 'numeric', nullable: true },
        { name: 'published', type: 'bool', nullable: false, default: 'false' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Product catalog with inventory management',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'orders',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'order_number', type: 'text', nullable: false, unique: true },
        {
          name: 'customer_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'profiles(id)',
        },
        { name: 'status', type: 'text', nullable: false, default: "'pending'" },
        { name: 'subtotal', type: 'numeric', nullable: false },
        { name: 'tax', type: 'numeric', nullable: false, default: '0' },
        { name: 'shipping', type: 'numeric', nullable: false, default: '0' },
        { name: 'total', type: 'numeric', nullable: false },
        { name: 'notes', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Order management and tracking',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'cart_items',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'user_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'profiles(id)',
        },
        {
          name: 'product_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'products(id)',
        },
        { name: 'quantity', type: 'int4', nullable: false, default: '1' },
        { name: 'added_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Shopping cart functionality',
      source: TableSource.TEMPLATE,
    },
  ],
  Blog: [
    {
      tableName: 'articles',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'title', type: 'text', nullable: false },
        { name: 'slug', type: 'text', nullable: false, unique: true },
        { name: 'content', type: 'text', nullable: true },
        { name: 'excerpt', type: 'text', nullable: true },
        { name: 'cover_image', type: 'text', nullable: true },
        {
          name: 'author_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'profiles(id)',
        },
        { name: 'status', type: 'text', nullable: false, default: "'draft'" },
        { name: 'published_at', type: 'timestamptz', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Blog articles with publishing workflow',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'categories',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'name', type: 'text', nullable: false },
        { name: 'slug', type: 'text', nullable: false, unique: true },
        { name: 'description', type: 'text', nullable: true },
        { name: 'color', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Article categories and tags',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'comments',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'article_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'articles(id)',
        },
        { name: 'author_name', type: 'text', nullable: false },
        { name: 'author_email', type: 'text', nullable: false },
        { name: 'content', type: 'text', nullable: false },
        { name: 'approved', type: 'bool', nullable: false, default: 'false' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Blog comments with moderation',
      source: TableSource.TEMPLATE,
    },
  ],
  'To-Do List': [
    {
      tableName: 'tasks',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'title', type: 'text', nullable: false },
        { name: 'description', type: 'text', nullable: true },
        { name: 'completed', type: 'bool', nullable: false, default: 'false' },
        { name: 'priority', type: 'text', nullable: true, default: "'medium'" },
        { name: 'due_date', type: 'date', nullable: true },
        {
          name: 'user_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'auth.users(id)',
        },
        { name: 'list_id', type: 'uuid', nullable: true, isForeign: true, references: 'lists(id)' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Individual tasks with priority and due dates',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'lists',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'name', type: 'text', nullable: false },
        { name: 'description', type: 'text', nullable: true },
        { name: 'color', type: 'text', nullable: true },
        { name: 'icon', type: 'text', nullable: true },
        {
          name: 'user_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'auth.users(id)',
        },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'updated_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Task lists for organization',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'subtasks',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'task_id',
          type: 'uuid',
          nullable: false,
          isForeign: true,
          references: 'tasks(id)',
        },
        { name: 'title', type: 'text', nullable: false },
        { name: 'completed', type: 'bool', nullable: false, default: 'false' },
        { name: 'position', type: 'int4', nullable: false, default: '0' },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Subtasks for breaking down larger tasks',
      source: TableSource.TEMPLATE,
    },
  ],
  Analytics: [
    {
      tableName: 'events',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'user_id',
          type: 'uuid',
          nullable: true,
          isForeign: true,
          references: 'profiles(id)',
        },
        { name: 'session_id', type: 'text', nullable: true },
        { name: 'event_type', type: 'text', nullable: false },
        { name: 'properties', type: 'jsonb', nullable: true },
        { name: 'user_agent', type: 'text', nullable: true },
        { name: 'ip_address', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Event tracking for analytics',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'page_views',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'user_id',
          type: 'uuid',
          nullable: true,
          isForeign: true,
          references: 'profiles(id)',
        },
        { name: 'session_id', type: 'text', nullable: true },
        { name: 'path', type: 'text', nullable: false },
        { name: 'referrer', type: 'text', nullable: true },
        { name: 'duration', type: 'int4', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Page view tracking',
      source: TableSource.TEMPLATE,
    },
    {
      tableName: 'metrics',
      fields: [
        {
          name: 'id',
          type: 'uuid',
          nullable: false,
          isPrimary: true,
          default: 'gen_random_uuid()',
        },
        { name: 'metric_name', type: 'text', nullable: false },
        { name: 'value', type: 'numeric', nullable: false },
        { name: 'tags', type: 'jsonb', nullable: true },
        { name: 'timestamp', type: 'timestamptz', nullable: false, default: 'now()' },
        { name: 'aggregation_period', type: 'text', nullable: true },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
      rationale: 'Custom metrics and KPI tracking',
      source: TableSource.TEMPLATE,
    },
  ],
}
