// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconArrowRightCircle(props: IconProps) {
  return <Icon type="ArrowRightCircle" {...props} />
}

export default IconArrowRightCircle
