const prs = [
  {
    number: 42970,
    title: 'chore(studio): polish database settings',
    url: 'https://github.com/supabase/supabase/pull/42970',
    author: 'dnywh',
    createdAt: '2026-02-18T03:33:46Z',
    hoursOld: 35,
    daysOld: 1,
    fileCount: 12,
    reviewStatus: 'no-reviews',
    reviewEmoji: ':eyes:',
    mergeableStatus: 'blocked',
    mergeableEmoji: ':no_entry:',
  },
  {
    number: 42964,
    title: 'chore: image transformation and storage settings entitlements',
    url: 'https://github.com/supabase/supabase/pull/42964',
    author: 'ignaciodob',
    createdAt: '2026-02-17T22:40:19Z',
    hoursOld: 40,
    daysOld: 1,
    fileCount: 1,
    reviewStatus: 'no-reviews',
    reviewEmoji: ':eyes:',
    mergeableStatus: 'blocked',
    mergeableEmoji: ':no_entry:',
  },
  {
    number: 42963,
    title: 'feat(assistant): enable Braintrust tracing for non-sensitive chats',
    url: 'https://github.com/supabase/supabase/pull/42963',
    author: 'mattrossman',
    createdAt: '2026-02-17T21:29:06Z',
    hoursOld: 41,
    daysOld: 1,
    fileCount: 8,
    reviewStatus: 'no-reviews',
    reviewEmoji: ':eyes:',
    mergeableStatus: 'blocked',
    mergeableEmoji: ':no_entry:',
  },
  {
    number: 42868,
    title: 'wip studio layout',
    url: 'https://github.com/supabase/supabase/pull/42868',
    author: 'fsansalvadore',
    createdAt: '2026-02-16T16:22:08Z',
    hoursOld: 70,
    daysOld: 2,
    fileCount: 9,
    reviewStatus: 'no-reviews',
    reviewEmoji: ':eyes:',
    mergeableStatus: 'unstable',
    mergeableEmoji: ':warning:',
  },
  {
    number: 42087,
    title: 'Move JWT Page',
    url: 'https://github.com/supabase/supabase/pull/42087',
    author: 'SaxonF',
    createdAt: '2026-01-23T01:51:24Z',
    hoursOld: 661,
    daysOld: 27,
    fileCount: 9,
    reviewStatus: 'no-reviews',
    reviewEmoji: ':eyes:',
    mergeableStatus: 'unknown',
    mergeableEmoji: ':grey_question:',
  },
]
