// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconXSquare(props: IconProps) {
  return <Icon type="XSquare" {...props} />
}

export default IconXSquare
