create table
  public.lw12_tickets (
    id uuid not null default auth.uid (),
    email text null,
    name text null,
    username text null,
    "createdAt" timestamp with time zone not null default timezone ('utc'::text, now()),
    referred_by text null,
    "sharedOnTwitter" timestamp with time zone null,
    "sharedOnLinkedIn" timestamp with time zone null,
    metadata jsonb null,
    "gameWonAt" timestamp with time zone null,
    "ticketNumber" bigint generated by default as identity,
    constraint lw12_tickets_pkey primary key (id),
    constraint lw12_tickets_email_key unique (email),
    constraint lw12_tickets_ticketNumberInt_key unique ("ticketNumber"),
    constraint lw12_tickets_username_key unique (username),
    constraint public_lw12_tickets_id_fkey foreign key (id) references auth.users (id)
  ) tablespace pg_default;

alter table "public"."lw12_tickets" enable row level security;

create policy "Allow authenticated to select own ticket"
on "public"."lw12_tickets"
as permissive
for all
to authenticated
using ((id = auth.uid()));


create policy "Allow user to update its own ticket"
on "public"."lw12_tickets"
as permissive
for update
to authenticated
using ((id = auth.uid()))
with check ((id = auth.uid()));


create policy "Enable insert for authenticated users only"
on "public"."lw12_tickets"
as permissive
for insert
to authenticated
with check ((id = auth.uid()));