// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconUserCheck(props: IconProps) {
  return <Icon type="UserCheck" {...props} />
}

export default IconUserCheck
