import Head from 'next/head'
import DashboardLayout from '../components/layouts/DashboardLayout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <DashboardLayout>
      <div className={styles.container}>
        <Head>
          <title>Supabase | Table</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Table</h1>
        </main>
      </div>
    </DashboardLayout>
  )
}
