// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconUserMinus(props: IconProps) {
  return <Icon type="UserMinus" {...props} />
}

export default IconUserMinus
