// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconCloudRain(props: IconProps) {
  return <Icon type="CloudRain" {...props} />
}

export default IconCloudRain
