// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconCompass(props: IconProps) {
  return <Icon type="Compass" {...props} />
}

export default IconCompass
