// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Volume } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconVolume(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Volume} {...props} />
}

export default IconVolume
