// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconFastForward(props: IconProps) {
  return <Icon type="FastForward" {...props} />
}

export default IconFastForward
