// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Meh } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconMeh(props: any) {
    return <IconBase icon={Meh} {...props} />
  }

  export default IconMeh
  