// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { StopCircle } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconStopCircle(props: any) {
    return <IconBase icon={StopCircle} {...props} />
  }

  export default IconStopCircle
  