// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { Sunset } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconSunset(props: any) {
    return <IconBase icon={Sunset} {...props} />
  }

  export default IconSunset
  