// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { ArrowDownRight } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconArrowDownRight(props: any) {
    return <IconBase icon={ArrowDownRight} {...props} />
  }

  export default IconArrowDownRight
  