// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconTriangle(props: IconProps) {
  return <Icon type="Triangle" {...props} />
}

export default IconTriangle
