// [Joshen] Maybe shift this into shared-types repo or something?
// This isn't typed completely properly as I'm not too sure myself
export interface AuthConfig {
  id: number
  project_id: number
  updated_at: string

  DISABLE_SIGNUP: boolean
  EXTERNAL_EMAIL_ENABLED: boolean
  EXTERNAL_PHONE_ENABLED: boolean

  EXTERNAL_APPLE_ENABLED: boolean
  EXTERNAL_APPLE_CLIENT_ID: string | null
  EXTERNAL_APPLE_SECRET: string | null

  EXTERNAL_AZURE_ENABLED: boolean
  EXTERNAL_AZURE_URL: string | null
  EXTERNAL_AZURE_CLIENT_ID: string | null
  EXTERNAL_AZURE_SECRET: string | null

  EXTERNAL_BITBUCKET_ENABLED: boolean
  EXTERNAL_BITBUCKET_CLIENT_ID: string | null
  EXTERNAL_BITBUCKET_SECRET: string | null

  EXTERNAL_DISCORD_ENABLED: boolean
  EXTERNAL_DISCORD_CLIENT_ID: string | null
  EXTERNAL_DISCORD_SECRET: string | null

  EXTERNAL_FACEBOOK_ENABLED: boolean
  EXTERNAL_FACEBOOK_CLIENT_ID: string | null
  EXTERNAL_FACEBOOK_SECRET: string | null

  EXTERNAL_FIGMA_ENABLED: boolean
  EXTERNAL_FIGMA_CLIENT_ID: string | null
  EXTERNAL_FIGMA_SECRET: string | null

  EXTERNAL_GITHUB_ENABLED: false
  EXTERNAL_GITHUB_CLIENT_ID: string | null
  EXTERNAL_GITHUB_SECRET: string | null

  EXTERNAL_GITLAB_ENABLED: boolean
  EXTERNAL_GITLAB_CLIENT_ID: string | null
  EXTERNAL_GITLAB_REDIRECT_URI: string | null
  EXTERNAL_GITLAB_SECRET: string | null

  EXTERNAL_GOOGLE_ENABLED: boolean
  EXTERNAL_GOOGLE_CLIENT_ID: string | null
  EXTERNAL_GOOGLE_SECRET: string | null

  EXTERNAL_KEYCLOAK_ENABLED: boolean
  EXTERNAL_KEYCLOAK_CLIENT_ID: string | null
  EXTERNAL_KEYCLOAK_SECRET: string | null
  EXTERNAL_KEYCLOAK_URL: string | null

  EXTERNAL_LINKEDIN_ENABLED: boolean
  EXTERNAL_LINKEDIN_CLIENT_ID: string | null
  EXTERNAL_LINKEDIN_SECRET: string | null

  EXTERNAL_LINKEDIN_OIDC_ENABLED: boolean
  EXTERNAL_LINKEDIN_OIDC_CLIENT_ID: string | null
  EXTERNAL_LINKEDIN_OIDC_SECRET: string | null

  EXTERNAL_NOTION_ENABLED: boolean
  EXTERNAL_NOTION_CLIENT_ID: string | null
  EXTERNAL_NOTION_SECRET: string | null

  EXTERNAL_SLACK_ENABLED: boolean
  EXTERNAL_SLACK_CLIENT_ID: string | null
  EXTERNAL_SLACK_SECRET: string | null

  EXTERNAL_SPOTIFY_ENABLED: boolean
  EXTERNAL_SPOTIFY_CLIENT_ID: string | null
  EXTERNAL_SPOTIFY_SECRET: string | null

  EXTERNAL_TWITCH_ENABLED: boolean
  EXTERNAL_TWITCH_CLIENT_ID: string | null
  EXTERNAL_TWITCH_SECRET: string | null

  EXTERNAL_TWITTER_ENABLED: boolean
  EXTERNAL_TWITTER_CLIENT_ID: string | null
  EXTERNAL_TWITTER_SECRET: string | null

  EXTERNAL_WORKOS_ENABLED: boolean
  EXTERNAL_WORKOS_CLIENT_ID: string | null
  EXTERNAL_WORKOS_SECRET: string | null
  EXTERNAL_WORKOS_URL: string | null

  EXTERNAL_ZOOM_ENABLED: boolean
  EXTERNAL_ZOOM_CLIENT_ID: string | null
  EXTERNAL_ZOOM_SECRET: string | null

  JWT_AUD: 'authenticated' | string
  JWT_DEFAULT_GROUP_NAME: 'authenticated' | string
  JWT_EXP: number

  MAILER_AUTOCONFIRM: boolean
  MAILER_OTP_EXP: number
  MAILER_SECURE_EMAIL_CHANGE_ENABLED: boolean
  MAILER_SUBJECTS_CONFIRMATION: string
  MAILER_SUBJECTS_EMAIL_CHANGE: string
  MAILER_SUBJECTS_INVITE: string
  MAILER_SUBJECTS_MAGIC_LINK: string
  MAILER_SUBJECTS_RECOVERY: string
  MAILER_TEMPLATES_CONFIRMATION: string | null
  MAILER_TEMPLATES_CONFIRMATION_CONTENT: string
  MAILER_TEMPLATES_EMAIL_CHANGE: string | null
  MAILER_TEMPLATES_EMAIL_CHANGE_CONTENT: string
  MAILER_TEMPLATES_INVITE: string | null
  MAILER_TEMPLATES_INVITE_CONTENT: string
  MAILER_TEMPLATES_MAGIC_LINK: string | null
  MAILER_TEMPLATES_MAGIC_LINK_CONTENT: string
  MAILER_TEMPLATES_RECOVERY: string | null
  MAILER_TEMPLATES_RECOVERY_CONTENT: string
  MAILER_URLPATHS_CONFIRMATION: string
  MAILER_URLPATHS_EMAIL_CHANGE: string
  MAILER_URLPATHS_INVITE: string
  MAILER_URLPATHS_RECOVERY: string

  OPERATOR_TOKEN: string | null
  PASSWORD_MIN_LENGTH: number
  RATE_LIMIT_EMAIL_SENT: number
  RATE_LIMIT_SMS_SENT: number
  RATE_LIMIT_HEADER: string | null
  RATE_LIMIT_TOKEN_REFRESH: number
  RATE_LIMIT_VERIFY: number
  REFRESH_TOKEN_ROTATION_ENABLED: boolean

  SECURITY_CAPTCHA_ENABLED: boolean
  SECURITY_CAPTCHA_PROVIDER: 'hcaptcha' | 'turnstile' | string
  SECURITY_CAPTCHA_SECRET: string
  SECURITY_REFRESH_TOKEN_REUSE_INTERVAL: number
  SECURITY_UPDATE_PASSWORD_REQUIRE_REAUTHENTICATION: boolean

  SITE_URL: string
  SMS_AUTOCONFIRM: boolean
  SMS_MAX_FREQUENCY: number
  SMS_MESSAGEBIRD_ACCESS_KEY: string
  SMS_MESSAGEBIRD_ORIGINATOR: string
  SMS_OTP_EXP: number
  SMS_OTP_LENGTH: number
  SMS_PROVIDER: 'twilio' | string
  SMS_TEMPLATE: string
  SMS_TEXTLOCAL_API_KEY: string
  SMS_TEXTLOCAL_SENDER: string
  SMS_TWILIO_ACCOUNT_SID: string
  SMS_TWILIO_AUTH_TOKEN: string
  SMS_TWILIO_CONTENT_SID: string
  SMS_TWILIO_MESSAGE_SERVICE_SID: string
  SMS_TWILIO_VERIFY_ACCOUNT_SID: string
  SMS_TWILIO_VERIFY_AUTH_TOKEN: string
  SMS_TWILIO_VERIFY_MESSAGE_SERVICE_SID: string
  SMS_VONAGE_API_KEY: string
  SMS_VONAGE_API_SECRET: string
  SMS_VONAGE_FROM: string
  SMTP_ADMIN_EMAIL: string | null
  SMTP_HOST: string | null
  SMTP_MAX_FREQUENCY: number
  SMTP_PASS: string | null
  SMTP_PASS_ENCRYPTED: string | null
  SMTP_PORT: number | string | null
  SMTP_SENDER_NAME: string | null
  SMTP_USER: string | null
  URI_ALLOW_LIST: string
}
