// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Tool } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconTool(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Tool} {...props} />
}

export default IconTool
