// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { Cast } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconCast(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={Cast} {...props} />
}

export default IconCast
