// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconYoutube(props: IconProps) {
  return <Icon type="Youtube" {...props} />
}

export default IconYoutube
