// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import * as React from 'react'
  // @ts-ignore
  import { FileMinus } from 'react-feather'
  import IconBase from './../../IconBase'

  function IconFileMinus(props: any) {
    return <IconBase icon={FileMinus} {...props} />
  }

  export default IconFileMinus
  