// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconFileMinus(props: IconProps) {
  return <Icon type="FileMinus" {...props} />
}

export default IconFileMinus
