name: Config (Production)

on:
  push:
    branches:
      - master
    paths:
      - "supabase/remotes/**"
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      TF_VAR_linked_project: xguihxuzqibwxjnimxev
    defaults:
      run:
        working-directory: supabase/remotes

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - run: terraform init
      - run: terraform apply -auto-approve -no-color
