name: Deploy studio app to staging on vercel
on:
  push:
    branches:
      - master
    paths:
      - 'studio/**'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      # remove ./studio/pages/api folder before deploying to vercel
      - uses: JesseTG/rm@v1.0.2
        with:
          path: ./studio/pages/api
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-comment: false
          vercel-args: '--prod -A .vercel/staging.json'
          vercel-org-id: team_E6KJ1W561hMTjon1QSwOh0WO #Required
          vercel-project-id: QmcmhbiAtCMFTAHCuGgQscNbke4TzgWULECctNcKmxWCoT #Required
          working-directory: ./studio #Your Working Directory, Optional
          vercel-project-name: staging-app
