name: Comment on external PRs

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  comment-on-external-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != github.repository && !contains(fromJson('["dependabot[bot]", "github-actions[bot]", "renovate[bot]"]'), github.actor)
    steps:
      - name: Comment on PR
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            const sender = context.payload.pull_request.user.login;

            const query = `query($q:String!) {
              search(query:$q, type: ISSUE, first: 2) {
                issueCount
              }
            }`;
            
            const variables = {
              q: `repo:${context.repo.owner}/${context.repo.repo} is:pr author:${sender}`
            };

            const result = await github.graphql(query, variables);
            const totalCount = result.search.issueCount;

            let greeting = "Thanks for contributing to Supabase! ❤️ Our team will review your PR.";
            if (totalCount === 1) {
              greeting = "Welcome to the Supabase community! 🎉 Thank you for creating your very first pull request. ❤️ Our team will review your PR shortly.";
            }

            const commentBody = `
            ${greeting}

            A few tips for a smoother review process:
            - If you have a local version of the repo, run \`pnpm run format\` to make sure formatting checks pass.
            - Once we've reviewed your PR, please don't trivially merge master (don't click \`Update branch\` if there are no merge conflicts to be fixed). This invalidates any pre-merge checks we've run.
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });