name: 'Pull Request Labeler'

# only docs uses the labeler at the moment
on:
  pull_request_target:
    paths:
      - 'apps/docs/**/*'

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
