name: Nix CI

on:
  push:
    branches:
      - release/*
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  id-token: write
  # required by testinfra-ami-build dependent workflows
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  eval:
    runs-on: blacksmith-32vcpu-ubuntu-2404
    outputs:
      packages_matrix: ${{ steps.gen-matrix.outputs.packages_matrix }}
      checks_matrix: ${{ steps.gen-matrix.outputs.checks_matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install nix
        uses: ./.github/actions/nix-install-ephemeral
        with:
          push-to-cache: true
          nix-signing-key: ${{ secrets.NIX_SIGN_SECRET_KEY }}
          role-to-assume: ${{ secrets.DEV_AWS_ROLE }}

      - name: Generate Nix Matrix
        id: gen-matrix
        run: |
          set -Eeu -o pipefail
          nix run --accept-flake-config .\#github-matrix -- checks legacyPackages

          sudo systemctl stop nix-daemon.socket || true
          sudo systemctl stop nix-daemon.service || true
          sudo pkill -9 nix-daemon || true
          sleep 2

  builds-aarch64-linux:
    name: ${{ matrix.name }}${{ matrix.postgresql_version || '' }}
    needs: eval
    runs-on: ${{ matrix.runs_on.group && matrix.runs_on || matrix.runs_on.labels }}
    if: ${{ fromJSON(needs.eval.outputs.packages_matrix).aarch64_linux != null }}
    strategy:
      fail-fast: false
      max-parallel: 25
      matrix: ${{ fromJSON(needs.eval.outputs.packages_matrix).aarch64_linux }}
    steps:
      - name: Checkout Repo
        if: ${{ matrix.attr != '' }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install nix
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-install-ephemeral
        with:
          push-to-cache: true
          nix-signing-key: ${{ secrets.NIX_SIGN_SECRET_KEY }}
          role-to-assume: ${{ secrets.DEV_AWS_ROLE }}
      - name: nix build
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-build-retry
        with:
          attr: .#${{ matrix.attr }}

  checks-aarch64-linux:
    name: ${{ matrix.name }}${{ matrix.postgresql_version || '' }}
    needs:
      - eval
      - builds-aarch64-linux
    runs-on: ${{ matrix.runs_on.group && matrix.runs_on || matrix.runs_on.labels }}
    if: ${{ fromJSON(needs.eval.outputs.checks_matrix).aarch64_linux != null }}
    strategy:
      fail-fast: false
      max-parallel: 25
      matrix: ${{ fromJSON(needs.eval.outputs.checks_matrix).aarch64_linux }}
    steps:
      - name: Checkout Repo
        if: ${{ matrix.attr != '' }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install nix
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-install-ephemeral
        with:
          push-to-cache: true
          nix-signing-key: ${{ secrets.NIX_SIGN_SECRET_KEY }}
          role-to-assume: ${{ secrets.DEV_AWS_ROLE }}
      - name: nix build
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-build-retry
        with:
          attr: .#${{ matrix.attr }}

  builds-aarch64-darwin:
    name: ${{ matrix.name }}${{ matrix.postgresql_version || '' }}
    needs: eval
    runs-on: ${{ matrix.attr != '' && matrix.runs_on.group && matrix.runs_on || matrix.runs_on.labels }}
    if: ${{ fromJSON(needs.eval.outputs.packages_matrix).aarch64_darwin != null }}
    strategy:
      fail-fast: false
      max-parallel: 25
      matrix: ${{ fromJSON(needs.eval.outputs.packages_matrix).aarch64_darwin }}
    steps:
      - name: Checkout Repo
        if: ${{ matrix.attr != '' }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install nix (ephemeral)
        if: ${{ matrix.attr != '' && matrix.runs_on.group != 'self-hosted-runners-nix' }}
        uses: ./.github/actions/nix-install-ephemeral
        with:
          push-to-cache: true
          nix-signing-key: ${{ secrets.NIX_SIGN_SECRET_KEY }}
          role-to-assume: ${{ secrets.DEV_AWS_ROLE }}
      - name: Install nix (self-hosted)
        if: ${{ matrix.attr != '' && matrix.runs_on.group == 'self-hosted-runners-nix' }}
        uses: ./.github/actions/nix-install-self-hosted
      - name: nix build
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-build-retry
        with:
          attr: .#${{ matrix.attr }}

  checks-aarch64-darwin:
    name: ${{ matrix.name }}${{ matrix.postgresql_version || '' }}
    needs:
      - eval
      - builds-aarch64-darwin
    runs-on: ${{ matrix.attr != '' && matrix.runs_on.group && matrix.runs_on || matrix.runs_on.labels }}
    if: ${{ fromJSON(needs.eval.outputs.checks_matrix).aarch64_darwin != null }}
    strategy:
      fail-fast: false
      max-parallel: 25
      matrix: ${{ fromJSON(needs.eval.outputs.checks_matrix).aarch64_darwin }}
    steps:
      - name: Checkout Repo
        if: ${{ matrix.attr != '' }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install nix
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-install-ephemeral
        with:
          push-to-cache: true
          nix-signing-key: ${{ secrets.NIX_SIGN_SECRET_KEY }}
          role-to-assume: ${{ secrets.DEV_AWS_ROLE }}
      - name: nix build
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-build-retry
        with:
          attr: .#${{ matrix.attr }}

  builds-x86_64-linux:
    name: ${{ matrix.name }}${{ matrix.postgresql_version || '' }}
    needs: eval
    runs-on: ${{ matrix.attr != '' && matrix.runs_on.group && matrix.runs_on || matrix.runs_on.labels }}
    if: ${{ fromJSON(needs.eval.outputs.packages_matrix).x86_64_linux != null }}
    strategy:
      fail-fast: false
      max-parallel: 25
      matrix: ${{ fromJSON(needs.eval.outputs.packages_matrix).x86_64_linux }}
    steps:
      - name: Checkout Repo
        if: ${{ matrix.attr != '' }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install nix
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-install-ephemeral
        with:
          push-to-cache: true
          nix-signing-key: ${{ secrets.NIX_SIGN_SECRET_KEY }}
          role-to-assume: ${{ secrets.DEV_AWS_ROLE }}
      - name: nix build
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-build-retry
        with:
          attr: .#${{ matrix.attr }}

  checks-x86_64-linux:
    name: ${{ matrix.name }}${{ matrix.postgresql_version || '' }}
    needs:
      - eval
      - builds-x86_64-linux
    runs-on: ${{ matrix.attr != '' && matrix.runs_on.group && matrix.runs_on || matrix.runs_on.labels }}
    if: ${{ fromJSON(needs.eval.outputs.checks_matrix).x86_64_linux != null }}
    strategy:
      fail-fast: false
      max-parallel: 25
      matrix: ${{ fromJSON(needs.eval.outputs.checks_matrix).x86_64_linux }}
    steps:
      - name: Checkout Repo
        if: ${{ matrix.attr != '' }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install nix
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-install-ephemeral
        with:
          push-to-cache: true
          nix-signing-key: ${{ secrets.NIX_SIGN_SECRET_KEY }}
          role-to-assume: ${{ secrets.DEV_AWS_ROLE }}
      - name: nix build
        if: ${{ matrix.attr != '' }}
        uses: ./.github/actions/nix-build-retry
        with:
          attr: .#${{ matrix.attr }}

  checks:
    name: Nix Checks ✅
    runs-on: blacksmith-2vcpu-ubuntu-2404
    needs:
      - checks-aarch64-darwin
      - checks-aarch64-linux
      - checks-x86_64-linux
    steps:
      - name: Check dependent job results
        if: contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped')
        run: |
          jq -rn --argjson needs '${{ toJSON(needs) }}' '$needs|to_entries[]|select(.value.result!="success")|"::error::"+.key+": "+.value.result'
          exit 1

  amis:
    needs:
      - builds-aarch64-linux
      - builds-x86_64-linux
    uses: ./.github/workflows/testinfra-ami-build.yml
    secrets:
      DEV_AWS_ROLE: ${{ secrets.DEV_AWS_ROLE }}
      NIX_SIGN_SECRET_KEY: ${{ secrets.NIX_SIGN_SECRET_KEY }}

  schema:
    needs:
      - builds-aarch64-linux
      - builds-x86_64-linux
    uses: ./.github/workflows/test.yml

  containers:
    needs: builds-aarch64-linux
    uses: ./.github/workflows/docker-image-test.yml
    secrets:
      DEV_AWS_ROLE: ${{ secrets.DEV_AWS_ROLE }}
      NIX_SIGN_SECRET_KEY: ${{ secrets.NIX_SIGN_SECRET_KEY }}

  check:
    name: Nix CI ✅
    if: always()
    runs-on: blacksmith-2vcpu-ubuntu-2404
    needs:
      - amis
      - checks
      - containers
      - schema
    steps:
      - name: Check dependent job results
        if: contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped')
        run: |
          jq -rn --argjson needs '${{ toJSON(needs) }}' '$needs|to_entries[]|select(.value.result!="success")|"::error::"+.key+": "+.value.result'
          exit 1
