name: Deploy OG Images

on:
  push:
    branches:
      - master
    paths:
      - 'supabase/functions/og-images/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.OG_IMAGE_SUPABASE_PROJECT_ID }}

    steps:
      - name: Check out repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Setup the Supabase CLI
        uses: supabase/setup-cli@ab058987d8d6c725971f6cf9d0b5c98467e30bd1 # v1.7.1
        with:
          version: latest

      - run: supabase functions deploy og-images --project-ref $PROJECT_ID --no-verify-jwt
