// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { CornerLeftDown } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconCornerLeftDown(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={CornerLeftDown} {...props} />
}

export default IconCornerLeftDown
