// DO NOT EDIT
// this file is generated by /internals/populate-icons script

import Icon, { IconProps } from '../../Icon'

function IconMessageCircle(props: IconProps) {
  return <Icon type="MessageCircle" {...props} />
}

export default IconMessageCircle
