// DO NOT EDIT - this file is generated by /internals/populate-icons script
import * as React from 'react'
// @ts-ignore
import { MessageCircle } from 'react-feather'
import IconBase, { IconBaseProps } from './../../IconBase'

function IconMessageCircle(props: Omit<IconBaseProps, 'icon'>) {
  return <IconBase icon={MessageCircle} {...props} />
}

export default IconMessageCircle
