description = "Remove '%s' to avoid marketing language and describe what the feature does specifically."
level = "WARNING"
words = [
    "best in class",
    "best-in-class",
    "cutting edge",
    "cutting-edge",
    "effortlessly",
    "game changer",
    "game-changer",
    "hassle free",
    "hassle-free",
    "powerful",
    "seamlessly",
]
