description = "Prefer '%r' to '%s'."
level = "WARNING"
words = [
    [
        "PostgreSQL",
        "Postgres",
    ],
    [
        "concurrent clients",
        "concurrent connections",
    ],
    [
        "utilize",
        "use",
    ],
    [
        "utilise",
        "use",
    ],
    [
        "utilizes",
        "uses",
    ],
    [
        "utilises",
        "uses",
    ],
    [
        "utilizing",
        "using",
    ],
    [
        "utilising",
        "using",
    ],
]
